DECLARE @Map TABLE([TableName] [nvarchar](200) NOT NULL,
	[ColumnName] [nvarchar](200) NOT NULL,
	[FriendlyName] [nvarchar](256) NOT NULL,
	[Exclude] [bit] NOT NULL,
	[LinkField] [nvarchar](1000)
	)
DECLARE @DbName NVARCHAR(128) = DB_NAME()

INSERT INTO @Map ([TableName], [ColumnName], [FriendlyName], [Exclude], [LinkField]) 
VALUES 
-- dbo schema inserts
 (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addCountry', N'Country', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addDXCode', N'DX Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addExtTxtID', N'External Text ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addID', N'Address ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addLine1', N'Address 1', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addLine2', N'Address 2', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addLine3', N'Address 3', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addLine4', N'Address 4', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addLine5', N'Address 5', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'addPostcode', N'Postcode', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'Created', N'Created', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'CreatedBy', N'Created By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'Updated', N'Updated ', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAddress]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocActive', N'Active', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocAddressee', N'Addressee', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocDDI', N'DDI', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocDefAddSetting', N'Default Address Setting', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocdefaultaddID', N'Default Address ID', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocEmail', N'Email', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocEmployeeID', N'Employee ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocFax', N'Fax', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocHeading', N'Heading', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocID', N'Associate ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocMobile', N'Mobile', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocNotes', N'Associate Notes', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocOrder', N'Order', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocPrefContactMethod', N'Preferred Method of Contact', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocRef', N'Reference', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocSalut', N'Salutation', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocType', N'Type', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''SUBASSOC'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'assocUseDX', N'Use DX', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'contID', N'Contact ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'fileID', N'Matter ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'Updated', N'Updated', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbAssociates]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'brID', N'Branch', 0, N'select @VALUE = brName from dbBranch where brID = Convert(int, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clAccCode', N'Account Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clActiveComplaints', N'Active Complaints', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clActiveUndertakings', N'Active Undertakings', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clAddInfo', N'Additional Information', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clAutoCreated', N'Auto Created', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clAutoSource', N'Auto Source', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clAutoType', N'Auto Type', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clDefaultAddress', N'Default Address', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clDefaultContact', N'Default Contact', 0, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clextID', N'External ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clexttxtID', N'External Text ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clGroup', N'Group', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clID', N'Client ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clMarket', N'Market', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clName', N'Client Name', 0, NULL)
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clNeedExport', N'Need Export', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clNickname', N'Nickname', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clNo', N'Client Number', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clNotes', N'Notes', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clPassword', N'Password', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clPasswordHint', N'Password Hint', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clPreClient', N'Pre-Client', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clPreClientConvDate', N'Pre-Client Conversion Date', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clRegisterCount', N'Register Count', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSearch1', N'Search 1', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSearch2', N'Search 2', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSearch3', N'Search 3', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSearch4', N'Search 4', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSearch5', N'Search 5', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSource', N'Source', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSourceContact', N'Source Contact', 0, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clSourceUser', N'Source User', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clStatus', N'Status', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clStop', N'Stop', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clStopReason', N'Stop Reason', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clStorageProvider', N'Storage Provider', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'cltypeCode', N'Type Code', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''CLTYPE'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'clUICultureInfo', N'Culture', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'feeusrID', N'Fee Earner', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'SecurityOptions', N'Security Options', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'Updated', N'Updated', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClient]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'clActive', N'Active', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'clID', N'Client ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'clNotePad', N'Note Pad', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'clPosition', N'Position', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'clRelation', N'Relation', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'contID', N'Contact ID', 0, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'ID', N'ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbClientContacts]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contAddFilter', N'Address Filter', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contAddInfo', N'', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contAddressee', N'Addressee', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contApproved', N'Approved', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contApprRevokedOn', N'Approval Revoked On', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contDefaultAddress', N'Default Address', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contExtTxtID', N'External Text ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contGrade', N'Grade', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contGroup', N'Group', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contGuid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contID', N'Contact ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contIdent', N'Identity 1', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contIdent2', N'Identity 2', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contIsClient', N'Contact is Client', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contLARef', N'Legal Aid Reference', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contMarketable', N'Marketable', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contName', N'Name', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contNotes', N'Notes', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contPrecLibrary', N'Precedent Library', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contPrefContactMethod', N'Preferred Method of Contact', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contSalut', N'Salutation', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contShortName', N'Short Name', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contSource', N'Source', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contTypeCode', N'Type Code', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''CONTTYPE'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contWebsite', N'Website', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'contXMASCard', N'Xmas Card', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'SecurityOptions', N'Security Options', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'Updated', N'Updated', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContact]', N'UserID', N'User ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactAddresses]', N'contActive', N'Active', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactAddresses]', N'contaddID', N'Address', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactAddresses]', N'contCode', N'Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactAddresses]', N'contID', N'Contact ID', 1, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactAddresses]', N'contOrder', N'Order', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactAddresses]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'contActive', N'Active', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'contCode', N'Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'contDefaultOrder', N'Default Order', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'contEmail', N'Email', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'contID', N'Contact ID', 1, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'contOrder', N'Order', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactEmails]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contChristianNames', N'First Name(s)', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contDisabilityFlag', N'Disability', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''DISABILITY'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contDOB', N'DOB', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contDOD', N'DOD', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contEthnicOrigin', N'Ethnic Origin', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''ETHNIC'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contID', N'Contact ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contIdentity', N'Identity', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contIdentity2', N'Identity 2', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contInitials', N'Initials', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contInterest1', N'Interest', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contInterest2', N'Interest 2', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contInterest3', N'Interest 3', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contMaidenName', N'Maiden Name', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contMaritalStatus', N'Marital Status', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''MARITALSTATUS'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contNationality', N'Nationality', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contNINumber', N'National Insurance', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contNOK', N'Next of Kin', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contNOKaddID', N'Next of Kin Address', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contOccupation', N'Occupation', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''OCCUPATION'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contPOB', N'POB', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contReligion', N'Religion', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contResidence', N'Residence', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contResidencePrevious', N'Previous Residence', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contResidenceSince', N'Residence Since', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contSex', N'Sex', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''SEX'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contSpouseName', N'Spouse Name', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contSpouseName2', N'Spouse Name 2', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contSurname', N'Surname', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'contTitle', N'Title', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'fdcontSurnameAtBirth', N'Surname at Birth', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactIndividual]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contActive', N'Active', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contCode', N'Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contDefaultOrder', N'Default Order', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contExtraCode', N'Extra Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contID', N'Contact ID', 1, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contNumber', N'Number', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'contOrder', N'Order', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbContactNumbers]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'brID', N'Branch', 0, N'select @VALUE = brName from dbBranch where brID = Convert(int, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'clID', N'Client ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'DefaultAssociateID', N'Default Associate', 0, N'select @VALUE = contName from dbAssociates a inner join dbContact c on a.contID = c.contID where assocID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileAccCode', N'Account Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileAgreementDate', N'Agreement Date', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileAlertLevel', N'Alert Level', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileAlertMessage', N'Alert Messages', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileAllowExternal', N'Allow External', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileArchiveDate', N'Archive Date', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileArchiveRef', N'Archive Ref', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileBanding', N'Banding', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileBTD', N'BTD', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileClosed', N'Closed', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileClosedby', N'Closed By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileComplexity', N'Complexity', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileConflictCheck', N'Conflict Check', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileConflictFound', N'Conflicts Found', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileConflictNotes', N'Conflict Notes', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileCost', N'Cost', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileCreditLimit', N'Credit Limit', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'filecurISOCode', N'ISO Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileDepartment', N'Department', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileDesc', N'Description', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileDestroyDate', N'Destroy Date', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileEstimate', N'Estimate', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileExternalNotes', N'External Notes', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileExtLinkID', N'External Link ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileExtLinkTxtID', N'External Link Text ID', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileFranCode', N'Franchise Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileFundCode', N'Fund Code', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileFundingExtension', N'Funding Extension', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileFundingExtReason', N'Funding Extension Reason', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileFundRef', N'Fund Ref', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileID', N'Matter ID', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileLACate,ry', N'Legal Aid Cate,ry', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileLastEstimate', N'Last Estimate', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileLastEstimateDate', N'Last Estimate Date', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileManagerID', N'Manager', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileNeedExport', N'Needs Export', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileNickname', N'Nickname', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileNo', N'Matter Number', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileNotes', N'Notes', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileOffline', N'Offline', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileOriginalLimit', N'Original Limit', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'filePassword', N'Password', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'filePasswordHint', N'Password Hint', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'filePrecLibrary', N'Precedent Library', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'filePrincipleID', N'Fee Earner', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileQuoteSent', N'Quote Sent', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileRatePerUnit', N'Rate PerUnit', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileResponsibleID', N'Responsible', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileRestrictions', N'Restrictions', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileReviewDate', N'Review Date', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileRiskAssesment', N'Risk Assessment', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileScope', N'Scope', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileSMSEnabled', N'SMS Enabled', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileSource', N'Source', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileSourceContact', N'Source Contact', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileSourceUser', N'Source User', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileSPSDocWS', N'', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileSPSSite', N'SPS Site', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileStatus', N'Status', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''FILESTATUS'' and cdUICultureInfo = ''{default}'' and cdCode =  NewValue')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileStorageProvider', N'Storage Provider', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileTeam', N'Team', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileTimeActivityGroup', N'Time Activity Group', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileType', N'Type', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''FILETYPE'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileUICultureInfo', N'Culture', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileWarningPerc', N'Warning Percentage', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileWIP', N'WIP', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'fileXml', N'XML', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'SecurityOptions', N'Security Options', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'Updated', N'Updated', 0, N'')
, (N'[' + @DbName + N'].[dbo].[dbfile]', N'Updatedby', N'Updated By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
-- config schema inserts
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocActive', N'Active', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocAddressee', N'Addressee', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocDDI', N'DDI', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocDefAddSetting', N'Default Address Setting', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocdefaultaddID', N'Default Address ID', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocEmail', N'Email', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocEmployeeID', N'Employee ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocFax', N'Fax', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocHeading', N'Heading', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocID', N'Associate ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocMobile', N'Mobile', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocNotes', N'Associate Notes', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocOrder', N'Order', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocPrefContactMethod', N'Preferred Method of Contact', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocRef', N'Reference', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocSalut', N'Salutation', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocType', N'Type', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''SUBASSOC'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'assocUseDX', N'Use DX', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'contID', N'Contact ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'fileID', N'Matter ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'Updated', N'Updated', 1, N'')
, (N'[' + @DbName + N'].[config].[dbAssociates]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'brID', N'Branch', 0, N'select @VALUE = brName from dbBranch where brID = Convert(int, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clAccCode', N'Account Code', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clActiveComplaints', N'Active Complaints', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clActiveUndertakings', N'Active Undertakings', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clAddInfo', N'Additional Information', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clAutoCreated', N'Auto Created', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clAutoSource', N'Auto Source', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clAutoType', N'Auto Type', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clDefaultAddress', N'Default Address', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clDefaultContact', N'Default Contact', 0, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clextID', N'External ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clexttxtID', N'External Text ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clGroup', N'Group', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clguid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clID', N'Client ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clMarket', N'Market', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clName', N'Client Name', 0, NULL)
, (N'[' + @DbName + N'].[config].[dbClient]', N'clNeedExport', N'Need Export', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clNickname', N'Nickname', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clNo', N'Client Number', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clNotes', N'Notes', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clPassword', N'Password', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clPasswordHint', N'Password Hint', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clPreClient', N'Pre-Client', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clPreClientConvDate', N'Pre-Client Conversion Date', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clRegisterCount', N'Register Count', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSearch1', N'Search 1', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSearch2', N'Search 2', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSearch3', N'Search 3', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSearch4', N'Search 4', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSearch5', N'Search 5', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSource', N'Source', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSourceContact', N'Source Contact', 0, N'select @VALUE = contName from dbContact where contID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clSourceUser', N'Source User', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clStatus', N'Status', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clStop', N'Stop', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clStopReason', N'Stop Reason', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clStorageProvider', N'Storage Provider', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'cltypeCode', N'Type Code', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''CLTYPE'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'clUICultureInfo', N'Culture', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'feeusrID', N'Fee Earner', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbClient]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'SecurityOptions', N'Security Options', 0, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'Updated', N'Updated', 1, N'')
, (N'[' + @DbName + N'].[config].[dbClient]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contAddFilter', N'Address Filter', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contAddInfo', N'', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contAddressee', N'Addressee', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contApproved', N'Approved', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contApprRevokedOn', N'Approval Revoked On', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contDefaultAddress', N'Default Address', 0, N'select @VALUE = (addLine1 + '', '' + addLine2 + '', '' + addLine3 + '', '' + addLine4 + '', '' + addLine5 + '', '' + addPostcode) from dbAddress where addID = CONVERT(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contExtTxtID', N'External Text ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contGrade', N'Grade', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contGroup', N'Group', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contGuid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contID', N'Contact ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contIdent', N'Identity 1', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contIdent2', N'Identity 2', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contIsClient', N'Contact is Client', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contLARef', N'Legal Aid Reference', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contMarketable', N'Marketable', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contName', N'Name', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contNotes', N'Notes', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contPrecLibrary', N'Precedent Library', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contPrefContactMethod', N'Preferred Method of Contact', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contSalut', N'Salutation', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contShortName', N'Short Name', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contSource', N'Source', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contTypeCode', N'Type Code', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''CONTTYPE'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contWebsite', N'Website', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'contXMASCard', N'Xmas Card', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbContact]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'SecurityOptions', N'Security Options', 0, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'Updated', N'Updated', 1, N'')
, (N'[' + @DbName + N'].[config].[dbContact]', N'UpdatedBy', N'Updated By', 1, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbContact]', N'UserID', N'User ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'brID', N'Branch', 0, N'select @VALUE = brName from dbBranch where brID = Convert(int, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'clID', N'Client ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'Created', N'Created', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'CreatedBy', N'Created By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'DefaultAssociateID', N'Default Associate', 0, N'select @VALUE = contName from dbAssociates a inner join dbContact c on a.contID = c.contID where assocID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileAccCode', N'Account Code', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileAgreementDate', N'Agreement Date', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileAlertLevel', N'Alert Level', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileAlertMessage', N'Alert Messages', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileAllowExternal', N'Allow External', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileArchiveDate', N'Archive Date', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileArchiveRef', N'Archive Ref', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileBanding', N'Banding', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileBTD', N'BTD', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileClosed', N'Closed', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileClosedby', N'Closed By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileComplexity', N'Complexity', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileConflictCheck', N'Conflict Check', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileConflictFound', N'Conflicts Found', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileConflictNotes', N'Conflict Notes', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileCost', N'Cost', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileCreditLimit', N'Credit Limit', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'filecurISOCode', N'ISO Code', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileDepartment', N'Department', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileDesc', N'Description', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileDestroyDate', N'Destroy Date', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileEstimate', N'Estimate', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileExternalNotes', N'External Notes', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileExtLinkID', N'External Link ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileExtLinkTxtID', N'External Link Text ID', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileFranCode', N'Franchise Code', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileFundCode', N'Fund Code', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileFundingExtension', N'Funding Extension', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileFundingExtReason', N'Funding Extension Reason', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileFundRef', N'Fund Ref', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileguid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileID', N'Matter ID', 1, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileLACate,ry', N'Legal Aid Cate,ry', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileLastEstimate', N'Last Estimate', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileLastEstimateDate', N'Last Estimate Date', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileManagerID', N'Manager', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileNeedExport', N'Needs Export', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileNickname', N'Nickname', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileNo', N'Matter Number', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileNotes', N'Notes', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileOffline', N'Offline', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileOriginalLimit', N'Original Limit', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'filePassword', N'Password', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'filePasswordHint', N'Password Hint', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'filePrecLibrary', N'Precedent Library', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'filePrincipleID', N'Fee Earner', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileQuoteSent', N'Quote Sent', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileRatePerUnit', N'Rate PerUnit', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileResponsibleID', N'Responsible', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileRestrictions', N'Restrictions', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileReviewDate', N'Review Date', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileRiskAssesment', N'Risk Assessment', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileScope', N'Scope', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileSMSEnabled', N'SMS Enabled', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileSource', N'Source', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileSourceContact', N'Source Contact', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileSourceUser', N'Source User', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileSPSDocWS', N'', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileSPSSite', N'SPS Site', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileStatus', N'Status', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''FILESTATUS'' and cdUICultureInfo = ''{default}'' and cdCode =  NewValue')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileStorageProvider', N'Storage Provider', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileTeam', N'Team', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileTimeActivityGroup', N'Time Activity Group', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileType', N'Type', 0, N'select @VALUE = cdDesc from dbCodeLookup where cdType = ''FILETYPE'' and cdUICultureInfo = ''{default}'' and cdCode = Convert(nvarchar(200), NewValue)')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileUICultureInfo', N'Culture', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileWarningPerc', N'Warning Percentage', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileWIP', N'WIP', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'fileXml', N'XML', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'rowguid', N'', 1, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'SecurityOptions', N'Security Options', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'Updated', N'Updated', 0, N'')
, (N'[' + @DbName + N'].[config].[dbfile]', N'Updatedby', N'Updated By', 0, N'select @VALUE = usrFullName from dbUser where usrID = Convert(bigint, NewValue)')

INSERT [audit].[ColumnNameMapping] ([TableName], [ColumnName], [FriendlyName], [Exclude], [LinkField]) 
SELECT [TableName]
	, [ColumnName]
	, [FriendlyName]
	, [Exclude]
	, [LinkField]
FROM @Map m 
WHERE NOT EXISTS (SELECT 1 FROM [audit].[ColumnNameMapping] cm WHERE cm.TableName = m.TableName AND cm.ColumnName = m.ColumnName)
