//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace ELPLServicesLibrary
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class InterimSettlementPackResponse
    {

        private InterimSettlementPackResponseDefendantRepresentative defendantRepresentativeField;

        private InterimSettlementPackResponseInterimPayment interimPaymentField;

        private CT_A2A_DefendantLosses_Interim_ELPL[] defendantRepliesField;

        private InterimSettlementPackResponseTotal totalField;

        /// <remarks/>
        public InterimSettlementPackResponseDefendantRepresentative DefendantRepresentative
        {
            get
            {
                return this.defendantRepresentativeField;
            }
            set
            {
                this.defendantRepresentativeField = value;
            }
        }

        /// <remarks/>
        public InterimSettlementPackResponseInterimPayment InterimPayment
        {
            get
            {
                return this.interimPaymentField;
            }
            set
            {
                this.interimPaymentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("DefendantResponse", IsNullable = false)]
        public CT_A2A_DefendantLosses_Interim_ELPL[] DefendantReplies
        {
            get
            {
                return this.defendantRepliesField;
            }
            set
            {
                this.defendantRepliesField = value;
            }
        }

        /// <remarks/>
        public InterimSettlementPackResponseTotal Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InterimSettlementPackResponseDefendantRepresentative
    {

        private CT_A2A_CompanyDetails defendantsInsurerField;

        /// <remarks/>
        public CT_A2A_CompanyDetails DefendantsInsurer
        {
            get
            {
                return this.defendantsInsurerField;
            }
            set
            {
                this.defendantsInsurerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_A2A_DefendantLosses_Interim_ELPL
    {

        private C18_LossType_A2A_R3 lossTypeField;

        private C00_YNFlag isGrossAmountAgreedField;

        private string commentsField;

        private decimal grossValueOfferedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public C18_LossType_A2A_R3 LossType
        {
            get
            {
                return this.lossTypeField;
            }
            set
            {
                this.lossTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public C00_YNFlag IsGrossAmountAgreed
        {
            get
            {
                return this.isGrossAmountAgreedField;
            }
            set
            {
                this.isGrossAmountAgreedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal GrossValueOffered
        {
            get
            {
                return this.grossValueOfferedField;
            }
            set
            {
                this.grossValueOfferedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    public enum C18_LossType_A2A_R3
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CT_A2A_DefendantResponseToInterimPaymentRequest
    {

        private string additionalCommentsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string AdditionalComments
        {
            get
            {
                return this.additionalCommentsField;
            }
            set
            {
                this.additionalCommentsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InterimSettlementPackResponseInterimPayment
    {

        private CT_A2A_DefendantResponseToInterimPaymentRequest defendantResponsesToInterimPaymentRequestField;

        /// <remarks/>
        public CT_A2A_DefendantResponseToInterimPaymentRequest DefendantResponsesToInterimPaymentRequest
        {
            get
            {
                return this.defendantResponsesToInterimPaymentRequestField;
            }
            set
            {
                this.defendantResponsesToInterimPaymentRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InterimSettlementPackResponseTotal
    {

        private InterimSettlementPackResponseTotalLossesTotal lossesTotalField;

        /// <remarks/>
        public InterimSettlementPackResponseTotalLossesTotal LossesTotal
        {
            get
            {
                return this.lossesTotalField;
            }
            set
            {
                this.lossesTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InterimSettlementPackResponseTotalLossesTotal
    {

        private decimal cRUDeductionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal CRUDeductions
        {
            get
            {
                return this.cRUDeductionsField;
            }
            set
            {
                this.cRUDeductionsField = value;
            }
        }
    }
}