Print 'Starting NewInstallScripts\Default_ContactType.sql'


-- add default Contact types
IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = '3RDPARTY' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( '3RDPARTY' , 38 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" tabtype="Enquiry" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="868940124" source="SCRCONINDINFO" tabtype="Enquiry" glyph="30" group="NAVGRPCONTINFO" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" userRoles="" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTINDIV" /><ExtendedData code="EXTCONTSEC" /></ExtendedDataList><Settings GeneralType="Individual" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'BARRISTER' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'BARRISTER' , 21 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" tabtype="Enquiry" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="868940124" source="SCRCONINDINFO" tabtype="Enquiry" glyph="30" group="NAVGRPCONTINFO" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTINDIV" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Individual" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'CLIENT' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'CLIENT' , 1 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /></ExtendedDataList><Settings /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'COURT' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'COURT' , 33 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'EAGENT' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'EAGENT' , 22 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP2A" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'EXPERT' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'EXPERT' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="868940124" source="SCRCONINDINFO" tabtype="Enquiry" glyph="30" group="NAVGRPCONTINFO" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTINDIV" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'FBROKER' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'FBROKER' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" GeneralType="Company" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'FINANCIAL' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'FINANCIAL' , 27 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'INDIVIDUAL' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'INDIVIDUAL' , 36 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="868940124" glyph="30" source="SCRCONINDINFO" tabtype="Enquiry" group="NAVGRPCONTINFO" /><Tab lookup="-976011395" glyph="59" source="SCRCONINDAUDIT" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTINDIV" /><ExtendedData code="EXTCONTSEC" /></ExtendedDataList><Settings /><defaultTemplates /></Config>' , 1 , 1 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'INSBROKER' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'INSBROKER' , 18 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" GeneralType="Company" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'INSCO' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'INSCO' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'INSCOMASS' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'INSCOMASS' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'IREV' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'IREV' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'LANDREG' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'LANDREG' , 17 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" GeneralType="Company" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'LBROKER' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'LBROKER' , 17 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'LEGOMORG' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'LEGOMORG' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'LOCALAUTH' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'LOCALAUTH' , 20 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'LOCAUTAGY' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'LOCAUTAGY' , 18 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'ORGANISATION' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'ORGANISATION' , 44 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTCOMP" /><ExtendedData code="EXTCONTSEC" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 1 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'REMOTE' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'REMOTE' , 22 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Individual" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'SHERIFF' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'SHERIFF' , 17 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'SOLICITOR' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'SOLICITOR' , 26 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP2A" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'SUBCLIENT' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'SUBCLIENT' , 14 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="868940124" source="SCRCONINDINFO" tabtype="Enquiry" glyph="30" group="NAVGRPCONTINFO" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTINDIV" /></ExtendedDataList><Settings /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'TEMPLATE' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'TEMPLATE' , 10 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="IsPackageInstalled(&quot;REMOTEACCOUNT&quot;)" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTCOMP" /><ExtendedData code="EXTCONTINDIV" /><ExtendedData code="EXTCONTSEC" /></ExtendedDataList><Settings /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'TMPCORP' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'TMPCORP' , 13 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings GeneralType="Company" wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'TMPINDIV' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'TMPINDIV' , 16 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="868940124" source="SCRCONINDINFO" tabtype="Enquiry" glyph="52" /><Tab lookup="-976011395" glyph="40" source="EXTCONTSEC" tabtype="ExtData" conditional="IsPackageInstalled(&quot;SECURITY&quot;)" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTCOMP" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTINDIV" /></ExtendedDataList><Settings wizard="" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO

IF NOT EXISTS ( SELECT typeCode FROM dbo.dbContactType WHERE typeCode = 'WATAUTH' )
BEGIN
	INSERT dbo.dbContactType ( typeCode , typeVersion , typeXML , typeGlyph , typeActive )
	VALUES ( 'WATAUTH' , 19 , '<Config><Dialog><Form lookup="CONTCAPTION" /><Buttons /><Tabs><Tab lookup="CONTDETAILS" glyph="23" source="SCRCONMAIN" group="NAVGRPCONTINFO" /><Tab lookup="SCHCONASSOC" source="SCHCONASSOC" tabtype="List" glyph="25" group="NAVGRPCONTINFO" /><Tab lookup="-1433682802" source="SCRCONCORPINFO" tabtype="Enquiry" glyph="56" /><Tab lookup="-976011395" source="SCRCONINDAUDIT" tabtype="Enquiry" glyph="59" conditional="Ispackageinstalled(&quot;Security&quot;)" group="NAVGRPCONTINFO" /><Tab lookup="-1390301088" glyph="31" source="SCRCONREMACCINF" tabtype="Enquiry" conditional="Ispackageinstalled(&quot;RemoteAccount&quot;)" /><Tab lookup="CLDOCUMENTS" glyph="0" source="SCHDOCCNTTRAN" tabtype="Addin" conditional="IsPackageInstalled(&quot;DMS&quot;)" group="NAVGRPDOCUMENTS" /><Tab lookup="-1609146310" glyph="19" source="SCHCONPERFRATE" /><Tab lookup="-171432738" glyph="24" source="SCRCONNOTES" tabtype="Enquiry" group="NAVGRPCONTINFO" /></Tabs><Panels width="180" brightness="60" backcolor="Silver"><Panel lookup="CONTDETAILS" height="100" expanded="True" glyph="Grey" property="DefaultAddress" panelType="Property" /></Panels></Dialog><ExtendedDataList><ExtendedData code="EXTREMACCCONT" /><ExtendedData code="EXTCONTSEC" /><ExtendedData code="EXTCONTCOMP" /></ExtendedDataList><Settings wizard="SCRCONNEWCORP" /><defaultTemplates /></Config>' , 1 , 0 )
END
GO
