//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fwbs.Oms.Office.Outlook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fwbs.Oms.Office.Outlook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaches a chosen recipient to the blind carbon copy list of recipients..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Insert_AttachBCC {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Insert_AttachBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaches a chosen recipient to the carbon copy list of recipients..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Insert_AttachCC {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Insert_AttachCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaches another document within the system as an attachment to the current mail item..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Insert_AttachDoc {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Insert_AttachDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the %PRECEDENT% library..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Insert_PrecedentLibrary {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Insert_PrecedentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies to the current %ASSOCIATE% in the form of an email using the default mail %PRECEDENT%..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Reply_Mail {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Reply_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies to the %ASSOCIATE% in the form of a letter using the default configured letterhead..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Reply_ToAssociate {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Reply_ToAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replies to the %CLIENT% in the form of a letter using the default configured letterhead..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Reply_ToClient {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Reply_ToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows checking and authorisation of the attached document..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Tools_Authorise {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Tools_Authorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaches the document variables from the current item..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Tools_DetachVars {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Tools_DetachVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files the current mail item under the correct local folder..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Tools_FileIt {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Tools_FileIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves or resaves the current item under the attached %CLIENT% / %FILE%..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Tools_Save {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Tools_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current mail item and then sends it straight away afterwards..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Tools_SaveAndSend {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Tools_SaveAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the current item against a different %CLIENT% / %FILE%..
        /// </summary>
        internal static string SuperTip_TabOMSDocument_Tools_SaveAs {
            get {
                return ResourceManager.GetString("SuperTip_TabOMSDocument_Tools_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string TabHome_Connect_Create_AddAppointment {
            get {
                return ResourceManager.GetString("TabHome_Connect_Create_AddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string TabHome_Connect_Create_AddTask {
            get {
                return ResourceManager.GetString("TabHome_Connect_Create_AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email To %ASSOCIATE%.
        /// </summary>
        internal static string TabHome_Connect_Create_AssocEmail {
            get {
                return ResourceManager.GetString("TabHome_Connect_Create_AssocEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter to %ASSOCIATE%.
        /// </summary>
        internal static string TabHome_Connect_Create_AssocLetter {
            get {
                return ResourceManager.GetString("TabHome_Connect_Create_AssocLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email To %CLIENT%.
        /// </summary>
        internal static string TabHome_Connect_Create_ClientEmail {
            get {
                return ResourceManager.GetString("TabHome_Connect_Create_ClientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter to %CLIENT%.
        /// </summary>
        internal static string TabHome_Connect_Create_ClientLetter {
            get {
                return ResourceManager.GetString("TabHome_Connect_Create_ClientLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Save.
        /// </summary>
        internal static string TabHome_Connect_SaveButtonMenu_ManualSave {
            get {
                return ResourceManager.GetString("TabHome_Connect_SaveButtonMenu_ManualSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Email.
        /// </summary>
        internal static string TabHome_Connect_SaveButtonsMenu_FileIt {
            get {
                return ResourceManager.GetString("TabHome_Connect_SaveButtonsMenu_FileIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Document.
        /// </summary>
        internal static string TabMail_Connect_View_OpenDocuments {
            get {
                return ResourceManager.GetString("TabMail_Connect_View_OpenDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add BCC Recipient.
        /// </summary>
        internal static string TabOMSDocument_Insert_AttachBCC {
            get {
                return ResourceManager.GetString("TabOMSDocument_Insert_AttachBCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add CC Recipient.
        /// </summary>
        internal static string TabOMSDocument_Insert_AttachCC {
            get {
                return ResourceManager.GetString("TabOMSDocument_Insert_AttachCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Document.
        /// </summary>
        internal static string TabOMSDocument_Insert_AttachDoc {
            get {
                return ResourceManager.GetString("TabOMSDocument_Insert_AttachDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %PRECEDENT% Library.
        /// </summary>
        internal static string TabOMSDocument_Insert_PrecedentLibrary {
            get {
                return ResourceManager.GetString("TabOMSDocument_Insert_PrecedentLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        internal static string TabOMSDocument_Reply {
            get {
                return ResourceManager.GetString("TabOMSDocument_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email to %ASSOCIATE%.
        /// </summary>
        internal static string TabOMSDocument_Reply_Mail {
            get {
                return ResourceManager.GetString("TabOMSDocument_Reply_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter to %ASSOCIATE%.
        /// </summary>
        internal static string TabOMSDocument_Reply_ToAssociate {
            get {
                return ResourceManager.GetString("TabOMSDocument_Reply_ToAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter to %CLIENT%.
        /// </summary>
        internal static string TabOMSDocument_Reply_ToClient {
            get {
                return ResourceManager.GetString("TabOMSDocument_Reply_ToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Document.
        /// </summary>
        internal static string TabOMSDocument_Tools_Authorise {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_Authorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorise.
        /// </summary>
        internal static string TabOMSDocument_Tools_ConfAuthorise {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_ConfAuthorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        internal static string TabOMSDocument_Tools_DetachVars {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_DetachVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Email.
        /// </summary>
        internal static string TabOMSDocument_Tools_FileIt {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_FileIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string TabOMSDocument_Tools_RefAuthorise {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_RefAuthorise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TabOMSDocument_Tools_Save {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Send.
        /// </summary>
        internal static string TabOMSDocument_Tools_SaveAndSend {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_SaveAndSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string TabOMSDocument_Tools_SaveAs {
            get {
                return ResourceManager.GetString("TabOMSDocument_Tools_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Email.
        /// </summary>
        internal static string TabReadMessage_OMS_FileIt {
            get {
                return ResourceManager.GetString("TabReadMessage_OMS_FileIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;body{overflow: hidden}&lt;/style&gt;
        ///  &lt;/head&gt;
        ///  &lt;body rightmargin = &apos;0&apos; leftmargin =&apos;0&apos; topmargin =&apos;0&apos; bottommargin = &apos;0&apos;&gt;
        ///     &lt;object classid=&apos;clsid:B9C8117E-C13B-4ff5-BF75-03BE75EB7FE5&apos; ID=&apos;FolderHomepageCtl&apos; VIEWASTEXT width=&apos;100%&apos; height=&apos;100%&apos;/&gt;
        ///  &lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string WebViewHtmFileContent {
            get {
                return ResourceManager.GetString("WebViewHtmFileContent", resourceCulture);
            }
        }
    }
}
