CREATE PROCEDURE [dbo].[fdsprRaPIdSearchDocs] 
(
	@CURRENTUSER INT = NULL 
	, @UI UUICULTUREINFO = '{DEFAULT}'
	, @DOCTYPE UCODELOOKUP = NULL 
	, @INCLUDEDELETED BIT = 0
	, @UPLOADEDDOWNLOADED NVARCHAR(15) = NULL
	, @FILEID BIGINT = 0
	, @CREATEDFROM DATETIME = NULL
	, @CREATEDTO DATETIME = NULL
	, @MAX_RECORDS INT = 50 
)  
AS


IF @CURRENTUSER IS NULL
	SET @CURRENTUSER = DBO.GETCURRENTUSER()


IF @FILEID IS NULL SET @FILEID = 0


DECLARE @SELECT NVARCHAR(2300)
DECLARE @TOP NVARCHAR(10)
DECLARE @WHERE NVARCHAR(1600)


IF @MAX_RECORDS > 0
	SET @TOP = N'TOP ' + CONVERT(NVARCHAR, @MAX_RECORDS)
ELSE
	SET @TOP = N''


SET @SELECT = 
	N'SELECT  ' + @TOP + '
		DBO.DBUSER.USRINITS AS CRBYINITS, 
		DBO.DBUSER.USRFULLNAME AS CRBYFULLNAME, 
		DBUSER_1.USRINITS AS UPDBYINITS, 
		DBUSER_1.USRFULLNAME AS UPDBYFULLNAME, 
		DBUSER_2.USRINITS AS AUTHBYINITS, 
		DBUSER_2.USRFULLNAME AS AUTHBYFULLNAME, 
		DBO.GETCODELOOKUPDESC(''DOCTYPE'', DBO.DBDOCUMENT.DOCTYPE, @UI) AS DOCTYPEDESC, 
		DBO.DBDOCUMENT.DOCID, 
		DBO.DBDOCUMENT.CREATED AS CRFIELD,
		DBO.DBDOCUMENT.DOCDESC, 
		DBO.DBDOCUMENT.DOCTYPE, 
		COALESCE(DBO.DBDOCUMENT.DOCAUTHORED, DBO.DBDOCUMENT.CREATED) AS CREATED, 
		DBO.DBDOCUMENT.UPDATED, 
		DBO.DBDOCUMENT.DOCDIRECTION, 
		DBO.DBDOCUMENT.DOCEXTENSION,
		DBO.DBCLIENT.CLNO, 
		DBO.DBFILE.FILENO, 
		DBO.DBDOCUMENT.DOCSTYLEDESC, 
		DBO.GETCODELOOKUPDESC(''WALLET'' , DBO.DBDOCUMENT.DOCWALLET , @UI) AS DOCWALLET,
		CONT.CONTNAME,
		CONVERT(NVARCHAR(20),DBO.DBDOCUMENT.DOCID) AS DOCIDTXT,
		DBO.DBDOCUMENT.DOCFILENAME AS DOCTOKEN,
		DBO.DBDOCUMENT.DOCCHECKEDOUT,
		DBO.DBDOCUMENT.DOCCHECKEDOUTBY,
		DBO.DBDOCUMENT.DOCCHECKEDOUTLOCATION,
		V.VERLABEL
		, CONVERT(BIT, CASE 
			WHEN RD.RPDDOCDATTACHMENTGUID IS NOT NULL THEN 1
			ELSE 0
		  END) AS [DOWNLOADED]
		, CONVERT(BIT, CASE 
			WHEN RU.RPDDOCRETURNGUID IS NOT NULL THEN 1
			ELSE 0
		  END) AS [UPLOADED]	
		, RU.RPDDOCDESCRIPTION AS [UPLOADED DESCRIPTION]
		, RD.RPDDOCDDESCRIPTION AS [DOWNLOADED DESCRIPTION]
FROM         
	DBO.DBUSER 
RIGHT OUTER JOIN
					DBO.DBDOCUMENT 
LEFT OUTER JOIN
					DBO.DBFILE ON DBO.DBDOCUMENT.FILEID = DBO.DBFILE.FILEID 
LEFT OUTER JOIN
					DBO.DBCLIENT ON DBO.DBDOCUMENT.CLID = DBO.DBCLIENT.CLID 
LEFT OUTER JOIN
					DBO.DBUSER DBUSER_1 ON DBO.DBDOCUMENT.UPDATEDBY = DBUSER_1.USRID ON DBO.DBUSER.USRID = DBO.DBDOCUMENT.CREATEDBY
LEFT OUTER JOIN
					DBO.DBUSER DBUSER_2 ON DBO.DBDOCUMENT.DOCAUTHOREDBY = DBUSER_2.USRID
INNER JOIN
					DBASSOCIATES ASS ON ASS.ASSOCID = DBDOCUMENT.ASSOCID
INNER JOIN 
					DBCONTACT CONT ON CONT.CONTID = ASS.CONTID
LEFT JOIN 
					DBO.DBAPPLICATION A ON A.APPID = DBDOCUMENT.DOCAPPID
LEFT JOIN
					DBO.DBDOCUMENTVERSION V ON V.VERID = DBO.DBDOCUMENT.DOCCURRENTVERSION
LEFT JOIN
	FDRAPIDDOCUMENTDOWNLOADS RD ON DBO.DBDOCUMENT.DOCID = RD.DOCID
LEFT JOIN
	FDRAPIDDOCUMENTUPLOADS RU ON DBO.DBDOCUMENT.DOCID = RU.DOCID
'

SET @WHERE = N' WHERE DBO.DBDOCUMENT.FILEID = @FILEID '


-- DOCUMENT TYPE
IF NOT @DOCTYPE IS NULL
	SET @WHERE = @WHERE + N' AND DOCTYPE = @DOCTYPE'


-- DATE CREATED RANGE
IF(@CREATEDFROM IS NOT NULL AND @CREATEDTO IS NOT NULL)
BEGIN
	BEGIN
		SET @WHERE = @WHERE + ' AND DBO.DBDOCUMENT.CREATED >= @CREATEDFROM AND DBO.DBDOCUMENT.CREATED < @CREATEDTO '
	END
END

IF(@CREATEDFROM IS NOT NULL AND @CREATEDTO IS NULL)
BEGIN
	BEGIN
		SET @WHERE = @WHERE + ' AND DBO.DBDOCUMENT.CREATED >= @CREATEDFROM '
	END
END

IF(@CREATEDFROM IS NULL AND @CREATEDTO IS NOT NULL)
BEGIN
	BEGIN
		SET @WHERE = @WHERE + ' AND DBO.DBDOCUMENT.CREATED < @CREATEDTO '
	END
END


-- DOCUMENT UPLOADED/DOWNLOADED
IF (@UPLOADEDDOWNLOADED = 'RTADOWNLOADED')
BEGIN
	SET @WHERE = @WHERE + ' AND RD.RPDDOCDDOWNLOADED IS NOT NULL '
END	

IF (@UPLOADEDDOWNLOADED = 'RTAUPLOADED')
BEGIN
	SET @WHERE = @WHERE + ' AND RU.RPDDOCUPLOADED IS NOT NULL '
END	


-- INCLUDE DELETED DOCUMENTS
IF EXISTS ( SELECT C.[NAME] FROM SYSCOLUMNS C JOIN SYSOBJECTS O ON C.[ID] = O.[ID] WHERE O.[NAME] = 'DBDOCUMENT'  AND C.[NAME] = 'DOCDELETED' )
BEGIN
	IF @INCLUDEDELETED = 0
	BEGIN
		SET @WHERE = @WHERE + N' AND COALESCE(DOCDELETED,0) = 0'
	END
END


DECLARE @SQL NVARCHAR(4000)
SET @SQL = @SELECT + @WHERE + ' ORDER BY DBO.DBDOCUMENT.UPDATED DESC' 
PRINT @SQL


EXEC SP_EXECUTESQL @SQL,  N'
	
	@CURRENTUSER INT 
	, @UI UUICULTUREINFO
	, @DOCTYPE UCODELOOKUP
	, @INCLUDEDELETED BIT
	, @UPLOADEDDOWNLOADED NVARCHAR(15)
	, @FILEID BIGINT
	, @CREATEDFROM DATETIME
	, @CREATEDTO DATETIME
	, @MAX_RECORDS INT', 
	
	@CURRENTUSER
	, @UI
	, @DOCTYPE
	, @INCLUDEDELETED
	, @UPLOADEDDOWNLOADED
	, @FILEID
	, @CREATEDFROM
	, @CREATEDTO
	, @MAX_RECORDS
