
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archWillDate'
	, @COLUMNDESC = 'DATETIME NULL'

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archPOADate'
	, @COLUMNDESC = 'DATETIME NULL'

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archStorageDate'
	, @COLUMNDESC = 'DATETIME NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archCodicil1'
	, @COLUMNDESC = 'DATETIME NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archCodicil2'
	, @COLUMNDESC = 'DATETIME NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archCodicil3'
	, @COLUMNDESC = 'DATETIME NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archCodicil4'
	, @COLUMNDESC = 'DATETIME NULL'

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archGeneralType'
	, @COLUMNDESC = 'dbo.uCodeLookup NULL'

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archExtLinkID'
	, @COLUMNDESC = 'NVARCHAR ( 20 ) NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archRefOther'
	, @COLUMNDESC = 'NVARCHAR ( 20 ) NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archStorageLocationText'
	, @COLUMNDESC = 'NVARCHAR ( 50 ) NULL'
	
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archEmbeddedFile'
	, @COLUMNDESC = 'NVARCHAR(MAX) NULL'

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbArchive' 
	, @COLUMNNAME = 'archDocRef'
	, @COLUMNDESC = 'NVARCHAR ( 15 ) NULL'

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbTracking' 
	, @COLUMNNAME = 'trackNotes'
	, @COLUMNDESC = 'NVARCHAR ( 200 ) NULL'
	
--CHANGES

EXEC FWBSCOLUMNCHANGES
	@SPTABLE = 'dbArchive'
	, @SPCOLUMN = 'archNote'
	, @SPDEFINITION = 'NVARCHAR ( 1000 ) NULL'
	

IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_dbArchive_Created]') AND type = 'D')
BEGIN
	ALTER TABLE [dbo].[dbArchive] ADD  CONSTRAINT [DF_dbArchive_Created]  DEFAULT (getutcdate()) FOR [Created]
END
GO

UPDATE dbo.dbArchive
SET	ARCHSTORAGEDATE = CREATED
WHERE ARCHSTORAGEDATE IS NULL AND CREATED IS NOT NULL

GO
UPDATE dbo.dbCommandCentreType
SET typeXML = REPLACE(CAST(typeXML AS NVARCHAR(MAX)), '"SCHCLIARCHALL"', '"SCHCOMARCHALL"')
WHERE typeCode = 'STANDARD'
	AND  CHARINDEX('"SCHCLIARCHALL"', typeXML) IS NOT NULL

GO