/*
	HELPER SCRIPT
	=============
	JOIN MATTERSPHERE MATTER TO 3E MATTER TO SEE IF ANY 
	DECLINED 3E MATTERS (POST CONFLICT SEARCH) ARE FLAGGED ARE NOT DEAD IN 
	MATTERSPHERE.  ASSUME CODES AS PER STOCK, CODES WILL PROBABLY CHANGE ON SITE
	ASSUMES RUNNING FROM 3E DATABASE.  CHANGE LINK TO MATTERSPHERE DATABASE.  
	CONSIDER ENVIRONMENT AND RUN AS OVER NIGHT SQL UPDATE?
*/

DECLARE @3E_CODE NVARCHAR ( 16 )
DECLARE @MS_CODE NVARCHAR ( 15 )

SET @3E_CODE = 'Declined'
SET @MS_CODE = 'DEAD'

UPDATE 
	DBFILE
SET
	FILESTATUS = @MS_CODE
	, FILENEEDEXPORT = FILENEEDEXPORT --PREVENT UPDATE TRIGGER
FROM
	MATTER
INNER JOIN 
	MCELITE.DBO.DBFILE ON MCELITE.DBO.DBFILE.FILEEXTLINKID = MATTER.MATTINDEX
WHERE
	MATTER.MATTSTATUS = @3E_CODE AND
	MCELITE.DBO.DBFILE.FILESTATUS != @MS_CODE
	