//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fwbs.WinFinder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fwbs.WinFinder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window is not a local window..
        /// </summary>
        internal static string ExceptionNotLocalWindow {
            get {
                return ResourceManager.GetString("ExceptionNotLocalWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not allow recursion through all windows.
        /// </summary>
        internal static string ExceptionRecursiveWindowsFromRoot {
            get {
                return ResourceManager.GetString("ExceptionRecursiveWindowsFromRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Area.
        /// </summary>
        internal static string WindowTextNotificationArea {
            get {
                return ResourceManager.GetString("WindowTextNotificationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Launch.
        /// </summary>
        internal static string WindowTextQuickLaunch {
            get {
                return ResourceManager.GetString("WindowTextQuickLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Applications.
        /// </summary>
        internal static string WindowTextRunningApps {
            get {
                return ResourceManager.GetString("WindowTextRunningApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Control Area.
        /// </summary>
        internal static string WindowTextSystemControlArea {
            get {
                return ResourceManager.GetString("WindowTextSystemControlArea", resourceCulture);
            }
        }
    }
}
