//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace FWBS.enterpriseMatterLoadService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MatterLoadServiceSoap", Namespace="http://www.elite.com/openapi/matterload")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NVSerializable))]
    public partial class MatterLoadService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private user userValueField;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultiPayorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MatterLoadService() {
            this.Url = global::FWBS.Properties.Settings.Default.OMSExportENT_enterpriseMatterLoadService_MatterLoadService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public user userValue {
            get {
                return this.userValueField;
            }
            set {
                this.userValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultiPayorCompletedEventHandler CreateMultiPayorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("userValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.elite.com/openapi/matterload/Create", RequestNamespace="http://www.elite.com/openapi/matterload", ResponseNamespace="http://www.elite.com/openapi/matterload", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Create([System.Xml.Serialization.XmlElementAttribute("matter")] MatterLoad[] matter, string startDate) {
            object[] results = this.Invoke("Create", new object[] {
                        matter,
                        startDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(MatterLoad[] matter, string startDate) {
            this.CreateAsync(matter, startDate, null);
        }
        
        /// <remarks/>
        public void CreateAsync(MatterLoad[] matter, string startDate, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        matter,
                        startDate}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("userValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.elite.com/openapi/matterload/CreateMultiPayor", RequestNamespace="http://www.elite.com/openapi/matterload", ResponseNamespace="http://www.elite.com/openapi/matterload", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateMultiPayor([System.Xml.Serialization.XmlElementAttribute("matter")] MatterMultiLoad[] matter, string runOption) {
            object[] results = this.Invoke("CreateMultiPayor", new object[] {
                        matter,
                        runOption});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultiPayorAsync(MatterMultiLoad[] matter, string runOption) {
            this.CreateMultiPayorAsync(matter, runOption, null);
        }
        
        /// <remarks/>
        public void CreateMultiPayorAsync(MatterMultiLoad[] matter, string runOption, object userState) {
            if ((this.CreateMultiPayorOperationCompleted == null)) {
                this.CreateMultiPayorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultiPayorOperationCompleted);
            }
            this.InvokeAsync("CreateMultiPayor", new object[] {
                        matter,
                        runOption}, this.CreateMultiPayorOperationCompleted, userState);
        }
        
        private void OnCreateMultiPayorOperationCompleted(object arg) {
            if ((this.CreateMultiPayorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultiPayorCompleted(this, new CreateMultiPayorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.elite.com/openapi/matterload", IsNullable=false)]
    public partial class user : System.Web.Services.Protocols.SoapHeader {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public partial class MatterMultiPayorDetail {
        
        private string mplcodeField;
        
        private string mpclnumField;
        
        private decimal mppercentField;
        
        private string mpaddress1Field;
        
        private string mpaddress2Field;
        
        private string mpaddress3Field;
        
        private string mpaddress4Field;
        
        private string mpaddress5Field;
        
        private string mpaddress6Field;
        
        /// <remarks/>
        public string mplcode {
            get {
                return this.mplcodeField;
            }
            set {
                this.mplcodeField = value;
            }
        }
        
        /// <remarks/>
        public string mpclnum {
            get {
                return this.mpclnumField;
            }
            set {
                this.mpclnumField = value;
            }
        }
        
        /// <remarks/>
        public decimal mppercent {
            get {
                return this.mppercentField;
            }
            set {
                this.mppercentField = value;
            }
        }
        
        /// <remarks/>
        public string mpaddress1 {
            get {
                return this.mpaddress1Field;
            }
            set {
                this.mpaddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string mpaddress2 {
            get {
                return this.mpaddress2Field;
            }
            set {
                this.mpaddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string mpaddress3 {
            get {
                return this.mpaddress3Field;
            }
            set {
                this.mpaddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string mpaddress4 {
            get {
                return this.mpaddress4Field;
            }
            set {
                this.mpaddress4Field = value;
            }
        }
        
        /// <remarks/>
        public string mpaddress5 {
            get {
                return this.mpaddress5Field;
            }
            set {
                this.mpaddress5Field = value;
            }
        }
        
        /// <remarks/>
        public string mpaddress6 {
            get {
                return this.mpaddress6Field;
            }
            set {
                this.mpaddress6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public partial class MatterMultiPayor {
        
        private System.DateTime mmdate1Field;
        
        private MatterMultiPayorDetail[] mattmultipaydField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime mmdate1 {
            get {
                return this.mmdate1Field;
            }
            set {
                this.mmdate1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mattmultipayd")]
        public MatterMultiPayorDetail[] mattmultipayd {
            get {
                return this.mattmultipaydField;
            }
            set {
                this.mattmultipaydField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public partial class MatterAddress {
        
        private string matypeField;
        
        private string maddress1Field;
        
        private string maddress2Field;
        
        private string maddress3Field;
        
        private string maddress4Field;
        
        private string maddress5Field;
        
        private string maddress6Field;
        
        /// <remarks/>
        public string matype {
            get {
                return this.matypeField;
            }
            set {
                this.matypeField = value;
            }
        }
        
        /// <remarks/>
        public string maddress1 {
            get {
                return this.maddress1Field;
            }
            set {
                this.maddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string maddress2 {
            get {
                return this.maddress2Field;
            }
            set {
                this.maddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string maddress3 {
            get {
                return this.maddress3Field;
            }
            set {
                this.maddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string maddress4 {
            get {
                return this.maddress4Field;
            }
            set {
                this.maddress4Field = value;
            }
        }
        
        /// <remarks/>
        public string maddress5 {
            get {
                return this.maddress5Field;
            }
            set {
                this.maddress5Field = value;
            }
        }
        
        /// <remarks/>
        public string maddress6 {
            get {
                return this.maddress6Field;
            }
            set {
                this.maddress6Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public partial class MatterMultiLoad {
        
        private string mmatterField;
        
        private MatterAddress[] mattaddField;
        
        private MatterMultiPayor mattmultipayField;
        
        /// <remarks/>
        public string mmatter {
            get {
                return this.mmatterField;
            }
            set {
                this.mmatterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mattadd")]
        public MatterAddress[] mattadd {
            get {
                return this.mattaddField;
            }
            set {
                this.mattaddField = value;
            }
        }
        
        /// <remarks/>
        public MatterMultiPayor mattmultipay {
            get {
                return this.mattmultipayField;
            }
            set {
                this.mattmultipayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Udf))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MatterLoad))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public abstract partial class NVSerializable {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public partial class Udf : NVSerializable {
        
        private string labelField;
        
        private string valField;
        
        /// <remarks/>
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public string val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.elite.com/openapi/matterload")]
    public partial class MatterLoad : NVSerializable {
        
        private string mMATTERField;
        
        private string mNAMEField;
        
        private string mODELField;
        
        private string mRTCODEField;
        
        private string mDEPTField;
        
        private string mPRACField;
        
        private string mLOCField;
        
        private string mOPENDTField;
        
        private string mBILLATYField;
        
        private string mSUPATYField;
        
        private string mORGATYField;
        
        private string mHOLDDTField;
        
        private string mCONTACTField;
        
        private string mDESC1Field;
        
        private string mDESC2Field;
        
        private string mDESC3Field;
        
        private string mINSTR1Field;
        
        private string mINSTR2Field;
        
        private string mCLIENTField;
        
        private string mADDR1Field;
        
        private string mADDR2Field;
        
        private string mADDR3Field;
        
        private string mADDR4Field;
        
        private string mADDR5Field;
        
        private string mADDR6Field;
        
        private string mPHONEField;
        
        private string mTMINField;
        
        private string mCMINField;
        
        private string mTOTMINField;
        
        private string mFFREQField;
        
        private string mCFREQField;
        
        private string mTMPLTField;
        
        private string mTFORMATField;
        
        private string mCFORMATField;
        
        private string mTMARKField;
        
        private string mTMRKLEDField;
        
        private string mCMARKField;
        
        private string mCMRKLEDField;
        
        private string mINTRSTField;
        
        private string mINTDAYSField;
        
        private string mINTLEDField;
        
        private string mFFEEField;
        
        private string mFCOSTField;
        
        private string mRATEDField;
        
        private string mREFERField;
        
        private string mCHOLDDTField;
        
        private string mFTMPLTField;
        
        private string mFOLLOW1Field;
        
        private string mFOLLOW2Field;
        
        private string mFOLLOW3Field;
        
        private string mFOLLOW4Field;
        
        private string mTRACCTField;
        
        private string mCURRENCYField;
        
        private string mMAXFEEField;
        
        private string mPHPREFIXField;
        
        private string mMASTERField;
        
        private string mCOPIESField;
        
        private string mARRANGEField;
        
        private string mTIMEUNITField;
        
        private string fIELD1Field;
        
        private string fIELD2Field;
        
        private string fIELD3Field;
        
        private string fIELD4Field;
        
        private string fIELD5Field;
        
        private string fIELD6Field;
        
        private string fIELD7Field;
        
        private string fIELD8Field;
        
        private string fIELD9Field;
        
        private string fIELD10Field;
        
        private string fIELD11Field;
        
        private string mNONBILLField;
        
        private string mNPOSTFField;
        
        private string mNBCOSTField;
        
        private string mN1PR260Field;
        
        private string mN1PR270Field;
        
        private string mN1PR280Field;
        
        private string mN1PR290Field;
        
        private string mN1DP260Field;
        
        private string mN1DP270Field;
        
        private string mN1DP280Field;
        
        private string mN1DP290Field;
        
        private string mN2PR260Field;
        
        private string mN2PR270Field;
        
        private string mN2PR280Field;
        
        private string mN2PR290Field;
        
        private string mN2DP260Field;
        
        private string mN2DP270Field;
        
        private string mN2DP280Field;
        
        private string mN2DP290Field;
        
        private string mN1ACU260Field;
        
        private string mN1ACU270Field;
        
        private string mN1ACU280Field;
        
        private string mN1ACU290Field;
        
        private string mN2ACU260Field;
        
        private string mN2ACU270Field;
        
        private string mN2ACU280Field;
        
        private string mN2ACU290Field;
        
        private string mSTATUSField;
        
        private string mPROTEMField;
        
        private string mJNUMField;
        
        private string mFAXField;
        
        private string mCLOSEDTField;
        
        private string mRELATEDField;
        
        private string mNARRATIVEField;
        
        private string mIOBILLINGField;
        
        private string mLANGField;
        
        private string mTAXCField;
        
        private string mTAXTField;
        
        private string mUNITField;
        
        private string mFIXCAPField;
        
        private string mRATEField;
        
        private string mDISCOUNTGRPField;
        
        private string mGLOBALField;
        
        private Udf[] udfField;
        
        /// <remarks/>
        public string MMATTER {
            get {
                return this.mMATTERField;
            }
            set {
                this.mMATTERField = value;
            }
        }
        
        /// <remarks/>
        public string MNAME {
            get {
                return this.mNAMEField;
            }
            set {
                this.mNAMEField = value;
            }
        }
        
        /// <remarks/>
        public string MODEL {
            get {
                return this.mODELField;
            }
            set {
                this.mODELField = value;
            }
        }
        
        /// <remarks/>
        public string MRTCODE {
            get {
                return this.mRTCODEField;
            }
            set {
                this.mRTCODEField = value;
            }
        }
        
        /// <remarks/>
        public string MDEPT {
            get {
                return this.mDEPTField;
            }
            set {
                this.mDEPTField = value;
            }
        }
        
        /// <remarks/>
        public string MPRAC {
            get {
                return this.mPRACField;
            }
            set {
                this.mPRACField = value;
            }
        }
        
        /// <remarks/>
        public string MLOC {
            get {
                return this.mLOCField;
            }
            set {
                this.mLOCField = value;
            }
        }
        
        /// <remarks/>
        public string MOPENDT {
            get {
                return this.mOPENDTField;
            }
            set {
                this.mOPENDTField = value;
            }
        }
        
        /// <remarks/>
        public string MBILLATY {
            get {
                return this.mBILLATYField;
            }
            set {
                this.mBILLATYField = value;
            }
        }
        
        /// <remarks/>
        public string MSUPATY {
            get {
                return this.mSUPATYField;
            }
            set {
                this.mSUPATYField = value;
            }
        }
        
        /// <remarks/>
        public string MORGATY {
            get {
                return this.mORGATYField;
            }
            set {
                this.mORGATYField = value;
            }
        }
        
        /// <remarks/>
        public string MHOLDDT {
            get {
                return this.mHOLDDTField;
            }
            set {
                this.mHOLDDTField = value;
            }
        }
        
        /// <remarks/>
        public string MCONTACT {
            get {
                return this.mCONTACTField;
            }
            set {
                this.mCONTACTField = value;
            }
        }
        
        /// <remarks/>
        public string MDESC1 {
            get {
                return this.mDESC1Field;
            }
            set {
                this.mDESC1Field = value;
            }
        }
        
        /// <remarks/>
        public string MDESC2 {
            get {
                return this.mDESC2Field;
            }
            set {
                this.mDESC2Field = value;
            }
        }
        
        /// <remarks/>
        public string MDESC3 {
            get {
                return this.mDESC3Field;
            }
            set {
                this.mDESC3Field = value;
            }
        }
        
        /// <remarks/>
        public string MINSTR1 {
            get {
                return this.mINSTR1Field;
            }
            set {
                this.mINSTR1Field = value;
            }
        }
        
        /// <remarks/>
        public string MINSTR2 {
            get {
                return this.mINSTR2Field;
            }
            set {
                this.mINSTR2Field = value;
            }
        }
        
        /// <remarks/>
        public string MCLIENT {
            get {
                return this.mCLIENTField;
            }
            set {
                this.mCLIENTField = value;
            }
        }
        
        /// <remarks/>
        public string MADDR1 {
            get {
                return this.mADDR1Field;
            }
            set {
                this.mADDR1Field = value;
            }
        }
        
        /// <remarks/>
        public string MADDR2 {
            get {
                return this.mADDR2Field;
            }
            set {
                this.mADDR2Field = value;
            }
        }
        
        /// <remarks/>
        public string MADDR3 {
            get {
                return this.mADDR3Field;
            }
            set {
                this.mADDR3Field = value;
            }
        }
        
        /// <remarks/>
        public string MADDR4 {
            get {
                return this.mADDR4Field;
            }
            set {
                this.mADDR4Field = value;
            }
        }
        
        /// <remarks/>
        public string MADDR5 {
            get {
                return this.mADDR5Field;
            }
            set {
                this.mADDR5Field = value;
            }
        }
        
        /// <remarks/>
        public string MADDR6 {
            get {
                return this.mADDR6Field;
            }
            set {
                this.mADDR6Field = value;
            }
        }
        
        /// <remarks/>
        public string MPHONE {
            get {
                return this.mPHONEField;
            }
            set {
                this.mPHONEField = value;
            }
        }
        
        /// <remarks/>
        public string MTMIN {
            get {
                return this.mTMINField;
            }
            set {
                this.mTMINField = value;
            }
        }
        
        /// <remarks/>
        public string MCMIN {
            get {
                return this.mCMINField;
            }
            set {
                this.mCMINField = value;
            }
        }
        
        /// <remarks/>
        public string MTOTMIN {
            get {
                return this.mTOTMINField;
            }
            set {
                this.mTOTMINField = value;
            }
        }
        
        /// <remarks/>
        public string MFFREQ {
            get {
                return this.mFFREQField;
            }
            set {
                this.mFFREQField = value;
            }
        }
        
        /// <remarks/>
        public string MCFREQ {
            get {
                return this.mCFREQField;
            }
            set {
                this.mCFREQField = value;
            }
        }
        
        /// <remarks/>
        public string MTMPLT {
            get {
                return this.mTMPLTField;
            }
            set {
                this.mTMPLTField = value;
            }
        }
        
        /// <remarks/>
        public string MTFORMAT {
            get {
                return this.mTFORMATField;
            }
            set {
                this.mTFORMATField = value;
            }
        }
        
        /// <remarks/>
        public string MCFORMAT {
            get {
                return this.mCFORMATField;
            }
            set {
                this.mCFORMATField = value;
            }
        }
        
        /// <remarks/>
        public string MTMARK {
            get {
                return this.mTMARKField;
            }
            set {
                this.mTMARKField = value;
            }
        }
        
        /// <remarks/>
        public string MTMRKLED {
            get {
                return this.mTMRKLEDField;
            }
            set {
                this.mTMRKLEDField = value;
            }
        }
        
        /// <remarks/>
        public string MCMARK {
            get {
                return this.mCMARKField;
            }
            set {
                this.mCMARKField = value;
            }
        }
        
        /// <remarks/>
        public string MCMRKLED {
            get {
                return this.mCMRKLEDField;
            }
            set {
                this.mCMRKLEDField = value;
            }
        }
        
        /// <remarks/>
        public string MINTRST {
            get {
                return this.mINTRSTField;
            }
            set {
                this.mINTRSTField = value;
            }
        }
        
        /// <remarks/>
        public string MINTDAYS {
            get {
                return this.mINTDAYSField;
            }
            set {
                this.mINTDAYSField = value;
            }
        }
        
        /// <remarks/>
        public string MINTLED {
            get {
                return this.mINTLEDField;
            }
            set {
                this.mINTLEDField = value;
            }
        }
        
        /// <remarks/>
        public string MFFEE {
            get {
                return this.mFFEEField;
            }
            set {
                this.mFFEEField = value;
            }
        }
        
        /// <remarks/>
        public string MFCOST {
            get {
                return this.mFCOSTField;
            }
            set {
                this.mFCOSTField = value;
            }
        }
        
        /// <remarks/>
        public string MRATED {
            get {
                return this.mRATEDField;
            }
            set {
                this.mRATEDField = value;
            }
        }
        
        /// <remarks/>
        public string MREFER {
            get {
                return this.mREFERField;
            }
            set {
                this.mREFERField = value;
            }
        }
        
        /// <remarks/>
        public string MCHOLDDT {
            get {
                return this.mCHOLDDTField;
            }
            set {
                this.mCHOLDDTField = value;
            }
        }
        
        /// <remarks/>
        public string MFTMPLT {
            get {
                return this.mFTMPLTField;
            }
            set {
                this.mFTMPLTField = value;
            }
        }
        
        /// <remarks/>
        public string MFOLLOW1 {
            get {
                return this.mFOLLOW1Field;
            }
            set {
                this.mFOLLOW1Field = value;
            }
        }
        
        /// <remarks/>
        public string MFOLLOW2 {
            get {
                return this.mFOLLOW2Field;
            }
            set {
                this.mFOLLOW2Field = value;
            }
        }
        
        /// <remarks/>
        public string MFOLLOW3 {
            get {
                return this.mFOLLOW3Field;
            }
            set {
                this.mFOLLOW3Field = value;
            }
        }
        
        /// <remarks/>
        public string MFOLLOW4 {
            get {
                return this.mFOLLOW4Field;
            }
            set {
                this.mFOLLOW4Field = value;
            }
        }
        
        /// <remarks/>
        public string MTRACCT {
            get {
                return this.mTRACCTField;
            }
            set {
                this.mTRACCTField = value;
            }
        }
        
        /// <remarks/>
        public string MCURRENCY {
            get {
                return this.mCURRENCYField;
            }
            set {
                this.mCURRENCYField = value;
            }
        }
        
        /// <remarks/>
        public string MMAXFEE {
            get {
                return this.mMAXFEEField;
            }
            set {
                this.mMAXFEEField = value;
            }
        }
        
        /// <remarks/>
        public string MPHPREFIX {
            get {
                return this.mPHPREFIXField;
            }
            set {
                this.mPHPREFIXField = value;
            }
        }
        
        /// <remarks/>
        public string MMASTER {
            get {
                return this.mMASTERField;
            }
            set {
                this.mMASTERField = value;
            }
        }
        
        /// <remarks/>
        public string MCOPIES {
            get {
                return this.mCOPIESField;
            }
            set {
                this.mCOPIESField = value;
            }
        }
        
        /// <remarks/>
        public string MARRANGE {
            get {
                return this.mARRANGEField;
            }
            set {
                this.mARRANGEField = value;
            }
        }
        
        /// <remarks/>
        public string MTIMEUNIT {
            get {
                return this.mTIMEUNITField;
            }
            set {
                this.mTIMEUNITField = value;
            }
        }
        
        /// <remarks/>
        public string FIELD1 {
            get {
                return this.fIELD1Field;
            }
            set {
                this.fIELD1Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD2 {
            get {
                return this.fIELD2Field;
            }
            set {
                this.fIELD2Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD3 {
            get {
                return this.fIELD3Field;
            }
            set {
                this.fIELD3Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD4 {
            get {
                return this.fIELD4Field;
            }
            set {
                this.fIELD4Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD5 {
            get {
                return this.fIELD5Field;
            }
            set {
                this.fIELD5Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD6 {
            get {
                return this.fIELD6Field;
            }
            set {
                this.fIELD6Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD7 {
            get {
                return this.fIELD7Field;
            }
            set {
                this.fIELD7Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD8 {
            get {
                return this.fIELD8Field;
            }
            set {
                this.fIELD8Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD9 {
            get {
                return this.fIELD9Field;
            }
            set {
                this.fIELD9Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD10 {
            get {
                return this.fIELD10Field;
            }
            set {
                this.fIELD10Field = value;
            }
        }
        
        /// <remarks/>
        public string FIELD11 {
            get {
                return this.fIELD11Field;
            }
            set {
                this.fIELD11Field = value;
            }
        }
        
        /// <remarks/>
        public string MNONBILL {
            get {
                return this.mNONBILLField;
            }
            set {
                this.mNONBILLField = value;
            }
        }
        
        /// <remarks/>
        public string MNPOSTF {
            get {
                return this.mNPOSTFField;
            }
            set {
                this.mNPOSTFField = value;
            }
        }
        
        /// <remarks/>
        public string MNBCOST {
            get {
                return this.mNBCOSTField;
            }
            set {
                this.mNBCOSTField = value;
            }
        }
        
        /// <remarks/>
        public string MN1PR260 {
            get {
                return this.mN1PR260Field;
            }
            set {
                this.mN1PR260Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1PR270 {
            get {
                return this.mN1PR270Field;
            }
            set {
                this.mN1PR270Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1PR280 {
            get {
                return this.mN1PR280Field;
            }
            set {
                this.mN1PR280Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1PR290 {
            get {
                return this.mN1PR290Field;
            }
            set {
                this.mN1PR290Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1DP260 {
            get {
                return this.mN1DP260Field;
            }
            set {
                this.mN1DP260Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1DP270 {
            get {
                return this.mN1DP270Field;
            }
            set {
                this.mN1DP270Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1DP280 {
            get {
                return this.mN1DP280Field;
            }
            set {
                this.mN1DP280Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1DP290 {
            get {
                return this.mN1DP290Field;
            }
            set {
                this.mN1DP290Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2PR260 {
            get {
                return this.mN2PR260Field;
            }
            set {
                this.mN2PR260Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2PR270 {
            get {
                return this.mN2PR270Field;
            }
            set {
                this.mN2PR270Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2PR280 {
            get {
                return this.mN2PR280Field;
            }
            set {
                this.mN2PR280Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2PR290 {
            get {
                return this.mN2PR290Field;
            }
            set {
                this.mN2PR290Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2DP260 {
            get {
                return this.mN2DP260Field;
            }
            set {
                this.mN2DP260Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2DP270 {
            get {
                return this.mN2DP270Field;
            }
            set {
                this.mN2DP270Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2DP280 {
            get {
                return this.mN2DP280Field;
            }
            set {
                this.mN2DP280Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2DP290 {
            get {
                return this.mN2DP290Field;
            }
            set {
                this.mN2DP290Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1ACU260 {
            get {
                return this.mN1ACU260Field;
            }
            set {
                this.mN1ACU260Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1ACU270 {
            get {
                return this.mN1ACU270Field;
            }
            set {
                this.mN1ACU270Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1ACU280 {
            get {
                return this.mN1ACU280Field;
            }
            set {
                this.mN1ACU280Field = value;
            }
        }
        
        /// <remarks/>
        public string MN1ACU290 {
            get {
                return this.mN1ACU290Field;
            }
            set {
                this.mN1ACU290Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2ACU260 {
            get {
                return this.mN2ACU260Field;
            }
            set {
                this.mN2ACU260Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2ACU270 {
            get {
                return this.mN2ACU270Field;
            }
            set {
                this.mN2ACU270Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2ACU280 {
            get {
                return this.mN2ACU280Field;
            }
            set {
                this.mN2ACU280Field = value;
            }
        }
        
        /// <remarks/>
        public string MN2ACU290 {
            get {
                return this.mN2ACU290Field;
            }
            set {
                this.mN2ACU290Field = value;
            }
        }
        
        /// <remarks/>
        public string MSTATUS {
            get {
                return this.mSTATUSField;
            }
            set {
                this.mSTATUSField = value;
            }
        }
        
        /// <remarks/>
        public string MPROTEM {
            get {
                return this.mPROTEMField;
            }
            set {
                this.mPROTEMField = value;
            }
        }
        
        /// <remarks/>
        public string MJNUM {
            get {
                return this.mJNUMField;
            }
            set {
                this.mJNUMField = value;
            }
        }
        
        /// <remarks/>
        public string MFAX {
            get {
                return this.mFAXField;
            }
            set {
                this.mFAXField = value;
            }
        }
        
        /// <remarks/>
        public string MCLOSEDT {
            get {
                return this.mCLOSEDTField;
            }
            set {
                this.mCLOSEDTField = value;
            }
        }
        
        /// <remarks/>
        public string MRELATED {
            get {
                return this.mRELATEDField;
            }
            set {
                this.mRELATEDField = value;
            }
        }
        
        /// <remarks/>
        public string MNARRATIVE {
            get {
                return this.mNARRATIVEField;
            }
            set {
                this.mNARRATIVEField = value;
            }
        }
        
        /// <remarks/>
        public string MIOBILLING {
            get {
                return this.mIOBILLINGField;
            }
            set {
                this.mIOBILLINGField = value;
            }
        }
        
        /// <remarks/>
        public string MLANG {
            get {
                return this.mLANGField;
            }
            set {
                this.mLANGField = value;
            }
        }
        
        /// <remarks/>
        public string MTAXC {
            get {
                return this.mTAXCField;
            }
            set {
                this.mTAXCField = value;
            }
        }
        
        /// <remarks/>
        public string MTAXT {
            get {
                return this.mTAXTField;
            }
            set {
                this.mTAXTField = value;
            }
        }
        
        /// <remarks/>
        public string MUNIT {
            get {
                return this.mUNITField;
            }
            set {
                this.mUNITField = value;
            }
        }
        
        /// <remarks/>
        public string MFIXCAP {
            get {
                return this.mFIXCAPField;
            }
            set {
                this.mFIXCAPField = value;
            }
        }
        
        /// <remarks/>
        public string MRATE {
            get {
                return this.mRATEField;
            }
            set {
                this.mRATEField = value;
            }
        }
        
        /// <remarks/>
        public string MDISCOUNTGRP {
            get {
                return this.mDISCOUNTGRPField;
            }
            set {
                this.mDISCOUNTGRPField = value;
            }
        }
        
        /// <remarks/>
        public string MGLOBAL {
            get {
                return this.mGLOBALField;
            }
            set {
                this.mGLOBALField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("udf")]
        public Udf[] udf {
            get {
                return this.udfField;
            }
            set {
                this.udfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateMultiPayorCompletedEventHandler(object sender, CreateMultiPayorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultiPayorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultiPayorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591