DECLARE @Length INT = (SELECT CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'dbContactCompany' AND COLUMN_NAME = 'contRegCoName')
IF @Length < 80
	ALTER TABLE dbo.dbContactCompany ALTER COLUMN contRegCoName NVARCHAR (80)
GO