
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage21Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage22Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage23Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage24Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage25Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage26Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage27Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage28Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage29Desc' , @columnDesc = 'nvarchar(50) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage30Desc' , @columnDesc = 'nvarchar(50) NULL'

exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage21Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage22Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage23Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage24Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage25Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage26Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage27Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage28Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage29Days' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage30Days' , @columnDesc = 'smallint NULL'

exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage21LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage22LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage23LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage24LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage25LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage26LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage27LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage28LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage29LongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage30LongDesc' , @columnDesc = 'ntext NULL'

exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage21Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage22Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage23Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage24Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage25Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage26Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage27Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage28Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage29Calcfrom' , @columnDesc = 'smallint NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage30Calcfrom' , @columnDesc = 'smallint NULL'

exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage21ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage22ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage23ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage24ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage25ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage26ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage27ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage28ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage29ReallyLongDesc' , @columnDesc = 'ntext NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage30ReallyLongDesc' , @columnDesc = 'ntext NULL'

exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage21Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage22Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage23Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage24Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage25Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage26Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage27Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage28Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage29Action' , @columnDesc = 'nvarchar(20) NULL'
exec fwbsaddcolumn @tablename = 'dbMSConfig_OMS2K' , @columnName = 'MSStage30Action' , @columnDesc = 'nvarchar(20) NULL'
