//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSCacheMgr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSCacheMgr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned Connection.
        /// </summary>
        internal static string Abandoned_Connection {
            get {
                return ResourceManager.GetString("Abandoned_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned Connections.
        /// </summary>
        internal static string Abandoned_Connections {
            get {
                return ResourceManager.GetString("Abandoned_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Access.
        /// </summary>
        internal static string Directory_Access {
            get {
                return ResourceManager.GetString("Directory_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory you are attempting to access no longer exists.
        /// </summary>
        internal static string Directory_not_exists {
            get {
                return ResourceManager.GetString("Directory_not_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating the number of files to delete.
        /// </summary>
        internal static string Error_calculating_the_number_of_files_to_delete {
            get {
                return ResourceManager.GetString("Error_calculating_the_number_of_files_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exclamation2b {
            get {
                object obj = ResourceManager.GetObject("exclamation2b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Connection.
        /// </summary>
        internal static string Existing_Connection {
            get {
                return ResourceManager.GetString("Existing_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Connections.
        /// </summary>
        internal static string Existing_Connections {
            get {
                return ResourceManager.GetString("Existing_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string File_Not_Found {
            get {
                return ResourceManager.GetString("File_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Existing Connections.
        /// </summary>
        internal static string No_Existing_Connections {
            get {
                return ResourceManager.GetString("No_Existing_Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TreeView Initialisation Error.
        /// </summary>
        internal static string TreeView_Initialisation_Error {
            get {
                return ResourceManager.GetString("TreeView_Initialisation_Error", resourceCulture);
            }
        }
    }
}
