CREATE TABLE [dbo].[dbMSConfig_OMS2K] (
    [MSCode]                  [dbo].[uCodeLookup] NOT NULL,
    [MSDescription]           NVARCHAR (50)       NOT NULL,
    [MSDept]                  [dbo].[uCodeLookup] NOT NULL,
    [MSAll]                   BIT                 NOT NULL,
    [MSStage1Desc]            NVARCHAR (50)       NULL,
    [MSStage2Desc]            NVARCHAR (50)       NULL,
    [MSStage3Desc]            NVARCHAR (50)       NULL,
    [MSStage4Desc]            NVARCHAR (50)       NULL,
    [MSStage5Desc]            NVARCHAR (50)       NULL,
    [MSStage6Desc]            NVARCHAR (50)       NULL,
    [MSStage7Desc]            NVARCHAR (50)       NULL,
    [MSStage8Desc]            NVARCHAR (50)       NULL,
    [MSStage9Desc]            NVARCHAR (50)       NULL,
    [MSStage10Desc]           NVARCHAR (50)       NULL,
    [MSStage11Desc]           NVARCHAR (50)       NULL,
    [MSStage12Desc]           NVARCHAR (50)       NULL,
    [MSStage13Desc]           NVARCHAR (50)       NULL,
    [MSStage14Desc]           NVARCHAR (50)       NULL,
    [MSStage15Desc]           NVARCHAR (50)       NULL,
    [MSStage16Desc]           NVARCHAR (50)       NULL,
    [MSStage17Desc]           NVARCHAR (50)       NULL,
    [MSStage18Desc]           NVARCHAR (50)       NULL,
    [MSStage19Desc]           NVARCHAR (50)       NULL,
    [MSStage20Desc]           NVARCHAR (50)       NULL,
    [MSStage21Desc]           NVARCHAR (50)       NULL,
    [MSStage22Desc]           NVARCHAR (50)       NULL,
    [MSStage23Desc]           NVARCHAR (50)       NULL,
    [MSStage24Desc]           NVARCHAR (50)       NULL,
    [MSStage25Desc]           NVARCHAR (50)       NULL,
    [MSStage26Desc]           NVARCHAR (50)       NULL,
    [MSStage27Desc]           NVARCHAR (50)       NULL,
    [MSStage28Desc]           NVARCHAR (50)       NULL,
    [MSStage29Desc]           NVARCHAR (50)       NULL,
    [MSStage30Desc]           NVARCHAR (50)       NULL,
    [MSStage1Days]            SMALLINT            NULL,
    [MSStage2Days]            SMALLINT            NULL,
    [MSStage3Days]            SMALLINT            NULL,
    [MSStage4Days]            SMALLINT            NULL,
    [MSStage5Days]            SMALLINT            NULL,
    [MSStage6Days]            SMALLINT            NULL,
    [MSStage7Days]            SMALLINT            NULL,
    [MSStage8Days]            SMALLINT            NULL,
    [MSStage9Days]            SMALLINT            NULL,
    [MSStage10Days]           SMALLINT            NULL,
    [MSStage11Days]           SMALLINT            NULL,
    [MSStage12Days]           SMALLINT            NULL,
    [MSStage13Days]           SMALLINT            NULL,
    [MSStage14Days]           SMALLINT            NULL,
    [MSStage15Days]           SMALLINT            NULL,
    [MSStage16Days]           SMALLINT            NULL,
    [MSStage17Days]           SMALLINT            NULL,
    [MSStage18Days]           SMALLINT            NULL,
    [MSStage19Days]           SMALLINT            NULL,
    [MSStage20Days]           SMALLINT            NULL,
    [MSStage21Days]           SMALLINT            NULL,
    [MSStage22Days]           SMALLINT            NULL,
    [MSStage23Days]           SMALLINT            NULL,
    [MSStage24Days]           SMALLINT            NULL,
    [MSStage25Days]           SMALLINT            NULL,
    [MSStage26Days]           SMALLINT            NULL,
    [MSStage27Days]           SMALLINT            NULL,
    [MSStage28Days]           SMALLINT            NULL,
    [MSStage29Days]           SMALLINT            NULL,
    [MSStage30Days]           SMALLINT            NULL,
	[MSStage1LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage2LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage3LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage4LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage5LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage6LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage7LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage8LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage9LongDesc]        NVARCHAR (MAX)      NULL,
    [MSStage10LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage11LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage12LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage13LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage14LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage15LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage16LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage17LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage18LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage19LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage20LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage21LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage22LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage23LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage24LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage25LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage26LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage27LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage28LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage29LongDesc]       NVARCHAR (MAX)      NULL,
    [MSStage30LongDesc]       NVARCHAR (MAX)      NULL,
	[MSStage1Calcfrom]        SMALLINT            NULL,
	[MSStage2Calcfrom]        SMALLINT            NULL,
    [MSStage3Calcfrom]        SMALLINT            NULL,
    [MSStage4Calcfrom]        SMALLINT            NULL,
    [MSStage5Calcfrom]        SMALLINT            NULL,
    [MSStage6Calcfrom]        SMALLINT            NULL,
    [MSStage7Calcfrom]        SMALLINT            NULL,
    [MSStage8Calcfrom]        SMALLINT            NULL,
    [MSStage9Calcfrom]        SMALLINT            NULL,
    [MSStage10Calcfrom]       SMALLINT            NULL,
    [MSStage11Calcfrom]       SMALLINT            NULL,
    [MSStage12Calcfrom]       SMALLINT            NULL,
    [MSStage13Calcfrom]       SMALLINT            NULL,
    [MSStage14Calcfrom]       SMALLINT            NULL,
    [MSStage15Calcfrom]       SMALLINT            NULL,
    [MSStage16Calcfrom]       SMALLINT            NULL,
    [MSStage17Calcfrom]       SMALLINT            NULL,
    [MSStage18Calcfrom]       SMALLINT            NULL,
    [MSStage19Calcfrom]       SMALLINT            NULL,
    [MSStage20Calcfrom]       SMALLINT            NULL,
    [MSStage21Calcfrom]       SMALLINT            NULL,
    [MSStage22Calcfrom]       SMALLINT            NULL,
    [MSStage23Calcfrom]       SMALLINT            NULL,
    [MSStage24Calcfrom]       SMALLINT            NULL,
    [MSStage25Calcfrom]       SMALLINT            NULL,
    [MSStage26Calcfrom]       SMALLINT            NULL,
    [MSStage27Calcfrom]       SMALLINT            NULL,
    [MSStage28Calcfrom]       SMALLINT            NULL,
    [MSStage29Calcfrom]       SMALLINT            NULL,
    [MSStage30Calcfrom]       SMALLINT            NULL,
    [MSStage1ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage2ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage3ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage4ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage5ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage6ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage7ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage8ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage9ReallyLongDesc]  NVARCHAR (MAX)      NULL,
    [MSStage10ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage11ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage12ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage13ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage14ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage15ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage16ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage17ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage18ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage19ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage20ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage21ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage22ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage23ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage24ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage25ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage26ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage27ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage28ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage29ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage30ReallyLongDesc] NVARCHAR (MAX)      NULL,
    [MSStage1Action]          NVARCHAR (20)       NULL,
    [MSStage2Action]          NVARCHAR (20)       NULL,
    [MSStage3Action]          NVARCHAR (20)       NULL,
    [MSStage4Action]          NVARCHAR (20)       NULL,
    [MSStage5Action]          NVARCHAR (20)       NULL,
    [MSStage6Action]          NVARCHAR (20)       NULL,
    [MSStage7Action]          NVARCHAR (20)       NULL,
    [MSStage8Action]          NVARCHAR (20)       NULL,
    [MSStage9Action]          NVARCHAR (20)       NULL,
    [MSStage10Action]         NVARCHAR (20)       NULL,
    [MSStage11Action]         NVARCHAR (20)       NULL,
    [MSStage12Action]         NVARCHAR (20)       NULL,
    [MSStage13Action]         NVARCHAR (20)       NULL,
    [MSStage14Action]         NVARCHAR (20)       NULL,
    [MSStage15Action]         NVARCHAR (20)       NULL,
    [MSStage16Action]         NVARCHAR (20)       NULL,
    [MSStage17Action]         NVARCHAR (20)       NULL,
    [MSStage18Action]         NVARCHAR (20)       NULL,
    [MSStage19Action]         NVARCHAR (20)       NULL,
    [MSStage20Action]         NVARCHAR (20)       NULL,
    [MSStage21Action]         NVARCHAR (20)       NULL,
    [MSStage22Action]         NVARCHAR (20)       NULL,
    [MSStage23Action]         NVARCHAR (20)       NULL,
    [MSStage24Action]         NVARCHAR (20)       NULL,
    [MSStage25Action]         NVARCHAR (20)       NULL,
    [MSStage26Action]         NVARCHAR (20)       NULL,
    [MSStage27Action]         NVARCHAR (20)       NULL,
    [MSStage28Action]         NVARCHAR (20)       NULL,
    [MSStage29Action]         NVARCHAR (20)       NULL,
    [MSStage30Action]         NVARCHAR (20)       NULL,
	[rowguid]                 UNIQUEIDENTIFIER    CONSTRAINT [DF_dbMSConfig_OMS2K_rowguid] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    CONSTRAINT [PK_dbMSConfig_OMS2K] PRIMARY KEY CLUSTERED ([MSCode] ASC) WITH (FILLFACTOR = 90)
);




GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_dbMSConfig_OMS2K_rowguid]
    ON [dbo].[dbMSConfig_OMS2K]([rowguid] ASC) WITH (FILLFACTOR = 90)
    ON [IndexGroup];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[dbMSConfig_OMS2K] TO [OMSApplicationRole]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[dbMSConfig_OMS2K] TO [OMSApplicationRole]
    AS [dbo];


GO
GRANT INSERT
    ON OBJECT::[dbo].[dbMSConfig_OMS2K] TO [OMSApplicationRole]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[dbMSConfig_OMS2K] TO [OMSApplicationRole]
    AS [dbo];

