--ADD ADDITIONAL COLUMNS TO COLLECT UDF 2, 3 , 4 AND 5 FOR ENTERPRISE INTEGRATION

EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbTimeLedger'
	, @COLUMNNAME = 'ENTERPRISE_UDF2'
	, @COLUMNDESC = 'NVARCHAR ( 10 )'
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbTimeLedger'
	, @COLUMNNAME = 'ENTERPRISE_UDF3'
	, @COLUMNDESC = 'NVARCHAR ( 10 )'
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbTimeLedger'
	, @COLUMNNAME = 'ENTERPRISE_UDF4'
	, @COLUMNDESC = 'NVARCHAR ( 10 )'
EXEC FWBSADDCOLUMN 
	@TABLENAME = 'dbTimeLedger'
	, @COLUMNNAME = 'ENTERPRISE_UDF5'
	, @COLUMNDESC = 'NVARCHAR ( 10 )'
EXEC FWBSADDCOLUMN --COLUMN TO STORE LOCAL RECORDED DATE TIME IN - POPULATED IN SCRIPTING ON TIME SCREEN WHERE USED IF NEEDED FOR MULTI-OFFICE SCENARIOS IN DIFFERENT TIME ZONES - TEXT FIELD SO DOES NOT GET TRANSLATED TO UTC AGAIN - NVARCHAR AS LOWEST SQL PLATFORM IS SQL 2005
	@TABLENAME = 'dbTimeLedger'
	, @COLUMNNAME = 'timeRecorded_Actual'
	, @COLUMNDESC = 'datetime NULL'
EXEC FWBSADDCOLUMN --COLUMN TO STORE LOCAL RECORDED TIME ZONE - POPULATED IN SCRIPTING ON TIME SCREEN WHERE USED IF NEEDED FOR MULTI-OFFICE SCENARIOS IN DIFFERENT TIME ZONES - TEXT FIELD SO DOES NOT GET TRANSLATED TO UTC AGAIN - NVARCHAR AS LOWEST SQL PLATFORM IS SQL 2005
	@TABLENAME = 'dbTimeLedger'
	, @COLUMNNAME = 'timeRecorded_tz'
	, @COLUMNDESC = 'NVARCHAR ( 100 )'