	DECLARE @Flag bit 
	set @flag=1
	DECLARE @DBNAME sysname 
	set @DBNAME=  quotename(DB_NAME());
	
	IF (@Flag = 1 AND CHANGE_TRACKING_CURRENT_VERSION() IS NULL)
		exec('ALTER DATABASE '+@DBNAME+'SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 3 DAYS, AUTO_CLEANUP = ON)')


GO