USE MASTER
GO

DECLARE @IS_BROKER_ENABLED BIT

SELECT @IS_BROKER_ENABLED = IS_BROKER_ENABLED FROM SYS.DATABASES WHERE NAME = N'$(DatabaseName)'

IF @IS_BROKER_ENABLED = 0 
BEGIN
	PRINT 'ENABLING BROKER'
	ALTER DATABASE [$(DatabaseName)] SET ENABLE_BROKER
END
ELSE
	PRINT 'BROKER ALREADY ENABLED'
GO

USE [$(DatabaseName)]
GO
