EXEC FWBSADDCOLUMN @TABLENAME = 'dbExtendedData' , @COLUMNNAME = 'extWhereMsApi' , @COLUMNDESC = 'NVARCHAR (250) NULL'
EXEC FWBSADDCOLUMN @TABLENAME = 'dbExtendedData' , @COLUMNNAME = 'extApiExclude' , @COLUMNDESC = 'BIT NOT NULL DEFAULT 1'
EXEC FWBSADDCOLUMN @TABLENAME = 'dbSearchListConfig' , @COLUMNNAME = 'schApiExclude' , @COLUMNDESC = 'BIT NOT NULL DEFAULT 1'
EXEC FWBSADDCOLUMN @TABLENAME = 'dbEnquiryDataList' , @COLUMNNAME = 'enqApiExclude' , @COLUMNDESC = 'BIT NOT NULL DEFAULT 1'
GO