CREATE TABLE [dbo].[fdRaPIdAccidentDetails](
	[fileID] [bigint] NOT NULL,
	[rpdAccClaimantType] [nvarchar](50) NULL,
	[rpdAccOccupantsNumber] [int] NULL,
	[rpdAccSeatbelt] [nvarchar](15) NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccSeatbelt]  DEFAULT (0),
	[rpdAccDate] [datetime] NULL,
	[rpdAccTime] [nvarchar](10) NULL,
	[rpdAccLocation] [nvarchar](100) NULL,
	[rpdAccDescription] [nvarchar](1000) NULL,
	[rpdAccPoliceReported] [nvarchar](15) NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccPoliceReported]  DEFAULT (0),
	[rpdAccDriverName] [nvarchar](25) NULL,
	[rpdAccDriverMiddleName] [nvarchar](25) NULL,
	[rpdAccDriverSurname] [nvarchar](25) NULL,
	[rpdAccDriverCountry] [nvarchar](50) NULL,
	[rpdAccDriverDistrict] [nvarchar](50) NULL,
	[rpdAccDriverCity] [nvarchar](50) NULL,
	[rpdAccDriverStreet1] [nvarchar](50) NULL,
	[rpdAccDriverHouseName] [nvarchar](50) NULL,
	[rpdAccDriverHouseNumber] [nvarchar](10) NULL,
	[rpdAccDriverAddressType] [nvarchar](25) NULL,
	[rpdAccOwnerCountry] [nvarchar](50) NULL,
	[rpdAccOwnerDistrict] [nvarchar](50) NULL,
	[rpdAccOwnerCity] [nvarchar](50) NULL,
	[rpdAccOwnerStreet1] [nvarchar](50) NULL,
	[rpdAccOwnerHouseName] [nvarchar](50) NULL,
	[rpdAccOwnerHouseNumber] [nvarchar](10) NULL,
	[rpdAccOwnerAddressType] [nvarchar](25) NULL,
	[rpdAccInsCompCountry] [nvarchar](50) NULL,
	[rpdAccInsCompDistrict] [nvarchar](50) NULL,
	[rpdAccInsCompCity] [nvarchar](50) NULL,
	[rpdAccInsCompStreet1] [nvarchar](50) NULL,
	[rpdAccInsCompHouseName] [nvarchar](50) NULL,
	[rpdAccInsCompHouseNumber] [nvarchar](10) NULL,
	[rpdAccInsCompAddressType] [nvarchar](25) NULL,
	[rpdAccPoliceStation] [nvarchar](75) NULL,
	[rpdAccPoliceAddress] [nvarchar](200) NULL,
	[rpdAccPoliceOfficerName] [nvarchar](50) NULL,
	[rpdAccPoliceReference] [nvarchar](50) NULL,
	[rpdAccBusOrCoach] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccBusOrCoach]  DEFAULT (0),
	[rpdAcctBusOrCoachDrvName] [nvarchar](50) NULL,
	[rpdAccBusOrCoachDrvID] [nvarchar](50) NULL,
	[rpdAccBusOrCoachDrvDesc] [nvarchar](500) NULL,
	[rpdAccBusOrCoachVclDesc] [nvarchar](500) NULL,
	[rpdAccBusOrCoachPsngrCnt] [int] NULL,
	[rpdAccBusOrCoachComments] [nvarchar](500) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_fdRaPIDAccidentDetails_rowguid]  DEFAULT (newid()),
	[rpdAccClaimantTypeOther] [nvarchar](30) NULL,
	[rpdAccDriverIsDefendant] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccDriverIsDefendant]  DEFAULT (0),
	[rpdAccOwnerName] [nvarchar](50) NULL,
	[rpdAccOwnerMiddleName] [nvarchar](50) NULL,
	[rpdAccOwnerSurname] [nvarchar](50) NULL,
	[rpdAccVclMake] [nvarchar](25) NULL,
	[rpdAccVclModel] [nvarchar](30) NULL,
	[rpdAccVclReg] [nvarchar](15) NULL,
	[rpdAccInsCompName] [nvarchar](100) NULL,
	[rpdAccInsCompPolicyNo] [nvarchar](50) NULL,
	[rpdAccBusOrCoachEvidence] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccBusOrCoachEvidence]  DEFAULT (0),
	[rpdAccBusOrCoachWhyNoEvd] [nvarchar](500) NULL,
	[rpdAccDriverStreet2] [nvarchar](50) NULL,
	[rpdAccDriverPostCode] [nvarchar](20) NULL,
	[rpdAccOwnerStreet2] [nvarchar](50) NULL,
	[rpdAccOwnerPostCode] [nvarchar](20) NULL,
	[rpdAccInsCompStreet2] [nvarchar](50) NULL,
	[rpdAccInsCompCounty] [nvarchar](50) NULL,
	[rpdAccInsCompPostCode] [nvarchar](20) NULL,
	[rpdAccDriverCounty] [nvarchar](50) NULL,
	[rpdAccOwnerCounty] [nvarchar](50) NULL,
	[rpdAccWthrSun] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrSun]  DEFAULT (0),
	[rpdAccWthrRain] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrRain]  DEFAULT (0),
	[rpdAccWthrSnow] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrSnow]  DEFAULT (0),
	[rpdAccWthrIce] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrIce]  DEFAULT (0),
	[rpdAccWthrFog] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrFog]  DEFAULT (0),
	[rpdAccWthrOther] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrOther]  DEFAULT (0),
	[rpdAccWthrOtherDetails] [nvarchar](200) NULL,
	[rpdAccWthrCondDry] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondDry]  DEFAULT (0),
	[rpdAccWthrCondWet] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondWet]  DEFAULT (0),
	[rpdAccWthrCondSnow] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondSnow]  DEFAULT (0),
	[rpdAccWthrCondIce] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondIce]  DEFAULT (0),
	[rpdAccWthrCondMud] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondMud]  DEFAULT (0),
	[rpdAccWthrCondOil] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondOil]  DEFAULT (0),
	[rpdAccWthrCondOther] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccWthrCondOther] DEFAULT (0),
	[rpdAccWthrCondOtherDets] [nvarchar](200) NULL,
	[rpdAccVclHitSideRoad] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclHitSideRoad]  DEFAULT (0),
	[rpdAccVclHitInRear] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclHitInRear]  DEFAULT (0),
	[rpdAccVclHitWhilstParked] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclHitWhilstParked]  DEFAULT (0),
	[rpdAccVclCarPark] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclCarPark]  DEFAULT (0),
	[rpdAccVclRoundabout] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclRoundabout]  DEFAULT (0),
	[rpdAccVclChangingLanes] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclChangingLanes]  DEFAULT (0),
	[rpdAccVclConcertinaColl] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclConcertinaColl]  DEFAULT (0),
	[rpdAccVclOther] [bit] NULL CONSTRAINT [DF_fdRaPIdAccidentDetails_rpdAccVclOther]  DEFAULT (0),
	rpdAccIncidentReported Int NULL,
	rpdAccReportedDateAndToWhom nVarchar(500) NULL,
	rpdAccClaimantLocation Int NULL,
	rpdAccClaimantLocOther Nvarchar(50) NULL,
 CONSTRAINT [PK_fdRaPIDAccidentDetails] PRIMARY KEY CLUSTERED 
(
	[fileID] ASC
) 
) 
