CREATE TABLE [dbo].[fdRaPIdDefendantDetails](
	[fileID] [bigint] NOT NULL,
	[rpdDefStatus] [nvarchar](30) NULL,
	[rpdDefPolicyNoRef] [nvarchar](50) NULL,
	[rpdDefAge] [int] NULL,
	[rpdDefDescription] [nvarchar](200) NULL,
	[rpdDefObtained] [nvarchar](50) NULL,
	[rpdDefSurname] [nvarchar](25) NULL,
	[rpdDefSex] [nvarchar](10) NULL,
	[rpdDefCountry] [nvarchar](50) NULL,
	[rpdDefPostCode] [nvarchar](15) NULL,
	[rpdDefCity] [nvarchar](50) NULL,
	[rpdDefStreet1] [nvarchar](50) NULL,
	[rpdDefHouseName] [nvarchar](50) NULL,
	[rpdDefAddressType] [nvarchar](30) NULL,
	[rpdDefVehicleReg] [nvarchar](20) NULL,
	[rpdDefInsurerType] [nvarchar](30) NULL,
	[rpdDefInsurerName] [nvarchar](100) NULL,
	[rpdDefInsurerOrgID] [nvarchar](50) NULL,
	[rpdDefInsurerOrgPath] [nvarchar](100) NULL,
	[rpdDefCompanyName] [nvarchar](100) NULL,
	[rpdDefWorkCountry] [nvarchar](50) NULL,
	[rpdDefWorkCity] [nvarchar](50) NULL,
	[rpdDefWorkStreet1] [nvarchar](50) NULL,
	[rpdDefWorkHouseName] [nvarchar](50) NULL,
	[rpdDefWorkAddressType] [nvarchar](30) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NULL CONSTRAINT [DF_fdRaPIdDefendantDetails_rowguid]  DEFAULT (newid()),
	[rpdDefTitle] [nvarchar](20) NULL,
	[rpdDefTitleOther] [nvarchar](20) NULL,
	[rpdDefDriverName] [nvarchar](50) NULL,
	[rpdDefReferralSource] [nvarchar](50) NULL,
	[rpdDefComments] [nvarchar](500) NULL,
	[rpdDefFirstName] [nvarchar](50) NULL,
	[rpdDefMiddleName] [nvarchar](50) NULL,
	[rpdDefDateOfBirth] [datetime] NULL,
	[rpdDefVehicleMake] [nvarchar](50) NULL,
	[rpdDefVehicleModel] [nvarchar](50) NULL,
	[rpdDefVehicleColour] [nvarchar](25) NULL,
	[rpdDefVehicleEngSize] [nvarchar](10) NULL,
	[rpdDefInsurerSelected] [bit] NULL CONSTRAINT [DF_fdRaPIdDefendantDetails_rpdDefInsurerSelected]  DEFAULT (0),
	[rpdDefStreet2] [nvarchar](50) NULL,
	[rpdDefDistrict] [nvarchar](50) NULL,
	[rpdDefHouseNumber] [nvarchar](10) NULL,
	[rpdDefCounty] [nvarchar](50) NULL,
	[rpdDefWorkHouseNumber] [nvarchar](10) NULL,
	[rpdDefWorkStreet2] [nvarchar](50) NULL,
	[rpdDefWorkDistrict] [nvarchar](50) NULL,
	[rpdDefWorkCounty] [nvarchar](50) NULL,
	[rpdDefWorkPostCode] [nvarchar](15) NULL,
	rpdDefInsCompanyName NVARCHAR(100) NULL,
 CONSTRAINT [PK_fdRaPIdDefendantDetails] PRIMARY KEY CLUSTERED 
(
	[fileID] ASC
)
)