CREATE TABLE [dbo].[fdRaPIdOtherPartyDetails](
	[rpdOPID] [bigint] IDENTITY(1,1) NOT NULL,
	[fileID] [bigint] NOT NULL,
	[rpdOPResponsible] [bit] NULL,
	[rpdOPType] [nvarchar](50) NULL,
	[rpdOPOther] [nvarchar](50) NULL,
	[rpdOPTitleType] [nvarchar](15) NULL,
	[rpdOPTitleTypeOther] [nvarchar](20) NULL,
	[rpdOPName] [nvarchar](50) NULL,
	[rpdOPMiddleName] [nvarchar](50) NULL,
	[rpdOPSurname] [nvarchar](50) NULL,
	[rpdOPOtherTitle] [nvarchar](50) NULL,
	[rpdOPAddressType] [nvarchar](50) NULL,
	[rpdOPHouseName] [nvarchar](50) NULL,
	[rpdOPHouseNumber] [nvarchar](50) NULL,
	[rpdOPStreet1] [nvarchar](50) NULL,
	[rpdOPStreet2] [nvarchar](50) NULL,
	[rpdOPDistrict] [nvarchar](50) NULL,
	[rpdOPCity] [nvarchar](50) NULL,
	[rpdOPCounty] [nvarchar](50) NULL,
	[rpdOPPostCode] [nvarchar](20) NULL,
	[rpdOPCountry] [nvarchar](50) NULL,
	[rpdOPVclReg] [nvarchar](15) NULL,
	[rpdOPVclMake] [nvarchar](25) NULL,
	[rpdOPVclModel] [nvarchar](30) NULL,
	[rpdOPVclColour] [nvarchar](25) NULL,
	[rpdOPInsCompanyName] [nvarchar](50) NULL,
	[rpdOPInsPolicyNumber] [nvarchar](50) NULL,
	[rpdOPInsAddressType] [nvarchar](50) NULL,
	[rpdOPInsHouseName] [nvarchar](50) NULL,
	[rpdOPInsHouseNumber] [nvarchar](50) NULL,
	[rpdOPInsStreet1] [nvarchar](50) NULL,
	[rpdOPInsStreet2] [nvarchar](50) NULL,
	[rpdOPInsDistrict] [nvarchar](50) NULL,
	[rpdOPInsCity] [nvarchar](50) NULL,
	[rpdOPInsCounty] [nvarchar](50) NULL,
	[rpdOPInsPostCode] [nvarchar](20) NULL,
	[rpdOPInsCountry] [nvarchar](50) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_fdRaPIdOtherPartyDetails_rowguid]  DEFAULT (newid()),
 CONSTRAINT [PK_fdRaPIdOtherPartyDetails] PRIMARY KEY CLUSTERED 
(
	[rpdOPID] ASC
)
)
