CREATE TABLE [dbo].[fdRaPIdSettlementDetails](
	[fileID] [bigint] NOT NULL,
	[rpdSetInterPackRequired] [bit] NULL,
	[rpdSetIntRequiredSent] [datetime] NULL,
	[rpdSetIntRequiredSentBy] [int] NULL,
	[rpdSetMorePaymentReq] [bit] NULL,
	[rpdSetIntMedicalRepCount] [int] NULL,
	[rpdSetIntValue] [decimal](18, 0) NULL,
	[rpdSetIntValueReasons] [nvarchar](500) NULL,
	[rpdSetIntSignatory] [nvarchar](15) NULL,
	[rpdSetIntRetSignedCopy] [bit] NULL,
	[rpdSetIntSubmitted] [datetime] NULL,
	[rpdSetIntSubmittedBy] [int] NULL,
	[rpdSetIntPayRecevd] [bit] NULL,
	[rpdSetIntPayRecevdSent] [datetime] NULL,
	[rpdSetIntPayRecevdSentBy] [int] NULL,
	[rpdSetIntPartial] [bit] NULL,
	[rpdSetIntPartialSent] [datetime] NULL,
	[rpdSetIntPartialSentBy] [int] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NULL CONSTRAINT [DF_fdRaPIdSettlementDetails_rowguid]  DEFAULT (newid()),
	rpdSetMedicalRepCount INT NULL,
	rpdSetAgreementData NVARCHAR(500) NULL,
	rpdSetSignatory NVARCHAR(15) NULL,
	rpdSetRetSignedCopy BIT NULL,
	rpdSetPackSubmitted DATETIME NULL,
	rpdSetPackSubmittedBy INT NULL,
	rpdSetConfRepSubmitted DATETIME NULL,
	rpdSetConfRepSubmittedBy INT NULL,
	rpdSetAgreeSubmitted DATETIME NULL,
	rpdSetAgreeSubmittedBy INT NULL,
	rpdSetAgreement BIT NULL,
	rpdSetLossesSeed INT NULL DEFAULT 0,
	rpdSetCOComments NVARCHAR(500) NULL,
	rpdSetCOGrossAmount DECIMAL(18, 0) NULL,
	rpdSetCOInterimPaymentAmt DECIMAL(18, 0) NULL,
	rpdSetCOSubmitted DATETIME NULL,
	rpdSetCOSubmittedBy INT NULL,
	rpdSetCONeeded BIT NULL,
	rpdSetCONeedSubmitted DATETIME NULL,
	rpdSetCONeedSubmittedBy INT NULL,
	rpdSetISPAckTOSubmit DATETIME NULL,
	rpdSetISPAckTOSubmitBy INT NULL,
	rpdSetISPAckRejSubmit DATETIME NULL,
	rpdSetISPAckRejSubmitBy INT NULL,
	rpdSetSPNotAgreedSubmit DATETIME NULL,
	rpdSetSPNotAgreedBy INT NULL,
	rpdSetSPAgreedSubmit DATETIME NULL,
	rpdSetSPAgreedBy INT NULL,
	rpdSetSPAddDamExist BIT NULL,
	rpdSetSPAddDamExistDate DATETIME NULL,
	rpdSetSPAddDamExistBy INT NULL, 
	rpdSetSPAddDamDecis BIT NULL,
	rpdSetSPAddDamDecisDate DATETIME NULL,
	rpdSetSPAddDamDecisBy INT NULL,
	rpdSetSPAddDamAllDate DATETIME NULL,
	rpdSetSPAddDamAllBy INT NULL,
	rpdSetSPAddDamAckDate DATETIME NULL,
	rpdSetSPAddDamAckBy INT NULL,
	rpdSetSPAddDamDecTODate DATETIME NULL,
	rpdSetSPAddDamDecTOBy INT NULL,
	rpdSetADSignatory NVARCHAR(15) NULL,
	rpdSetADRetSignedCopy BIT NULL,
	rpdSetADComments NVARCHAR(500) NULL,
	rpdSetADIntPaymentAmt MONEY NULL,
	rpdSetADGrossAmount MONEY NULL,
	rpdSetADSubmittedDate DATETIME NULL,
	rpdSetADSubmittedBy INT NULL,
	rpdSetISPAgreedAmount MONEY NULL,
	rpdSetISPAgreedAmtNotes NVARCHAR(1000) NULL,
	rpdSetISPReturn21Sub DATETIME NULL,
	rpdSetISPReturn21SubBy INT NULL,
	rpdSetISPRejectedReason NVARCHAR(1000) NULL,
	rpdSetIntSoftTissue bit NULL,
	rpdSetIntMedCoCase nvarchar(10) NULL,
	rpdSetSoftTissue bit NULL,
	rpdSetMedCoCase nvarchar(10) NULL,
 CONSTRAINT [PK_fdRaPIdSettlementDetails] PRIMARY KEY CLUSTERED 
(
	[fileID] ASC
)
)

