CREATE TABLE [dbo].[fdRaPIdMedicalDetails](
	[fileID] [bigint] NOT NULL,
	[rpdMedInjSoftTissue] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedInjSoftTissue]  DEFAULT (0),
	[rpdMedInjBoneInjury] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedInjBoneInjury]  DEFAULT (0),
	[rpdMedInjWhiplash] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedInjWhiplish]  DEFAULT (0),
	[rpdMedInjOther] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedInjOther]  DEFAULT (0),
	[rpdMedInjDescription] [nvarchar](500) NULL,
	[rpdMedTimeOffRequired] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedTimeOffRequired]  DEFAULT (0),
	[rpdMedTimeOffPeriod] [nvarchar](20) NULL,
	[rpdMedStillOffWork] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedStillOffWork]  DEFAULT (0),
	[rpdMedAttentionSeeking] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedAttentionSeeking]  DEFAULT (0),
	[rpdMedAttentionFirstDate] [datetime] NULL,
	[rpdMedHospitalAttendance] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedHospitalAttendance]  DEFAULT (0),
	[rpdMedOvernightDetention] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedOvernightDetention]  DEFAULT (0),
	[rpdMedHospitalDays] [int] NULL,
	[rpdMedHospitalType] [nvarchar](25) NULL,
	[rpdMedHospitalName] [nvarchar](75) NULL,
	[rpdMedHospitalPostCode] [nvarchar](15) NULL,
	[rpdMedHospitalAddLine1] [nvarchar](50) NULL,
	[rpdMedHospitalAddLine2] [nvarchar](50) NULL,
	[rpdMedHospitalAddLine3] [nvarchar](50) NULL,
	[rpdMedHospitalAddLine4] [nvarchar](50) NULL,
	[rpdMedRehabUndertaken] [nvarchar](25) NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedRehabUndertaken]  DEFAULT (0),
	[rpdMedRehabTreatment] [nvarchar](500) NULL,
	[rpdMedRehabNeeds] [bit] NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rpdMedRehabNeeds]  DEFAULT (0),
	[rpdMedRehabDetails] [nvarchar](500) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_fdRaPIdMedicalDetails_rowguid]  DEFAULT (newid()),
	[rpdMedHospital1] [bigint] NULL,
	[rpdMedHospital2] [bigint] NULL,
	[rpdMedHospital3] [bigint] NULL,
	[rpdMedHospital4] [bigint] NULL,
	[rpdMedHospitalType1] [nvarchar](25) NULL,
	[rpdMedHospitalType2] [nvarchar](25) NULL,
	[rpdMedHospitalType3] [nvarchar](25) NULL,
	[rpdMedHospitalType4] [nvarchar](25) NULL,
	rpdMedInjRespiratory BIT NULL,
	rpdMedInjDeafness BIT NULL,
	rpdMedInjVibration BIT NULL,
	rpdMedInjDermatitis BIT NULL,
 CONSTRAINT [PK_fdRaPIdMedicalDetails] PRIMARY KEY CLUSTERED 
(
	[fileID] ASC
)
)
