CREATE TABLE [dbo].[fdRaPIdClaimantDetails](
	[fileID] [bigint] NOT NULL,
	[rpdClmtName] [nvarchar](25) NULL,
	[rpdClmtSurname] [nvarchar](25) NULL,
	[rpdClmtOccupation] [nvarchar](50) NULL,
	[rpdClmtChildClaim] [bit] NULL CONSTRAINT [DF_fdRaPIdClaimantDetails_rpdClmtChildClaim]  DEFAULT (0),
	[rpdClmtNINComment] [nvarchar](500) NULL,
	[rpdClmtDateOfBirth] [datetime] NULL,
	[rpdClmtTitleType] [nvarchar](20) NULL,
	[rpdClmtCountry] [nvarchar](50) NULL,
	[rpdClmtCity] [nvarchar](50) NULL,
	[rpdClmtStreet1] [nvarchar](50) NULL,
	[rpdClmtAddressType] [nvarchar](30) NULL,
	[rpdClmtRepCompanyName] [nvarchar](75) NULL,
	[rpdClmtRepContName] [nvarchar](25) NULL,
	[rpdClmtRepContSurname] [nvarchar](25) NULL,
	[rpdClmtRepTelephone] [nvarchar](20) NULL,
	[rpdClmtRepRef] [nvarchar](50) NULL,
	[rpdClmtRepCountry] [nvarchar](50) NULL,
	[rpdClmtRepPostCode] [nvarchar](15) NULL,
	[rpdClmtRepCity] [nvarchar](50) NULL,
	[rpdClmtRepStreet1] [nvarchar](50) NULL,
	[rpdClmtRepHouseName] [nvarchar](50) NULL,
	[rpdClmtRepAddressType] [nvarchar](30) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL  CONSTRAINT [DF_fdRaPIdClaimant_rowguid]  DEFAULT (newid()),
	[rpdClmtRepContMidName] [nvarchar](25) NULL,
	[rpdClmtRepEmail] [nvarchar](100) NULL,
	[rpdClmtRepHouseNumber] [nvarchar](10) NULL,
	[rpdClmtRepStreet2] [nvarchar](50) NULL,
	[rpdClmtRepDistrict] [nvarchar](50) NULL,
	[rpdClmtRepCounty] [nvarchar](50) NULL,
	[rpdClmtNIN] [nvarchar](15) NULL,
	[rpdClmtMiddleName] [nvarchar](50) NULL,
	[rpdClmtTitleOther] [nvarchar](20) NULL,
	[rpdClmtVehicleReg] [nvarchar](15) NULL,
	[rpdClmtStreet2] [nvarchar](50) NULL,
	[rpdClmtDistrict] [nvarchar](50) NULL,
	[rpdClmtCounty] [nvarchar](50) NULL,
	[rpdClmtPostCode] [nvarchar](50) NULL,
	[rpdClmtHouseNumber] [nvarchar](10) NULL,
	[rpdClmtHouseName] [nvarchar](50) NULL,
	[rpdClmtEngineGUID] [nvarchar](50) NULL,
	[rpdClmtPhaseCacheID] [nvarchar](50) NULL,
	[rpdClmtPhaseCacheName] [nvarchar](250) NULL,
	[rpdClmtSignatory] [nvarchar](50) NULL,
	[rpdClmtRetainedCopy] [bit] NULL CONSTRAINT [DF_fdRaPIdClaimantDetails_rpdClmtRetainedCopy]  DEFAULT (0),
	[rpdClmtSubmitted] [datetime] NULL,
	[rpdClmtSubmittedBy] [bigint] NULL,
	[rpdClmtAppID] [nvarchar](50) NULL,
	rpdClmtPaymentReceived BIT NULL,
	rpdClmtPaymentRecSub DATETIME NULL,
	rpdClmtPaymentRecSubBy INT NULL,
	rpdClmtExitProcessCode NVARCHAR(15) NULL,
	rpdClmtExitProcessComments NVARCHAR(500) NULL,
	rpdClmtExitSubmitted DATETIME NULL,
	rpdClmtExitSubmittedBy INT NULL,
	rpdClmtExitAckSubmitted DATETIME NULL,
	rpdClmtExitAckSubmittedBy INT NULL,
	rpdClmtLiabDenSubmitted DATETIME NULL,
	rpdClmtLiabDenSubmitBy INT NULL,
	rpdClmtLiabAckCCSubmit DATETIME NULL,
	rpdClmtLiabAckCCSubmitBy INT NULL,
	rpdClmtLiabNegAckSubmit DATETIME NULL,
	rpdClmtLiabNegAckSubBy INT NULL,
	rpdClmtLiabDecTOSubmit DATETIME NULL,
	rpdClmtLiabDecTOSubmitBy INT NULL,
	rpdClmtVersionMajor INT NULL,
	rpdClmtVersionMinor INT NULL,
	rpdClmtClaimValue NVARCHAR(15) NULL,
	rpdClmtLiabAdmittedSub DATETIME NULL,
	rpdClmtLiabAdmittedSubBy INT NULL,
	rpdClmtClonedFromFileID BIGINT NULL,
	rpdClmtProcessType NVARCHAR(15) NULL,
	rpdClmtELPLType NVARCHAR(15) NULL,
	rpdClmtELPLNotification DATETIME NULL,
	rpdClmtELPLEmployPeriod NVARCHAR(500) NULL,
	rpdClmtELPLExposPeriod NVARCHAR(500) NULL, 
	rpdClmtAckRejSubmit DATETIME NULL,
	rpdClmtAckRejSubmitBy INT NULL,
	rpdClmtExitRejSub DATETIME NULL,
	rpdClmtExitRejSubBy INT NULL,
	rpdClmtAskCUEPIRef NVARCHAR(18) NULL,
	rpdClmtReferralSource NVARCHAR(15) NULL,
	rpdClmtRefSrcCmcName NVARCHAR(50) NULL,
	rpdClmtRefSrcMojCmcAuthNumber NVARCHAR(50) NULL,
	rpdClmtRefSrcWebsite NVARCHAR(50) NULL,
	rpdClmtRefSrcSource NVARCHAR(50) NULL,
	rpdClmtRepBranchName NVARCHAR(50) NULL,
    rpdClmtOICReferenceNumber NVARCHAR(14) NULL, 
    CONSTRAINT [PK_fdRaPIdClaimant] PRIMARY KEY CLUSTERED 
(
	[fileID] ASC
)
)
