CREATE TABLE [dbo].[fdRaPIdVehicleRepairDetails](
	[fileID] [bigint] NOT NULL,
	[rpdVclRepsClaimingDamage] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclRepsClaimingDamage]  DEFAULT ((0)),
	[rpdVclRepsOtherDetails] [nvarchar](500) NULL,
	[rpdVclRepsLocation] [nvarchar](200) NULL,
	[rpdVclRepsDefInsContDets] [nvarchar](200) NULL,
	[rpdVclRepsAltCompName] [nvarchar](75) NULL,
	[rpdVclRepsAltCompAddress] [nvarchar](200) NULL,
	[rpdVclRepsAltTelephone] [nvarchar](25) NULL,
	[rpdVclRepsAltReference] [nvarchar](50) NULL,
	[rpdVclAltEntitled] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclAltEntitled]  DEFAULT (0),
	[rpdVclAltProviderName] [nvarchar](75) NULL,
	[rpdVclAltProviderReference] [nvarchar](50) NULL,
	[rpdVclAltProviderAddress] [nvarchar](200) NULL,
	[rpdVclAltProviderStartDate] [datetime] NULL,
	[rpdVclAltProviderEndDate] [nvarchar](50) NULL,
	[rpdVclAltReg] [nvarchar](20) NULL,
	[rpdVclAltMake] [nvarchar](25) NULL,
	[rpdVclAltModel] [nvarchar](30) NULL,
	[rpdVclAltEngineSize] [nvarchar](10) NULL,
	[rpdVclAltColour] [nvarchar](20) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [DF_fdRaPIdVehicleRepairs_rowguid]  DEFAULT (newid()),
	[rpdVclRepsInsuranceDets] [nvarchar](50) NULL,
	[rpdVclRepsThrghClmtInsur] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclRepsThrghClmtInsur] DEFAULT(0),
	[rpdVclRepsThrghAltComp] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclRepsThrghAltComp]  DEFAULT (0),
	[rpdVclRepsTotalLoss] [nvarchar](25) NULL,
	[rpdVclRepsPosition] [nvarchar](50) NULL,
	[rpdVclRepsDefInsInspect] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclRepsDefInsInspect]  DEFAULT (0),
	[rpdVclAltProviderTel] [nvarchar](20) NULL,
	[rpdVclAltVclReqByClmt] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclAltVclReqByClmt]  DEFAULT (0),
	[rpdVclAltVclProvided] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclAltVclProvided]  DEFAULT (0),
	[rpdVclAltHireNeedOngoing] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclAltHireNeedOngoing]  DEFAULT (0),
	[rpdVclAltVclReqByCR] [bit] NULL CONSTRAINT [DF_fdRaPIdVehicleRepairDetails_rpdVclAltVclReqByCR]  DEFAULT (0),
	[rpdVclAltVclType] [nvarchar](25) NULL,
	[rpdVclAltVclContName] [nvarchar](50) NULL,
	[rpdVclAltVclContTel] [nvarchar](20) NULL,
 CONSTRAINT [PK_fdRaPIdVehicleRepairs] PRIMARY KEY CLUSTERED 
(
	[fileID] ASC
)
)
