
-- DBREGINFO IS A TABLE WHICH IS NOT REPLICATED.
-- YOU WILL NEED TO RUN THIS SCRIPT ON ANY MATTERSHPERE DATABASES WHICH WILL
-- HAVE THE AUDITING FUNCTIONALITY, IRRESPECTIVE OF WHETHER INSTALLED FROM A PACKAGE
-- OR BY REPLICATION.

exec fwbsAddColumn 
	@Tablename = 'dbRegInfo'
	, @ColumnName = 'regAuditingEnabled'
	, @columnDesc = 'BIT NULL'