//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace FWBS.OMS.OMSEXPORT.ClientService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClientServiceSoap", Namespace="http://cmsopen.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientDataBase))]
    public partial class ClientService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeDataCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadSingleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ClientService() {
            this.Url = "http://75sp1hf-expert-public.rm.na.aderant.com/cmsnet/FileOpening/FileOpeningWS/C" +
                "lientService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event InitializeDataCreateCompletedEventHandler InitializeDataCreateCompleted;
        
        /// <remarks/>
        public event GetDataCreateCompletedEventHandler GetDataCreateCompleted;
        
        /// <remarks/>
        public event GetDataUpdateCompletedEventHandler GetDataUpdateCompleted;
        
        /// <remarks/>
        public event ReadSingleCompletedEventHandler ReadSingleCompleted;
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Create", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Create(ClientDataCreate data) {
            object[] results = this.Invoke("Create", new object[] {
                        data});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(ClientDataCreate data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(ClientDataCreate data) {
            this.CreateAsync(data, null);
        }
        
        /// <remarks/>
        public void CreateAsync(ClientDataCreate data, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        data}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Update", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(int clientUno, ClientDataUpdate data) {
            this.Invoke("Update", new object[] {
                        clientUno,
                        data});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(int clientUno, ClientDataUpdate data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        clientUno,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateAsync(int clientUno, ClientDataUpdate data) {
            this.UpdateAsync(clientUno, data, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(int clientUno, ClientDataUpdate data, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        clientUno,
                        data}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Delete", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Delete(int clientUno, bool deleteChildren) {
            this.Invoke("Delete", new object[] {
                        clientUno,
                        deleteChildren});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(int clientUno, bool deleteChildren, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        clientUno,
                        deleteChildren}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDelete(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void DeleteAsync(int clientUno, bool deleteChildren) {
            this.DeleteAsync(clientUno, deleteChildren, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(int clientUno, bool deleteChildren, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        clientUno,
                        deleteChildren}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Initialize", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientData Initialize() {
            object[] results = this.Invoke("Initialize", new object[0]);
            return ((ClientData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInitialize(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Initialize", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public ClientData EndInitialize(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientData)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeAsync() {
            this.InitializeAsync(null);
        }
        
        /// <remarks/>
        public void InitializeAsync(object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[0], this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new InitializeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/InitializeDataCreate", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientDataCreate InitializeDataCreate() {
            object[] results = this.Invoke("InitializeDataCreate", new object[0]);
            return ((ClientDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInitializeDataCreate(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InitializeDataCreate", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public ClientDataCreate EndInitializeDataCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeDataCreateAsync() {
            this.InitializeDataCreateAsync(null);
        }
        
        /// <remarks/>
        public void InitializeDataCreateAsync(object userState) {
            if ((this.InitializeDataCreateOperationCompleted == null)) {
                this.InitializeDataCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeDataCreateOperationCompleted);
            }
            this.InvokeAsync("InitializeDataCreate", new object[0], this.InitializeDataCreateOperationCompleted, userState);
        }
        
        private void OnInitializeDataCreateOperationCompleted(object arg) {
            if ((this.InitializeDataCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeDataCreateCompleted(this, new InitializeDataCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/GetDataCreate", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientDataCreate GetDataCreate(ClientData data) {
            object[] results = this.Invoke("GetDataCreate", new object[] {
                        data});
            return ((ClientDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataCreate(ClientData data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataCreate", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public ClientDataCreate EndGetDataCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataCreateAsync(ClientData data) {
            this.GetDataCreateAsync(data, null);
        }
        
        /// <remarks/>
        public void GetDataCreateAsync(ClientData data, object userState) {
            if ((this.GetDataCreateOperationCompleted == null)) {
                this.GetDataCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataCreateOperationCompleted);
            }
            this.InvokeAsync("GetDataCreate", new object[] {
                        data}, this.GetDataCreateOperationCompleted, userState);
        }
        
        private void OnGetDataCreateOperationCompleted(object arg) {
            if ((this.GetDataCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCreateCompleted(this, new GetDataCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/GetDataUpdate", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientDataUpdate GetDataUpdate(ClientData data) {
            object[] results = this.Invoke("GetDataUpdate", new object[] {
                        data});
            return ((ClientDataUpdate)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataUpdate(ClientData data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataUpdate", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public ClientDataUpdate EndGetDataUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientDataUpdate)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUpdateAsync(ClientData data) {
            this.GetDataUpdateAsync(data, null);
        }
        
        /// <remarks/>
        public void GetDataUpdateAsync(ClientData data, object userState) {
            if ((this.GetDataUpdateOperationCompleted == null)) {
                this.GetDataUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUpdateOperationCompleted);
            }
            this.InvokeAsync("GetDataUpdate", new object[] {
                        data}, this.GetDataUpdateOperationCompleted, userState);
        }
        
        private void OnGetDataUpdateOperationCompleted(object arg) {
            if ((this.GetDataUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUpdateCompleted(this, new GetDataUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/ReadSingle", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientData ReadSingle(int clientUno) {
            object[] results = this.Invoke("ReadSingle", new object[] {
                        clientUno});
            return ((ClientData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadSingle(int clientUno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadSingle", new object[] {
                        clientUno}, callback, asyncState);
        }
        
        /// <remarks/>
        public ClientData EndReadSingle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientData)(results[0]));
        }
        
        /// <remarks/>
        public void ReadSingleAsync(int clientUno) {
            this.ReadSingleAsync(clientUno, null);
        }
        
        /// <remarks/>
        public void ReadSingleAsync(int clientUno, object userState) {
            if ((this.ReadSingleOperationCompleted == null)) {
                this.ReadSingleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadSingleOperationCompleted);
            }
            this.InvokeAsync("ReadSingle", new object[] {
                        clientUno}, this.ReadSingleOperationCompleted, userState);
        }
        
        private void OnReadSingleOperationCompleted(object arg) {
            if ((this.ReadSingleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadSingleCompleted(this, new ReadSingleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Read", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ClientData[] Read(string filter) {
            object[] results = this.Invoke("Read", new object[] {
                        filter});
            return ((ClientData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string filter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        filter}, callback, asyncState);
        }
        
        /// <remarks/>
        public ClientData[] EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ClientData[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string filter) {
            this.ReadAsync(filter, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string filter, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        filter}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class ClientDataCreate : ClientDataBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientDataUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientDataCreate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class ClientDataBase {
        
        private int addressUnoField;
        
        private System.DateTime apprDateField;
        
        private int apprEmplUnoField;
        
        private int assignEmplUnoField;
        
        private int billEmplUnoField;
        
        private string clientCodeField;
        
        private string clientNameField;
        
        private string clntCatCodeField;
        
        private string clntClassCodeField;
        
        private string clntTypeCodeField;
        
        private System.DateTime closeDateField;
        
        private int closeEmplUnoField;
        
        private System.DateTime confCheckDateField;
        
        private int confEmplUnoField;
        
        private string deptField;
        
        private string entityTypeField;
        
        private string hasSubsField;
        
        private string inactiveField;
        
        private int nameUnoField;
        
        private string notesTextField;
        
        private string offcField;
        
        private System.DateTime openDateField;
        
        private int openEmplUnoField;
        
        private int parentClntUnoField;
        
        private string profField;
        
        private System.DateTime prospectDateField;
        
        private System.DateTime purgeRevwDateField;
        
        private string reasonCloseField;
        
        private int respEmplUnoField;
        
        private string statusCodeField;
        
        private int yeMonthField;
        
        private string autoOadAlocField;
        
        private string autoOafAlocField;
        
        private string autoRaClientField;
        
        private string autoRaMatterField;
        
        private string autoRaPayorField;
        
        private string autoRetAlocField;
        
        private string autoUnapAlocField;
        
        private string billFreqCodeField;
        
        private string collectTextField;
        
        private string consolidateBlsField;
        
        private string creditHoldOkField;
        
        private decimal creditLimitField;
        
        private string currencyCodeField;
        
        private string disbClassField;
        
        private string disbJurOvrideField;
        
        private int diRateSetUnoField;
        
        private string genDisbFlagField;
        
        private double genDisbPcntField;
        
        private string jurisdicCodeField;
        
        private int optUnoField;
        
        private int payrClientUnoField;
        
        private string payDepositIntField;
        
        private double premDiscPcntField;
        
        private int prevRateLevelField;
        
        private int rateLevelField;
        
        private System.DateTime rateLevelDateField;
        
        private System.DateTime retnrEndDateField;
        
        private string taskSetCodeField;
        
        private string timeClassField;
        
        private string timeIncField;
        
        private string timeJurOvrideField;
        
        private string timeTypeCodeField;
        
        private int tmRateSetUnoField;
        
        private string useUnitsField;
        
        private string taskPlanCodeField;
        
        /// <remarks/>
        public int AddressUno {
            get {
                return this.addressUnoField;
            }
            set {
                this.addressUnoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ApprDate {
            get {
                return this.apprDateField;
            }
            set {
                this.apprDateField = value;
            }
        }
        
        /// <remarks/>
        public int ApprEmplUno {
            get {
                return this.apprEmplUnoField;
            }
            set {
                this.apprEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public int AssignEmplUno {
            get {
                return this.assignEmplUnoField;
            }
            set {
                this.assignEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public int BillEmplUno {
            get {
                return this.billEmplUnoField;
            }
            set {
                this.billEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientCode {
            get {
                return this.clientCodeField;
            }
            set {
                this.clientCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClntCatCode {
            get {
                return this.clntCatCodeField;
            }
            set {
                this.clntCatCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClntClassCode {
            get {
                return this.clntClassCodeField;
            }
            set {
                this.clntClassCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClntTypeCode {
            get {
                return this.clntTypeCodeField;
            }
            set {
                this.clntTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CloseDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
            }
        }
        
        /// <remarks/>
        public int CloseEmplUno {
            get {
                return this.closeEmplUnoField;
            }
            set {
                this.closeEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ConfCheckDate {
            get {
                return this.confCheckDateField;
            }
            set {
                this.confCheckDateField = value;
            }
        }
        
        /// <remarks/>
        public int ConfEmplUno {
            get {
                return this.confEmplUnoField;
            }
            set {
                this.confEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public string Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
            }
        }
        
        /// <remarks/>
        public string EntityType {
            get {
                return this.entityTypeField;
            }
            set {
                this.entityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string HasSubs {
            get {
                return this.hasSubsField;
            }
            set {
                this.hasSubsField = value;
            }
        }
        
        /// <remarks/>
        public string Inactive {
            get {
                return this.inactiveField;
            }
            set {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        public int NameUno {
            get {
                return this.nameUnoField;
            }
            set {
                this.nameUnoField = value;
            }
        }
        
        /// <remarks/>
        public string NotesText {
            get {
                return this.notesTextField;
            }
            set {
                this.notesTextField = value;
            }
        }
        
        /// <remarks/>
        public string Offc {
            get {
                return this.offcField;
            }
            set {
                this.offcField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OpenDate {
            get {
                return this.openDateField;
            }
            set {
                this.openDateField = value;
            }
        }
        
        /// <remarks/>
        public int OpenEmplUno {
            get {
                return this.openEmplUnoField;
            }
            set {
                this.openEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public int ParentClntUno {
            get {
                return this.parentClntUnoField;
            }
            set {
                this.parentClntUnoField = value;
            }
        }
        
        /// <remarks/>
        public string Prof {
            get {
                return this.profField;
            }
            set {
                this.profField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ProspectDate {
            get {
                return this.prospectDateField;
            }
            set {
                this.prospectDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PurgeRevwDate {
            get {
                return this.purgeRevwDateField;
            }
            set {
                this.purgeRevwDateField = value;
            }
        }
        
        /// <remarks/>
        public string ReasonClose {
            get {
                return this.reasonCloseField;
            }
            set {
                this.reasonCloseField = value;
            }
        }
        
        /// <remarks/>
        public int RespEmplUno {
            get {
                return this.respEmplUnoField;
            }
            set {
                this.respEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public int YeMonth {
            get {
                return this.yeMonthField;
            }
            set {
                this.yeMonthField = value;
            }
        }
        
        /// <remarks/>
        public string AutoOadAloc {
            get {
                return this.autoOadAlocField;
            }
            set {
                this.autoOadAlocField = value;
            }
        }
        
        /// <remarks/>
        public string AutoOafAloc {
            get {
                return this.autoOafAlocField;
            }
            set {
                this.autoOafAlocField = value;
            }
        }
        
        /// <remarks/>
        public string AutoRaClient {
            get {
                return this.autoRaClientField;
            }
            set {
                this.autoRaClientField = value;
            }
        }
        
        /// <remarks/>
        public string AutoRaMatter {
            get {
                return this.autoRaMatterField;
            }
            set {
                this.autoRaMatterField = value;
            }
        }
        
        /// <remarks/>
        public string AutoRaPayor {
            get {
                return this.autoRaPayorField;
            }
            set {
                this.autoRaPayorField = value;
            }
        }
        
        /// <remarks/>
        public string AutoRetAloc {
            get {
                return this.autoRetAlocField;
            }
            set {
                this.autoRetAlocField = value;
            }
        }
        
        /// <remarks/>
        public string AutoUnapAloc {
            get {
                return this.autoUnapAlocField;
            }
            set {
                this.autoUnapAlocField = value;
            }
        }
        
        /// <remarks/>
        public string BillFreqCode {
            get {
                return this.billFreqCodeField;
            }
            set {
                this.billFreqCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CollectText {
            get {
                return this.collectTextField;
            }
            set {
                this.collectTextField = value;
            }
        }
        
        /// <remarks/>
        public string ConsolidateBls {
            get {
                return this.consolidateBlsField;
            }
            set {
                this.consolidateBlsField = value;
            }
        }
        
        /// <remarks/>
        public string CreditHoldOk {
            get {
                return this.creditHoldOkField;
            }
            set {
                this.creditHoldOkField = value;
            }
        }
        
        /// <remarks/>
        public decimal CreditLimit {
            get {
                return this.creditLimitField;
            }
            set {
                this.creditLimitField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DisbClass {
            get {
                return this.disbClassField;
            }
            set {
                this.disbClassField = value;
            }
        }
        
        /// <remarks/>
        public string DisbJurOvride {
            get {
                return this.disbJurOvrideField;
            }
            set {
                this.disbJurOvrideField = value;
            }
        }
        
        /// <remarks/>
        public int DiRateSetUno {
            get {
                return this.diRateSetUnoField;
            }
            set {
                this.diRateSetUnoField = value;
            }
        }
        
        /// <remarks/>
        public string GenDisbFlag {
            get {
                return this.genDisbFlagField;
            }
            set {
                this.genDisbFlagField = value;
            }
        }
        
        /// <remarks/>
        public double GenDisbPcnt {
            get {
                return this.genDisbPcntField;
            }
            set {
                this.genDisbPcntField = value;
            }
        }
        
        /// <remarks/>
        public string JurisdicCode {
            get {
                return this.jurisdicCodeField;
            }
            set {
                this.jurisdicCodeField = value;
            }
        }
        
        /// <remarks/>
        public int OptUno {
            get {
                return this.optUnoField;
            }
            set {
                this.optUnoField = value;
            }
        }
        
        /// <remarks/>
        public int PayrClientUno {
            get {
                return this.payrClientUnoField;
            }
            set {
                this.payrClientUnoField = value;
            }
        }
        
        /// <remarks/>
        public string PayDepositInt {
            get {
                return this.payDepositIntField;
            }
            set {
                this.payDepositIntField = value;
            }
        }
        
        /// <remarks/>
        public double PremDiscPcnt {
            get {
                return this.premDiscPcntField;
            }
            set {
                this.premDiscPcntField = value;
            }
        }
        
        /// <remarks/>
        public int PrevRateLevel {
            get {
                return this.prevRateLevelField;
            }
            set {
                this.prevRateLevelField = value;
            }
        }
        
        /// <remarks/>
        public int RateLevel {
            get {
                return this.rateLevelField;
            }
            set {
                this.rateLevelField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RateLevelDate {
            get {
                return this.rateLevelDateField;
            }
            set {
                this.rateLevelDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RetnrEndDate {
            get {
                return this.retnrEndDateField;
            }
            set {
                this.retnrEndDateField = value;
            }
        }
        
        /// <remarks/>
        public string TaskSetCode {
            get {
                return this.taskSetCodeField;
            }
            set {
                this.taskSetCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TimeClass {
            get {
                return this.timeClassField;
            }
            set {
                this.timeClassField = value;
            }
        }
        
        /// <remarks/>
        public string TimeInc {
            get {
                return this.timeIncField;
            }
            set {
                this.timeIncField = value;
            }
        }
        
        /// <remarks/>
        public string TimeJurOvride {
            get {
                return this.timeJurOvrideField;
            }
            set {
                this.timeJurOvrideField = value;
            }
        }
        
        /// <remarks/>
        public string TimeTypeCode {
            get {
                return this.timeTypeCodeField;
            }
            set {
                this.timeTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public int TmRateSetUno {
            get {
                return this.tmRateSetUnoField;
            }
            set {
                this.tmRateSetUnoField = value;
            }
        }
        
        /// <remarks/>
        public string UseUnits {
            get {
                return this.useUnitsField;
            }
            set {
                this.useUnitsField = value;
            }
        }
        
        /// <remarks/>
        public string TaskPlanCode {
            get {
                return this.taskPlanCodeField;
            }
            set {
                this.taskPlanCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class ClientData : ClientDataBase {
        
        private int clientUnoField;
        
        private System.DateTime lastModifiedField;
        
        private int clientNumberField;
        
        private System.DateTime editDateField;
        
        private int nextMatNoField;
        
        private string roundTypeField;
        
        /// <remarks/>
        public int ClientUno {
            get {
                return this.clientUnoField;
            }
            set {
                this.clientUnoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
        
        /// <remarks/>
        public int ClientNumber {
            get {
                return this.clientNumberField;
            }
            set {
                this.clientNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EditDate {
            get {
                return this.editDateField;
            }
            set {
                this.editDateField = value;
            }
        }
        
        /// <remarks/>
        public int NextMatNo {
            get {
                return this.nextMatNoField;
            }
            set {
                this.nextMatNoField = value;
            }
        }
        
        /// <remarks/>
        public string RoundType {
            get {
                return this.roundTypeField;
            }
            set {
                this.roundTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class ClientDataUpdate : ClientDataBase {
        
        private string roundTypeField;
        
        /// <remarks/>
        public string RoundType {
            get {
                return this.roundTypeField;
            }
            set {
                this.roundTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InitializeCompletedEventHandler(object sender, InitializeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InitializeDataCreateCompletedEventHandler(object sender, InitializeDataCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeDataCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeDataCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientDataCreate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientDataCreate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDataCreateCompletedEventHandler(object sender, GetDataCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientDataCreate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientDataCreate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDataUpdateCompletedEventHandler(object sender, GetDataUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientDataUpdate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientDataUpdate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadSingleCompletedEventHandler(object sender, ReadSingleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadSingleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadSingleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ClientData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientData[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591