
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'OMSRole' AND type = 'R')
	CREATE ROLE [OMSRole] AUTHORIZATION [dbo]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
