CREATE PROCEDURE dbo.SCHFILRISKCFG
(
	@ORDERBY NVARCHAR(MAX) = NULL
)  
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

DECLARE @SELECT NVARCHAR(MAX)

SET @SELECT = N'
SELECT * 
FROM dbriskconfig
'

IF @ORDERBY IS NULL
	SET  @SELECT =  @SELECT + N'ORDER BY riskId'
ELSE 
	IF @ORDERBY NOT LIKE '%riskId%'
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY  + N', riskId'
	ELSE 
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY

EXEC sp_executesql @SELECT

GO

GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFILRISKCFG] TO [OMSRole]
    AS [dbo];


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFILRISKCFG] TO [OMSAdminRole]
    AS [dbo];
