CREATE PROCEDURE dbo.SCHFEEDUETODAY
(
	@FEEUSRID INT
	, @ORDERBY NVARCHAR(MAX) = NULL
)

AS
SET NOCOUNT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

DECLARE @SELECT NVARCHAR(MAX)

--- SET THE SELECT CLAUSE
SET @SELECT = N' WITH Res AS
(
SELECT 
	F.fileID
	, dbo.GetFileRef(CL.clNo, F.fileNo) AS fileRef
	, CL.CLName
	, F.fileDesc
	, O.MSNextDueDate 
FROM dbClient CL
	INNER JOIN dbFile F ON F.CLID = CL.CLID 
	INNER JOIN dbo.dbMSData_OMS2K O ON F.fileID = O.fileid
WHERE F.filePrincipleID = @FEEUSRID 
	AND O.MSNextDueDate < GETDATE() 
)
SELECT * 
FROM Res
'
IF @ORDERBY IS NULL
	SET  @SELECT =  @SELECT + N'ORDER BY fileID'
ELSE 
	IF @ORDERBY NOT LIKE '%fileID%'
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY  + N', fileID'
	ELSE 
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY

EXEC sp_executesql @SELECT, N'@FEEUSRID INT', @FEEUSRID

GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFEEDUETODAY] TO [OMSRole]
    AS [dbo];


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFEEDUETODAY] TO [OMSAdminRole]
    AS [dbo];
