CREATE PROCEDURE dbo.SCHFILTRANSLIST
(
	@UI uUICultureInfo = '{default}'
	, @CLID BIGINT
	, @LIVEONLY BIT = 0
	, @ORDERBY NVARCHAR(MAX) = NULL
)  
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

DECLARE @SELECT NVARCHAR(MAX)


SET @SELECT = N'
WITH Res AS
(
SELECT F.FILETYPE
	, F.FILEID
	, F.FILEFUNDCODE 
	, F.CLID 
	, F.FILEDESC 
	, F.CREATED
	, F.FILESTATUS
	, F.FILENO
	, F.FILEACCCODE
	, F.FILECREDITLIMIT
	, F.FILECURISOCODE
	, Y.CDDESC AS FUNDTYPEDESC
	, Z.CDDESC AS FILETYPEDESC
	, V.CDDESC AS FILESTATUSDESC
	, F.FILENO + '' : '' + F.FILEDESC AS [FILEJOINTDESC]
	, F.FILEDEPARTMENT
	, F.FILEMANAGERID
	, F.FILERESPONSIBLEID
	, F.FILEPRINCIPLEID
	, F.FILETEAM
	, F.FILENICKNAME
	, F.PHID
	, F.FILEALERTMESSAGE
	, F.FILEALERTLEVEL
	, U.USRFULLNAME
	, D.CDDESC AS DEPARTMENT
FROM dbo.dbFile F
	INNER JOIN dbo.dbUser U ON U.usrID = F.filePrincipleID
	LEFT JOIN dbo.GetCodeLookupDescription(''FUNDTYPE'', @UI) Y ON Y.cdCode = F.fileFundCode 
	LEFT JOIN dbo.GetCodeLookupDescription(''FILETYPE'', @UI) Z ON Z.cdCode = F.fileType 
	LEFT JOIN dbo.GetCodeLookupDescription(''FILESTATUS'', @UI) V ON V.cdCode = F.fileStatus
	LEFT JOIN dbo.GetCodeLookupDescription(''DEPT'', @UI) D ON D.cdCode = F.fileDepartment 
WHERE F.clID = @CLID 
	AND F.fileStatus LIKE 
		CASE @LIVEONLY 
			WHEN 1 THEN ''%LIVE%''
			ELSE ''%''
		END
)
SELECT *
FROM Res
'

IF @ORDERBY IS NULL
	SET  @SELECT =  @SELECT + N'ORDER BY Created DESC'
ELSE 
	IF @ORDERBY NOT LIKE '%Created%'
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY  + N', Created DESC'
	ELSE 
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY

EXEC sp_executesql @SELECT, N'@UI uUICultureInfo, @CLID BIGINT, @LIVEONLY BIT', @UI, @CLID, @LIVEONLY

GO

GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFILTRANSLIST] TO [OMSRole]
    AS [dbo];


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFILTRANSLIST] TO [OMSAdminRole]
    AS [dbo];