CREATE PROCEDURE dbo.SCHFILPHASES
(
	@FILEID BIGINT 
	, @ORDERBY NVARCHAR(MAX) = NULL
)  
AS
SET TRAN ISOLATION LEVEL READ UNCOMMITTED
SET NOCOUNT ON

DECLARE @SELECT NVARCHAR(MAX)

SET @SELECT = N'
SELECT * 
FROM dbo.dbfilephase 
WHERE fileid = @FILEID
'

IF @ORDERBY IS NULL
	SET  @SELECT =  @SELECT + N'ORDER BY Created DESC'
ELSE 
	IF @ORDERBY NOT LIKE '%Created%'
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY  + N', Created DESC'
	ELSE 
		SET  @SELECT =  @SELECT + N'ORDER BY ' + @ORDERBY

EXEC sp_executesql @SELECT, N'@FILEID BIGINT', @FILEID


GO

GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFILPHASES] TO [OMSRole]
    AS [dbo];


GO
GRANT EXECUTE
    ON OBJECT::[dbo].[SCHFILPHASES] TO [OMSAdminRole]
    AS [dbo];
