
CREATE PROC sprTimeActivities2 ( @ACTIVITYGROUPENABLED BIT = 0 )
AS
--RETURNS 3 COLUMNS BEING ACTCODE , DESCRIPTION , FILETIMEACTIVITYGROUP
--CUSTOM VERSIONS SHOULD BE IN LINE WITH CORRECT DATA FOR TIME RECORDING INCLUDING THE TIMECLOCKS APPLICATION
--IT IS PLANNED THAT IN FUTURE RELEASE OF MC MERGE THIS INTO TO SPRTIMEACTIVITIES

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sprTimeActivities_CUSTOM]') AND type in (N'P', N'PC'))
BEGIN 
	EXEC sprTimeActivities2_CUSTOM @ACTIVITYGROUPENABLED
	RETURN
END

--STANDARD BEHAVIOUR
IF @ACTIVITYGROUPENABLED = 1
BEGIN
	SELECT NULL AS ACTCODE , DBO.GETCODELOOKUPDESC ( 'RESOURCE' , 'RESNOTSET' , '') AS [DESCRIPTION] , NULL AS FILETIMEACTIVITYGROUP UNION 
	SELECT DBACTIVITIES.ACTCODE , COALESCE(CL1.cdDesc, '~' + NULLIF(DBACTIVITIES.ACTCODE, '') + '~') AS [DESCRIPTION] , FILETIMEACTIVITYGROUP 
	FROM DBACTIVITIES INNER JOIN DBACTIVITYTOFILETIMEACTIVITYGROUP AFG ON AFG.ACTCODE = DBACTIVITIES.ACTCODE 
	LEFT JOIN dbo.GetCodeLookupDescription ( 'TIMEACTCODE', '' ) CL1 ON CL1.[cdCode] =  DBACTIVITIES.ACTCODE
	WHERE ACTACTIVE = 1 AND AFG.ACTIVE = 1 ORDER BY [DESCRIPTION]
END
ELSE
BEGIN 
	SELECT NULL AS ACTCODE , DBO.GETCODELOOKUPDESC ( 'RESOURCE' , 'RESNOTSET' , '') AS [DESCRIPTION] , NULL AS FILETIMEACTIVITYGROUP UNION 
	SELECT DBACTIVITIES.ACTCODE , COALESCE(CL1.cdDesc, '~' + NULLIF(DBACTIVITIES.ACTCODE, '') + '~') AS [DESCRIPTION] , NULL AS FILETIMEACTIVITYGROUP 
	FROM DBACTIVITIES 
	LEFT JOIN dbo.GetCodeLookupDescription ( 'TIMEACTCODE', '' ) CL1 ON CL1.[cdCode] =  DBACTIVITIES.ACTCODE
	WHERE ACTACTIVE = 1 ORDER BY [DESCRIPTION]
END
