CREATE PROCEDURE [dbo].[srepFeeMilestoneMgr]
(
	@UI uUICultureInfo='{default}'
	, @USER bigint = null
	, @STARTDATE datetime = null
	, @ENDDATE datetime = null
 )

AS 

--RN & PC 20180615: Modified for v8 30 milestones

declare @Select nvarchar(3000)
declare @Where nvarchar(500)


--- SET THE SELECT STATEMENT
SET @Select = N'
SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 
SELECT     
	CL.clNo, 
	CL.clName, 
	CASE
		WHEN A.addLine1 IS NOT NULL THEN A.addLine1
		ELSE A1.addLine1
	END AS addLine1,
	F.fileNo, 
	replace(F.fileDesc, char(13) + char(10), '''') as fileDesc, 
	MSD.MSNextDueDate, 
	MSC.MSDescription, 
	U.usrFullName, 
	DATEDIFF(day,MSD.MSNextDueDate, GetUtcDate()) AS DATEDIFFERENCE,
	CASE 
		WHEN DATEDIFF(day,MSD.MSNextDueDate,GetUtcDate()) < 0 THEN N''Due in''
		WHEN DATEDIFF(day,MSD.MSNextDueDate,GetUtcDate()) > 0 THEN N''Days Overdue''
		ELSE N''Due Today''
	END AS DateDiffDesc, 
	F.fileType, 
	CASE 
		WHEN MSD.MSNEXTDUESTAGE = 1 THEN MSC.MSSTAGE1DESC 
		WHEN MSD.MSNEXTDUESTAGE = 2 THEN MSC.MSSTAGE2DESC 
		WHEN MSD.MSNEXTDUESTAGE = 3 THEN MSC.MSSTAGE3DESC 
		WHEN MSD.MSNEXTDUESTAGE = 4 THEN MSC.MSSTAGE4DESC 
		WHEN MSD.MSNEXTDUESTAGE = 5 THEN MSC.MSSTAGE5DESC 
		WHEN MSD.MSNEXTDUESTAGE = 6 THEN MSC.MSSTAGE6DESC 
		WHEN MSD.MSNEXTDUESTAGE = 7 THEN MSC.MSSTAGE7DESC 
		WHEN MSD.MSNEXTDUESTAGE = 8 THEN MSC.MSSTAGE8DESC 
		WHEN MSD.MSNEXTDUESTAGE = 9 THEN MSC.MSSTAGE9DESC 
		WHEN MSD.MSNEXTDUESTAGE = 10 THEN MSC.MSSTAGE10DESC 
		WHEN MSD.MSNEXTDUESTAGE = 11 THEN MSC.MSSTAGE11DESC 
		WHEN MSD.MSNEXTDUESTAGE = 12 THEN MSC.MSSTAGE12DESC 
		WHEN MSD.MSNEXTDUESTAGE = 13 THEN MSC.MSSTAGE13DESC 
		WHEN MSD.MSNEXTDUESTAGE = 14 THEN MSC.MSSTAGE14DESC 
		WHEN MSD.MSNEXTDUESTAGE = 15 THEN MSC.MSSTAGE15DESC 
		WHEN MSD.MSNEXTDUESTAGE = 16 THEN MSC.MSSTAGE16DESC 
		WHEN MSD.MSNEXTDUESTAGE = 17 THEN MSC.MSSTAGE17DESC
		WHEN MSD.MSNEXTDUESTAGE = 18 THEN MSC.MSSTAGE18DESC 
		WHEN MSD.MSNEXTDUESTAGE = 19 THEN MSC.MSSTAGE19DESC 
		WHEN MSD.MSNEXTDUESTAGE = 20 THEN MSC.MSSTAGE20DESC 
		WHEN MSD.MSNEXTDUESTAGE = 21 THEN MSC.MSSTAGE21DESC 
		WHEN MSD.MSNEXTDUESTAGE = 22 THEN MSC.MSSTAGE22DESC 
		WHEN MSD.MSNEXTDUESTAGE = 23 THEN MSC.MSSTAGE23DESC 
		WHEN MSD.MSNEXTDUESTAGE = 24 THEN MSC.MSSTAGE24DESC 
		WHEN MSD.MSNEXTDUESTAGE = 25 THEN MSC.MSSTAGE25DESC 
		WHEN MSD.MSNEXTDUESTAGE = 26 THEN MSC.MSSTAGE26DESC 
		WHEN MSD.MSNEXTDUESTAGE = 27 THEN MSC.MSSTAGE27DESC 
		WHEN MSD.MSNEXTDUESTAGE = 28 THEN MSC.MSSTAGE28DESC
		WHEN MSD.MSNEXTDUESTAGE = 29 THEN MSC.MSSTAGE29DESC 
		WHEN MSD.MSNEXTDUESTAGE = 30 THEN MSC.MSSTAGE30DESC 
		ELSE N''OTHER!''
	END AS StageDesc, 
	MSD.MSNextDueStage, 
	U.usrinits
FROM         
	dbo.dbMSData_OMS2K MSD
INNER JOIN
	dbo.dbMSConfig_OMS2K MSC ON MSD.MSCode = MSC.MSCode 
INNER JOIN
	dbo.dbFile F ON MSD.fileID = F.fileID 
INNER JOIN
	dbo.dbClient CL ON F.clId = CL.clId
INNER JOIN
	dbo.dbContact CN ON CL.clDefaultContact = CN.contID
LEFT OUTER JOIN
	dbo.dbAddress A ON CL.clDefaultAddress = A.addID
LEFT OUTER JOIN
	dbo.dbAddress A1 ON CN.contDefaultAddress = A1.addID
INNER JOIN
	dbo.dbUser U ON F.filePrincipleID = U.usrID '

---- Build Where Clause
SET @WHERE = ''

--- @USER clause
IF(@USER IS NOT NULL)
BEGIN
	 set @where = @where + ' U.usrID = @USER '
END

IF(@STARTDATE IS NOT NULL)
BEGIN
   IF @where <> '' 
	BEGIN
		 set @where = @where + ' AND (MSD.MSNextDueDate >= @STARTDATE AND MSD.MSNextDueDate < @ENDDATE) '
	END
   ELSE
	BEGIN
		 set @where = @where + ' (MSD.MSNextDueDate >= @STARTDATE AND MSD.MSNextDueDate < @ENDDATE) '
	END
END

--- Add Where Clause
if @where <> ''
BEGIN
	set @where = N' WHERE ' + @where
END

declare @sql nvarchar(4000)
--- Add Statements together
set @sql = Rtrim(@select) + Rtrim(@where)

--- Debug Print
 print @sql


exec sp_executesql @sql,
N'
	@UI nvarchar(10)
	, @USER BigInt
	, @STARTDATE datetime
	, @ENDDATE datetime'
	, @UI
	, @USER
	, @STARTDATE
	, @ENDDATE

GO