--HELPER SCRIPT TO HELP POPULATE MATTERSPHERE DATA

--ASSUMES LINK ON ACODE TO ACTACCCODE, BUT POPULATES ACTCODE SO CHECK FOR PK BREAKS

INSERT INTO DBACTIVITIES
(
	ACTCODE
	, ACTACCCODE
	, ACTCHARGEABLE
	, ACTFIXEDRATELEGAL
	, ACTTEMPLATEMATCH
	, ACTLEGALAIDFILTER
	, ACTFIXEDVALUE
	, ACTACTIVE
	, ACTCURISOCODE
	, ACTFILETYPECODE
)
SELECT 
	SON_DB.DBO.ACTCODE.ACODE		
	, SON_DB.DBO.ACTCODE.ACODE		--KEEP IN SYNC WITH ACTCODE IF POSSIBLE
	, 1								--ALWAYS 1
	, 0
	, NULL
	, NULL
	, NULL							--ENTERPRISE CALCULATES ALL VALUES
	, CASE SON_DB.DBO.ACTCODE.ACTIVE
		WHEN 'Y' THEN 1
		ELSE 0
	END AS ACTACTIVE
	, NULL
	, NULL
		
FROM 
	SON_DB.DBO.ACTCODE
LEFT JOIN
	DBACTIVITIES ON DBACTIVITIES.ACTACCCODE = SON_DB.DBO.ACTCODE.ACODE
WHERE
	DBACTIVITIES.ACTCODE IS NULL
	AND ISNULL(SON_DB.DBO.ACTCODE.aratescale , 'N' ) = 'N'  

--NOW THE CODELOOKUPS
INSERT INTO DBCODELOOKUP
( 
	CDCODE
	, CDTYPE
	, CDDESC
)
SELECT
	SON_DB.DBO.ACTCODE.ACODE
	, 'TIMEACTCODE'
	, ISNULL ( ACTNAME , ACODE )
FROM
	SON_DB.DBO.ACTCODE
LEFT JOIN
	DBCODELOOKUP ON CDTYPE = 'TIMEACTCODE' AND CDCODE = SON_DB.DBO.ACTCODE.ACODE
WHERE
	DBCODELOOKUP.CDID IS NULL	
	AND ISNULL(SON_DB.DBO.ACTCODE.aratescale , 'N' ) = 'N'