--HELPER SCRIPT TO HELP POPULATE MATTERSPHERE DATA

--* REPLACE SON_DB WITH THE ENTERPRISE DATABASE NAME! *

--ASSUMES LINK ON DELCODE (ENTERPRISE) TO DEPTACCCODE, AND POPULATES DEPTACCCODE (BOTH ARE 10 CHAR MAX.)



-- 1. CREATE THE DEPARTMENTS
INSERT INTO DBDEPARTMENT
(
	DEPTCODE
	,DEPTACTIVE
	,DEPTACCCODE
)
SELECT DISTINCT 
	DEPTLAB.DELCODE 
	,CASE DEPTLAB.ACTIVE 
		WHEN 'Y' THEN 1
		ELSE 0 END AS DEPTACTIVE
	,DEPTLAB.DELCODE 
FROM 
	[SON_DB].[DBO].[DEPTLAB] 
LEFT JOIN
	[DBO].[DBDEPARTMENT] DEPT ON DEPT.DEPTACCCODE = [SON_DB].[DBO].[DEPTLAB].DELCODE
WHERE 
	 DEPT.DEPTACCCODE IS NULL

	
-- 2. INSERT THE CODELOOKUPS
INSERT INTO DBCODELOOKUP
( 
	CDCODE
	, CDTYPE
	, CDDESC
)
SELECT
	DEPTLAB.DELCODE 
	, 'DEPT'
	, DEPTLAB.HEAD1
FROM
	[SON_DB].[DBO].[DEPTLAB] 
LEFT JOIN
	DBCODELOOKUP ON CDTYPE = 'DEPT' AND CDCODE = [SON_DB].[DBO].[DEPTLAB].DELCODE 
WHERE
	DBCODELOOKUP.CDID IS NULL