-- * STATES *
-- USE THIS SCRIPT TO CREATE THE STATES IN MATTERSPHERE
-- ENSURE THAT THE COUNTRY SCRIPT HAS BEEN RUN ALREADY (!)

-- RUN ON THE MATTERSPHERE DATABASE


-- 1) CREATE 'STATES' CODELOOKUP GROUP
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'OMS' AND CDCODE = 'STATES' AND CDGROUP = 1 )
INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC , CDGROUP ) VALUES ( 'OMS' , 'STATES' , 'States' , 1 )

-- IDs are static (created from Default_Country initial script)
DECLARE
    @US  INT = 224,
    @CA  INT = 38,
    @AU  INT = 13
-- 2) CREATE THE 'STATES' SUBFOLDER CODELOOKUP GROUPS
-- US      United States of America
IF NOT EXISTS (SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'STATES' AND CDCODE = ( SELECT CONVERT ( NVARCHAR ( 15 ) , @US ) ))
                INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC , CDGROUP ) SELECT 'STATES' , @US , 'United States of America' , 1
-- CA      Canada
IF NOT EXISTS (SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'STATES' AND CDCODE = ( SELECT CONVERT ( NVARCHAR ( 15 ) , @CA ) ))
                INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC , CDGROUP ) SELECT 'STATES' , @CA , 'Canada' , 1
-- AU      Australia
IF NOT EXISTS (SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'STATES' AND CDCODE = ( SELECT CONVERT ( NVARCHAR ( 15 ) , @AU ) ))
                INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC , CDGROUP ) SELECT 'STATES' , @AU , 'Australia' , 1


-- 3) CREATE STATE ENTRIES IN CORRECT STATE SUBFOLDERS
-- US      United States of America
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'AL') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'AL','AL'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'AK') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'AK','AK'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'AS') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'AS','AS'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'AR') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'AR','AR'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'CA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'CA','CA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'CO') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'CO','CO'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'CT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'CT','CT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'DE') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'DE','DE'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'FL') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'FL','FL'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'DC') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'DC','DC'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'HI') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'HI','HI'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'ID') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'ID','ID'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'GU') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'GU','GU'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'IN') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'IN','IN'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'IA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'IA','IA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'KS') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'KS','KS'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'KY') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'KY','KY'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'LA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'LA','LA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'ME') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'ME','ME'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MD') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MD','MD'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MA','MA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MI') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MI','MI'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MN') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MN','MN'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MS') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MS','MS'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MO') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MO','MO'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MT','MT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NE') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NE','NE'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NV') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NV','NV'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NH') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NH','NH'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NJ') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NJ','NJ'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NM') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NM','NM'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NY') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NY','NY'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'NC') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'NC','NC'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'ND') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'ND','ND'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'OH') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'OH','OH'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'OK') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'OK','OK'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'OR') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'OR','OR'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'MP') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'MP','MP'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'RI') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'RI','RI'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'SC') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'SC','SC'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'SD') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'SD','SD'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'TN') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'TN','TN'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'PR') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'PR','PR'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'UT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'UT','UT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'VT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'VT','VT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'VA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'VA','VA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'WA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'WA','WA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'WV') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'WV','WV'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'VI') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'VI','VI'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @US ) AND CDCODE = 'WY') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @US , 'WY','WY'
-- CA      Canada
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'ON') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'ON','ON'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'QC') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'QC','QC'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'NS') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'NS','NS'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'NB') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'NB','NB'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'MB') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'MB','MB'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'BC') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'BC','BC'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'PE') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'PE','PE'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'SK') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'SK','SK'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'AB') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'AB','AB'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @CA ) AND CDCODE = 'NL') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @CA , 'NL','NL'
-- AU      Australia
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'ACT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'ACT','ACT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'JBT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'JBT','JBT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'NSW') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'NSW','NSW'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'NT') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'NT','NT'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'QLD') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'QLD','QLD'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'SA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'SA','SA'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'TAS') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'TAS','TAS'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'VIC') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'VIC','VIC'
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = CONVERT ( NVARCHAR ( 15 ) , @AU ) AND CDCODE = 'WA') INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC ) SELECT @AU , 'WA','WA'