//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace FWBS.OMS.OMSEXPORT.BillGroupService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BillGroupServiceSoap", Namespace="http://cmsopen.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BillGroupDataBase))]
    public partial class BillGroupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializeDataCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataCreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadSingleOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BillGroupService() {
            this.Url = "http://75sp1hf-expert-public.rm.na.aderant.com/cmsnet/FileOpening/FileOpeningWS/B" +
                "illGroupService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event InitializeCompletedEventHandler InitializeCompleted;
        
        /// <remarks/>
        public event InitializeDataCreateCompletedEventHandler InitializeDataCreateCompleted;
        
        /// <remarks/>
        public event GetDataCreateCompletedEventHandler GetDataCreateCompleted;
        
        /// <remarks/>
        public event GetDataUpdateCompletedEventHandler GetDataUpdateCompleted;
        
        /// <remarks/>
        public event ReadSingleCompletedEventHandler ReadSingleCompleted;
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Create", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Create(BillGroupDataCreate data) {
            object[] results = this.Invoke("Create", new object[] {
                        data});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreate(BillGroupDataCreate data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Create", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(BillGroupDataCreate data) {
            this.CreateAsync(data, null);
        }
        
        /// <remarks/>
        public void CreateAsync(BillGroupDataCreate data, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        data}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Update", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(int billGrpUno, BillGroupDataUpdate data) {
            this.Invoke("Update", new object[] {
                        billGrpUno,
                        data});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdate(int billGrpUno, BillGroupDataUpdate data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Update", new object[] {
                        billGrpUno,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdate(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void UpdateAsync(int billGrpUno, BillGroupDataUpdate data) {
            this.UpdateAsync(billGrpUno, data, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(int billGrpUno, BillGroupDataUpdate data, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        billGrpUno,
                        data}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Delete", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Delete(int billGrpUno) {
            this.Invoke("Delete", new object[] {
                        billGrpUno});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDelete(int billGrpUno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Delete", new object[] {
                        billGrpUno}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndDelete(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void DeleteAsync(int billGrpUno) {
            this.DeleteAsync(billGrpUno, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(int billGrpUno, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        billGrpUno}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Initialize", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillGroupData Initialize() {
            object[] results = this.Invoke("Initialize", new object[0]);
            return ((BillGroupData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInitialize(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Initialize", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public BillGroupData EndInitialize(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillGroupData)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeAsync() {
            this.InitializeAsync(null);
        }
        
        /// <remarks/>
        public void InitializeAsync(object userState) {
            if ((this.InitializeOperationCompleted == null)) {
                this.InitializeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeOperationCompleted);
            }
            this.InvokeAsync("Initialize", new object[0], this.InitializeOperationCompleted, userState);
        }
        
        private void OnInitializeOperationCompleted(object arg) {
            if ((this.InitializeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeCompleted(this, new InitializeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/InitializeDataCreate", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillGroupDataCreate InitializeDataCreate() {
            object[] results = this.Invoke("InitializeDataCreate", new object[0]);
            return ((BillGroupDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInitializeDataCreate(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InitializeDataCreate", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public BillGroupDataCreate EndInitializeDataCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillGroupDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public void InitializeDataCreateAsync() {
            this.InitializeDataCreateAsync(null);
        }
        
        /// <remarks/>
        public void InitializeDataCreateAsync(object userState) {
            if ((this.InitializeDataCreateOperationCompleted == null)) {
                this.InitializeDataCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializeDataCreateOperationCompleted);
            }
            this.InvokeAsync("InitializeDataCreate", new object[0], this.InitializeDataCreateOperationCompleted, userState);
        }
        
        private void OnInitializeDataCreateOperationCompleted(object arg) {
            if ((this.InitializeDataCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializeDataCreateCompleted(this, new InitializeDataCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/GetDataCreate", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillGroupDataCreate GetDataCreate(BillGroupData data) {
            object[] results = this.Invoke("GetDataCreate", new object[] {
                        data});
            return ((BillGroupDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataCreate(BillGroupData data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataCreate", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public BillGroupDataCreate EndGetDataCreate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillGroupDataCreate)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataCreateAsync(BillGroupData data) {
            this.GetDataCreateAsync(data, null);
        }
        
        /// <remarks/>
        public void GetDataCreateAsync(BillGroupData data, object userState) {
            if ((this.GetDataCreateOperationCompleted == null)) {
                this.GetDataCreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataCreateOperationCompleted);
            }
            this.InvokeAsync("GetDataCreate", new object[] {
                        data}, this.GetDataCreateOperationCompleted, userState);
        }
        
        private void OnGetDataCreateOperationCompleted(object arg) {
            if ((this.GetDataCreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCreateCompleted(this, new GetDataCreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/GetDataUpdate", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillGroupDataUpdate GetDataUpdate(BillGroupData data) {
            object[] results = this.Invoke("GetDataUpdate", new object[] {
                        data});
            return ((BillGroupDataUpdate)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetDataUpdate(BillGroupData data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDataUpdate", new object[] {
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public BillGroupDataUpdate EndGetDataUpdate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillGroupDataUpdate)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUpdateAsync(BillGroupData data) {
            this.GetDataUpdateAsync(data, null);
        }
        
        /// <remarks/>
        public void GetDataUpdateAsync(BillGroupData data, object userState) {
            if ((this.GetDataUpdateOperationCompleted == null)) {
                this.GetDataUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUpdateOperationCompleted);
            }
            this.InvokeAsync("GetDataUpdate", new object[] {
                        data}, this.GetDataUpdateOperationCompleted, userState);
        }
        
        private void OnGetDataUpdateOperationCompleted(object arg) {
            if ((this.GetDataUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUpdateCompleted(this, new GetDataUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/ReadSingle", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillGroupData ReadSingle(int billGrpUno) {
            object[] results = this.Invoke("ReadSingle", new object[] {
                        billGrpUno});
            return ((BillGroupData)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginReadSingle(int billGrpUno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ReadSingle", new object[] {
                        billGrpUno}, callback, asyncState);
        }
        
        /// <remarks/>
        public BillGroupData EndReadSingle(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillGroupData)(results[0]));
        }
        
        /// <remarks/>
        public void ReadSingleAsync(int billGrpUno) {
            this.ReadSingleAsync(billGrpUno, null);
        }
        
        /// <remarks/>
        public void ReadSingleAsync(int billGrpUno, object userState) {
            if ((this.ReadSingleOperationCompleted == null)) {
                this.ReadSingleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadSingleOperationCompleted);
            }
            this.InvokeAsync("ReadSingle", new object[] {
                        billGrpUno}, this.ReadSingleOperationCompleted, userState);
        }
        
        private void OnReadSingleOperationCompleted(object arg) {
            if ((this.ReadSingleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadSingleCompleted(this, new ReadSingleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cmsopen.com/Read", RequestNamespace="http://cmsopen.com/", ResponseNamespace="http://cmsopen.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BillGroupData[] Read(string filter) {
            object[] results = this.Invoke("Read", new object[] {
                        filter});
            return ((BillGroupData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRead(string filter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Read", new object[] {
                        filter}, callback, asyncState);
        }
        
        /// <remarks/>
        public BillGroupData[] EndRead(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BillGroupData[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string filter) {
            this.ReadAsync(filter, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string filter, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        filter}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class BillGroupDataCreate : BillGroupDataBase {
        
        private string billGrpCodeField;
        
        private int clientUnoField;
        
        /// <remarks/>
        public string BillGrpCode {
            get {
                return this.billGrpCodeField;
            }
            set {
                this.billGrpCodeField = value;
            }
        }
        
        /// <remarks/>
        public int ClientUno {
            get {
                return this.clientUnoField;
            }
            set {
                this.clientUnoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BillGroupData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BillGroupDataUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BillGroupDataCreate))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class BillGroupDataBase {
        
        private int addressUnoField;
        
        private string billGrpDescField;
        
        private int blEmplUnoField;
        
        private int blFormatUnoField;
        
        private string collectionsOkField;
        
        private int colAddressUnoField;
        
        private int colContactUnoField;
        
        private int colEmplUnoField;
        
        private int colTkEmplUnoField;
        
        private int contactUnoField;
        
        private int copiesField;
        
        private string currencyCodeField;
        
        private int gracePeriodField;
        
        private string inactiveField;
        
        private string interestBaseField;
        
        private double interestRateField;
        
        private string interestSourceField;
        
        private int intDueAdjField;
        
        private string isDefaultField;
        
        private string isRfpBillField;
        
        private string jurisdicCodeField;
        
        private string languageCodeField;
        
        private decimal maxDisbBillField;
        
        private decimal maxFeeBillField;
        
        private decimal maxTotalBillField;
        
        private decimal minDisbBillField;
        
        private decimal minFeeBillField;
        
        private decimal minTotalBillField;
        
        private string offcField;
        
        private int pbFormatUnoField;
        
        private string printCurrencyField;
        
        private int reminderDaysField;
        
        private int rsFormatUnoField;
        
        private string ultimateRespField;
        
        private string useBillRateField;
        
        /// <remarks/>
        public int AddressUno {
            get {
                return this.addressUnoField;
            }
            set {
                this.addressUnoField = value;
            }
        }
        
        /// <remarks/>
        public string BillGrpDesc {
            get {
                return this.billGrpDescField;
            }
            set {
                this.billGrpDescField = value;
            }
        }
        
        /// <remarks/>
        public int BlEmplUno {
            get {
                return this.blEmplUnoField;
            }
            set {
                this.blEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public int BlFormatUno {
            get {
                return this.blFormatUnoField;
            }
            set {
                this.blFormatUnoField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionsOk {
            get {
                return this.collectionsOkField;
            }
            set {
                this.collectionsOkField = value;
            }
        }
        
        /// <remarks/>
        public int ColAddressUno {
            get {
                return this.colAddressUnoField;
            }
            set {
                this.colAddressUnoField = value;
            }
        }
        
        /// <remarks/>
        public int ColContactUno {
            get {
                return this.colContactUnoField;
            }
            set {
                this.colContactUnoField = value;
            }
        }
        
        /// <remarks/>
        public int ColEmplUno {
            get {
                return this.colEmplUnoField;
            }
            set {
                this.colEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public int ColTkEmplUno {
            get {
                return this.colTkEmplUnoField;
            }
            set {
                this.colTkEmplUnoField = value;
            }
        }
        
        /// <remarks/>
        public int ContactUno {
            get {
                return this.contactUnoField;
            }
            set {
                this.contactUnoField = value;
            }
        }
        
        /// <remarks/>
        public int Copies {
            get {
                return this.copiesField;
            }
            set {
                this.copiesField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public int GracePeriod {
            get {
                return this.gracePeriodField;
            }
            set {
                this.gracePeriodField = value;
            }
        }
        
        /// <remarks/>
        public string Inactive {
            get {
                return this.inactiveField;
            }
            set {
                this.inactiveField = value;
            }
        }
        
        /// <remarks/>
        public string InterestBase {
            get {
                return this.interestBaseField;
            }
            set {
                this.interestBaseField = value;
            }
        }
        
        /// <remarks/>
        public double InterestRate {
            get {
                return this.interestRateField;
            }
            set {
                this.interestRateField = value;
            }
        }
        
        /// <remarks/>
        public string InterestSource {
            get {
                return this.interestSourceField;
            }
            set {
                this.interestSourceField = value;
            }
        }
        
        /// <remarks/>
        public int IntDueAdj {
            get {
                return this.intDueAdjField;
            }
            set {
                this.intDueAdjField = value;
            }
        }
        
        /// <remarks/>
        public string IsDefault {
            get {
                return this.isDefaultField;
            }
            set {
                this.isDefaultField = value;
            }
        }
        
        /// <remarks/>
        public string IsRfpBill {
            get {
                return this.isRfpBillField;
            }
            set {
                this.isRfpBillField = value;
            }
        }
        
        /// <remarks/>
        public string JurisdicCode {
            get {
                return this.jurisdicCodeField;
            }
            set {
                this.jurisdicCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxDisbBill {
            get {
                return this.maxDisbBillField;
            }
            set {
                this.maxDisbBillField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxFeeBill {
            get {
                return this.maxFeeBillField;
            }
            set {
                this.maxFeeBillField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxTotalBill {
            get {
                return this.maxTotalBillField;
            }
            set {
                this.maxTotalBillField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinDisbBill {
            get {
                return this.minDisbBillField;
            }
            set {
                this.minDisbBillField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinFeeBill {
            get {
                return this.minFeeBillField;
            }
            set {
                this.minFeeBillField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinTotalBill {
            get {
                return this.minTotalBillField;
            }
            set {
                this.minTotalBillField = value;
            }
        }
        
        /// <remarks/>
        public string Offc {
            get {
                return this.offcField;
            }
            set {
                this.offcField = value;
            }
        }
        
        /// <remarks/>
        public int PbFormatUno {
            get {
                return this.pbFormatUnoField;
            }
            set {
                this.pbFormatUnoField = value;
            }
        }
        
        /// <remarks/>
        public string PrintCurrency {
            get {
                return this.printCurrencyField;
            }
            set {
                this.printCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public int ReminderDays {
            get {
                return this.reminderDaysField;
            }
            set {
                this.reminderDaysField = value;
            }
        }
        
        /// <remarks/>
        public int RsFormatUno {
            get {
                return this.rsFormatUnoField;
            }
            set {
                this.rsFormatUnoField = value;
            }
        }
        
        /// <remarks/>
        public string UltimateResp {
            get {
                return this.ultimateRespField;
            }
            set {
                this.ultimateRespField = value;
            }
        }
        
        /// <remarks/>
        public string UseBillRate {
            get {
                return this.useBillRateField;
            }
            set {
                this.useBillRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class BillGroupData : BillGroupDataBase {
        
        private string billGrpCodeField;
        
        private int billGrpUnoField;
        
        private int clientUnoField;
        
        private System.DateTime lastModifiedField;
        
        /// <remarks/>
        public string BillGrpCode {
            get {
                return this.billGrpCodeField;
            }
            set {
                this.billGrpCodeField = value;
            }
        }
        
        /// <remarks/>
        public int BillGrpUno {
            get {
                return this.billGrpUnoField;
            }
            set {
                this.billGrpUnoField = value;
            }
        }
        
        /// <remarks/>
        public int ClientUno {
            get {
                return this.clientUnoField;
            }
            set {
                this.clientUnoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cmsopen.com/")]
    public partial class BillGroupDataUpdate : BillGroupDataBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DeleteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InitializeCompletedEventHandler(object sender, InitializeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillGroupData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillGroupData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InitializeDataCreateCompletedEventHandler(object sender, InitializeDataCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializeDataCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializeDataCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillGroupDataCreate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillGroupDataCreate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDataCreateCompletedEventHandler(object sender, GetDataCreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillGroupDataCreate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillGroupDataCreate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDataUpdateCompletedEventHandler(object sender, GetDataUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillGroupDataUpdate Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillGroupDataUpdate)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadSingleCompletedEventHandler(object sender, ReadSingleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadSingleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadSingleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillGroupData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillGroupData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BillGroupData[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BillGroupData[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591