/****** Object:  StoredProcedure [dbo].[sprENTExportTime]    Script Date: 07/27/2012 14:30:23 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sprENTExportTime]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[sprENTExportTime]
GO


CREATE PROCEDURE [dbo].[sprENTExportTime]
AS

--CHECK IF A CUSTOM VERSION EXISTS - MUST RETURN SAME COLUMNS AS STANDARD VERSION
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[SPRENTEXPORTTIME_CUSTOM]') AND TYPE IN (N'P', N'PC'))
	EXEC [DBO].[SPRENTEXPORTTIME_CUSTOM]
ELSE
BEGIN
	SELECT
		ID
		, MAPPEDFILE.EXTERNALID													AS MATTERNUMBER
		, '-'																	AS CLIENTNAME			-- REMOVE THIS??
		, ISNULL ( TIMERECORDED_ACTUAL , DBO.UTCTOLOCALTIME ( TIMERECORDED )	)	AS [DATE] 
		, MAPPEDFEEEARNER.EXTERNALID											AS TIMEKEEPERINITIALS
		, 'FEES'																AS LEDGERCODE
		, ACT.ACTACCCODE														AS PRIMARYACTIVITYCODE
		, CONVERT ( DECIMAL ( 6 , 2 ) , TIMEMINS )  / 60 						AS [HOUR] 
		, ENTERPRISE_UDF2														AS UDF2
		, ENTERPRISE_UDF3														AS UDF3
		, ENTERPRISE_UDF4														AS UDF4
		, ENTERPRISE_UDF5														AS UDF5
		, TIMEDESC																AS [DESCRIPTION]		--CHECK MAX ON THIS COLUMN
	FROM
		DBTIMELEDGER TL
	LEFT OUTER JOIN 
		DBO.FDGETEXTERNALID ( 'ENTERPRISE' , 'FILE' ) MAPPEDFILE ON MAPPEDFILE.INTERNALID = CONVERT ( NVARCHAR ( 50 ) , TL.FILEID )
	LEFT OUTER JOIN
		DBO.FDGETEXTERNALID ( 'ENTERPRISE' , 'FEE EARNER' ) MAPPEDFEEEARNER ON MAPPEDFEEEARNER.INTERNALID = CONVERT ( NVARCHAR ( 50 ) , TL.FEEUSRID)
	INNER JOIN
		DBACTIVITIES ACT ON ACT.ACTCODE = TL.TIMEACTIVITYCODE
	WHERE
		TL.TIMETRANSFERRED = 0
END 



GO


