<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <ProductName>3E MatterSphere PDF Bundler</ProductName>
    <ShortProductName>PDF Bundler</ShortProductName>
    <UpgradeCode>82B3C2FC-902D-4D80-BD83-75AFBCE182DD</UpgradeCode>
    <SourceDir></SourceDir>
    <OutputName>3EMatterSpherePDFBundlerInstaller</OutputName>
  </PropertyGroup>

  <Import Project="..\..\Directory.Build.props"/>
</Project>
