
--REMOVE (R) FROM CODELOOKUP DESCRIPTION

UPDATE DBCODELOOKUP SET CDDESC = REPLACE ( CDDESC , 'MatterSphere' + char(174) , 'MatterSphere' ) WHERE CDDESC LIKE '%MatterSphere' + char(174) + '%'

--REMOVE (R) FROM CODELOOKUP HELP

UPDATE DBCODELOOKUP SET CDHELP = REPLACE ( CDHELP , 'MatterSphere' + char(174) , 'MatterSphere' ) WHERE CDHELP LIKE '%MatterSphere' + char(174) + '%'

--UPDATE MATTERSPHERE TO 3E MATTERSPHERE IN DESCRIPTION

UPDATE DBCODELOOKUP SET CDDESC = REPLACE ( CDDESC , 'MatterSphere' , '3E MatterSphere' ) WHERE CDDESC LIKE '%MatterSphere%' AND CDDESC NOT LIKE '%3E MATTERSPHERE%'

--UPDATE MATTERSPHERE TO 3E MATTERSPHERE IN HELP

UPDATE DBCODELOOKUP SET CDHELP = REPLACE ( CDHELP , 'MatterSphere' , '3E MatterSphere' ) WHERE CDHELP LIKE '%MatterSphere%' AND CDHELP NOT LIKE '%3E MATTERSPHERE%'

--UPDATE OMS FRAMEWORK SDK CODE LOOKUP IF NECESSARY

UPDATE DBCODELOOKUP SET CDDESC = REPLACE ( CDDESC , 'OMS Framework SDK' , '3E MatterSphere Framework SDK' ) WHERE CDDESC LIKE '%OMS Framework SDK%' AND CDDESC NOT LIKE '%3E MATTERSPHERE%'

--UPDATE PARTNER ACCESS CODE LOOKUP IF NECESSARY

UPDATE DBCODELOOKUP SET CDDESC = REPLACE ( CDDESC , 'OMS Framework SDK' , '3E MatterSphere Framework SDK' ) WHERE CDDESC LIKE '%OMS Framework SDK%' AND CDDESC NOT LIKE '%3E MATTERSPHERE%'

--UPDATE 3E MATTERSPHERE MAIN RIBBON XML

UPDATE DBCODELOOKUP SET CDDESC = REPLACE ( CDDESC , 'O&MS View' , '3E MatterSphere View' ) WHERE CDTYPE = 'CBCCAPTIONS' AND CDCODE = 'OMSVIEW'

--UPDATE OMS REPORTS TO 3E MATTERSPHERE REPORTS IN ADMIN KIT

UPDATE DBCODELOOKUP SET CDDESC = REPLACE ( CDDESC , 'OMS Reports' , '3E MatterSphere Reports' ) WHERE CDTYPE = 'RESOURCE' AND CDDESC LIKE '%OMS Reports%' AND CDDESC NOT LIKE '%3E MATTERSPHERE%'