/****** Object:  UserDefinedFunction [dbo].[fdGetExternalID]    Script Date: 05/15/2012 09:36:12 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[fdGetExternalID]') AND type in (N'FN', N'IF', N'TF', N'FS', N'FT'))
DROP FUNCTION [dbo].[fdGetExternalID]
GO

/****** Object:  UserDefinedFunction [dbo].[fdGetExternalID]    Script Date: 05/15/2012 09:36:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[fdGetExternalID] ( @SYSTEMNAME NVARCHAR ( 50 ) , @ENTITYNAME NVARCHAR ( 50 ) )

RETURNS TABLE AS --SYSTEM NVARCHAR ( 50 ) , ENTITY NVARCHAR ( 50 ) , INTERNALID NVARCHAR ( 60 ) , EXTERNALID NVARCHAR ( 50 ) ) AS
RETURN
(
	SELECT
		FDDBINTEGRATIONSYSTEM.NAME AS SystemName
		, FDDBINTEGRATIONENTITY.NAME AS EntityName
		, FDDBINTEGRATIONMAPPING.INTERNALID AS InternalID
		, FDDBINTEGRATIONMAPPING.EXTERNALID AS ExternalID
	FROM 
		FDDBINTEGRATIONMAPPING 
	INNER JOIN 
		FDDBINTEGRATIONSYSTEM ON FDDBINTEGRATIONMAPPING.SYSTEMID = FDDBINTEGRATIONSYSTEM.ID
	INNER JOIN 
		FDDBINTEGRATIONENTITY ON FDDBINTEGRATIONMAPPING.ENTITYID = FDDBINTEGRATIONENTITY.ID
	WHERE
		FDDBINTEGRATIONSYSTEM.NAME = @SYSTEMNAME AND
		FDDBINTEGRATIONENTITY.NAME = @ENTITYNAME
)

GO


