CREATE PROCEDURE [dbo].[wsClientListView]
@FEEUSRID bigint,
@SEARCH_TEXT nvarchar(MAX) = null,
@FILTERID nvarchar(MAX) = null,
@DATAKEYS nvarchar(MAX) = null
AS


PRINT '@DATAKEYS'
PRINT @DATAKEYS
PRINT '@SEARCH_TEXT'
PRINT @SEARCH_TEXT
PRINT '@FEEUSRID'
PRINT @FEEUSRID
PRINT '@FILTERID'
PRINT @FILTERID

--RESET FEEUSRID BASED ON FILTERS
IF @FILTERID = 'ALL' OR @FILTERID = 'RECENT' OR @FILTERID = 'FAVOURITES'
BEGIN
	PRINT 'RESETTING @FEEUSRID'
	SET @FEEUSRID = NULL
END 

IF @DATAKEYS IS NULL 
BEGIN
	PRINT 'SECTION 1'
	SELECT
		CLID
		, CLNO
		, CLNAME 
		, DBCLIENT.BRID
		, BRNAME
		, DBCLIENT.CREATED
		, DBUSER.USRFULLNAME AS FIRMCONTACT
		, DBCLIENT.FEEUSRID
	FROM
		DBCLIENT  WITH ( NOLOCK ) 
	INNER JOIN 
		DBUSER ON DBCLIENT.FEEUSRID = DBUSER.USRID
	INNER JOIN 
		DBBRANCH ON DBCLIENT.BRID = DBBRANCH.BRID
	WHERE
		DBCLIENT.FEEUSRID = ISNULL ( @FEEUSRID , DBCLIENT.FEEUSRID ) AND 
		( 
			DBCLIENT.CLNAME LIKE '%' +  ISNULL ( @SEARCH_TEXT , DBCLIENT.CLNAME ) + '%' OR
			ISNULL ( DBCLIENT.CLSEARCH1 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH1 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH2 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH2 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH3 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH3 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH4 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH4 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH5 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH5 , '' ) )  OR
			CLNO = @SEARCH_TEXT
		)
	ORDER BY
		CREATED
END  

IF @DATAKEYS IS NOT NULL 
BEGIN
	SELECT
		CLID
		, CLNO
		, CLNAME 
		, DBCLIENT.BRID
		, BRNAME
		, DBCLIENT.CREATED
		, DBUSER.USRFULLNAME AS FIRMCONTACT
		, DBCLIENT.FEEUSRID
	FROM
		DBCLIENT  WITH ( NOLOCK ) 
	INNER JOIN 
		DBUSER ON DBCLIENT.FEEUSRID = DBUSER.USRID
	INNER JOIN 
		DBBRANCH ON DBCLIENT.BRID = DBBRANCH.BRID
	WHERE
		CLID IN ( SELECT VALUE FROM DBO.SPLITSTRING ( @DATAKEYS , ',' ) ) AND
		DBCLIENT.FEEUSRID = ISNULL ( @FEEUSRID , DBCLIENT.FEEUSRID ) AND 
		( 
			DBCLIENT.CLNAME LIKE '%' +  ISNULL ( @SEARCH_TEXT , DBCLIENT.CLNAME ) + '%' OR
			ISNULL ( DBCLIENT.CLSEARCH1 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH1 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH2 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH2 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH3 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH3 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH4 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH4 , '' ) ) OR 
			ISNULL ( DBCLIENT.CLSEARCH5 , '' ) = ISNULL ( @SEARCH_TEXT , ISNULL ( DBCLIENT.CLSEARCH5 , '' ) )  OR
			CLNO = @SEARCH_TEXT
		)
	ORDER BY
		CREATED
END
