CREATE PROCEDURE [dbo].[wsFileListView]
@FEEUSRID bigint,
@UI NVARCHAR(15)='en-gb',
@SEARCH_TEXT nvarchar(MAX) = null,
@FILTERID nvarchar(MAX) = null,
@DATAKEYS nvarchar(MAX) = null
AS

--RESET FEEUSRID BASED ON FILTERS
IF @FILTERID = 'ALL'
BEGIN
       PRINT 'RESETTING @FEEUSRID'
       SET @FEEUSRID = NULL
END 

IF @FILTERID = 'TIMELOOKUP'
BEGIN
       SELECT TOP(100)
              FILEID
              , CLNO + '-' + FILENO + ' / ' + FILEDESC AS FILEDESC
       FROM
              DBFILE
       INNER JOIN 
              DBCLIENT ON DBFILE.CLID = DBCLIENT.CLID
			WHERE
              DBFILE.FILEPRINCIPLEID  = ISNULL ( @FEEUSRID , DBFILE.FILEPRINCIPLEID ) AND   
              DBFILE.FILEDESC LIKE '%' +  ISNULL ( @SEARCH_TEXT , DBFILE.FILEDESC ) + '%'  OR
              DBCLIENT.CLNO + '-' + DBFILE.FILENO LIKE '%' + ISNULL( @SEARCH_TEXT, DBCLIENT.CLNO + '-' + DBFILE.FILENO  ) + '%'
       ORDER BY 
              DBCLIENT.CLNO
              , DBFILE.CREATED
       RETURN
END 

IF @DATAKEYS IS NULL 
BEGIN
       SELECT TOP(5000)
              DBFILE.FILEID
              , DBFILE.CLID
              , DBCLIENT.CLNO
              , DBCLIENT.CLNAME 
              , DBCLIENT.BRID
              , DBBRANCH.BRNAME
              , DBFILE.CREATED
              , DBFILE.FILENO
              , DBCLIENT.CLNO + '-' + DBFILE.FILENO AS CLIENTFILE
              , DBFILE.FILEDESC
              , DBUSER.USRFULLNAME
              , LOOKUP_FILETYPE.CDDESC AS FILETYPE_DESC
       FROM
              DBCLIENT  WITH ( NOLOCK ) 
       INNER JOIN 
              DBFILE ON DBFILE.CLID = DBCLIENT.CLID
       INNER JOIN 
              DBBRANCH ON DBFILE.BRID = DBBRANCH.BRID
       INNER JOIN
              DBUSER ON DBFILE.FILEPRINCIPLEID=DBUSER.USRID
       LEFT JOIN 
              DBO.GETCODELOOKUPDESCRIPTION ( 'FILETYPE' , @UI ) AS LOOKUP_FILETYPE ON LOOKUP_FILETYPE.CDCODE = DBFILE.FILETYPE
       WHERE
              DBFILE.FILEPRINCIPLEID  = ISNULL ( @FEEUSRID , DBFILE.FILEPRINCIPLEID ) AND   
              DBFILE.FILEDESC LIKE '%' +  ISNULL ( @SEARCH_TEXT , DBFILE.FILEDESC ) + '%'  OR
              DBCLIENT.CLNO + '-' + DBFILE.FILENO LIKE '%' + @SEARCH_TEXT + '%'
       ORDER BY
              DBCLIENT.CLNO
			  , DBFILE.CREATED
END


IF @DATAKEYS IS NOT NULL 
BEGIN
    SELECT TOP(5000)
              DBFILE.FILEID
              , DBFILE.CLID
              , DBCLIENT.CLNO
              , DBCLIENT.CLNAME 
              , DBCLIENT.BRID
              , DBBRANCH.BRNAME
              , DBFILE.CREATED
              , DBFILE.FILENO
              , DBCLIENT.CLNO + '-' + DBFILE.FILENO AS CLIENTFILE
              , DBFILE.FILEDESC
              , DBUSER.USRFULLNAME
              , LOOKUP_FILETYPE.CDDESC AS FILETYPE_DESC
       FROM
              DBCLIENT  WITH ( NOLOCK ) 
       INNER JOIN 
              DBFILE ON DBFILE.CLID = DBCLIENT.CLID
       INNER JOIN 
              DBBRANCH ON DBFILE.BRID = DBBRANCH.BRID
       INNER JOIN
              DBUSER ON DBFILE.FILEPRINCIPLEID=DBUSER.USRID
       LEFT JOIN 
              DBO.GETCODELOOKUPDESCRIPTION ( 'FILETYPE' , @UI ) AS LOOKUP_FILETYPE ON LOOKUP_FILETYPE.CDCODE = DBFILE.FILETYPE
       WHERE
          DBFILE.FILEID IN ( SELECT VALUE FROM DBO.SPLITSTRING ( @DATAKEYS , ',' ) ) AND
          (DBFILE.FILEDESC LIKE '%' +  ISNULL ( @SEARCH_TEXT ,        DBFILE.FILEDESC ) + '%' OR
          DBCLIENT.CLNO + '-' + DBFILE.FILENO LIKE '%' + @SEARCH_TEXT + '%')
       ORDER BY
              DBCLIENT.CLNO, DBFILE.Created
END 
