CREATE FUNCTION [dbo].[GetFolderCodesForClientDocumentTree] (@clientID BIGINT, @UI NVARCHAR(15))
RETURNS TABLE
AS
RETURN
(
SELECT
	CAST(NULL AS NVARCHAR(15)) AS FolderCode
	, CAST(NULL AS UNIQUEIDENTIFIER) AS FolderGUID
	, CAST(NULL AS NVARCHAR(100)) AS FolderDescription 
)
