//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FWBS.ExternalAggregatorClient.ServiceAggregator
{


    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceAggregatorEndpoint", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Request))]
    public partial class SystemAggregator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetSecurityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApplyTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArchiveFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArchiveDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArchiveFileForceReleaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArchiveDocumentForceReleaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SystemAggregator() {
            this.Url = "http://localhost:10845/ServiceAggregator";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateClientCompletedEventHandler CreateClientCompleted;
        
        /// <remarks/>
        public event CreateFileCompletedEventHandler CreateFileCompleted;
        
        /// <remarks/>
        public event SetSecurityCompletedEventHandler SetSecurityCompleted;
        
        /// <remarks/>
        public event ApplyTemplateCompletedEventHandler ApplyTemplateCompleted;
        
        /// <remarks/>
        public event ArchiveFileCompletedEventHandler ArchiveFileCompleted;
        
        /// <remarks/>
        public event ArchiveDocumentCompletedEventHandler ArchiveDocumentCompleted;
        
        /// <remarks/>
        public event ArchiveFileForceReleaseCompletedEventHandler ArchiveFileForceReleaseCompleted;
        
        /// <remarks/>
        public event ArchiveDocumentForceReleaseCompletedEventHandler ArchiveDocumentForceReleaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/CreateClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CreateClientResponse CreateClient([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ClientDetailsRequest client) {
            object[] results = this.Invoke("CreateClient", new object[] {
                        client});
            return ((CreateClientResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateClientAsync(ClientDetailsRequest client) {
            this.CreateClientAsync(client, null);
        }
        
        /// <remarks/>
        public void CreateClientAsync(ClientDetailsRequest client, object userState) {
            if ((this.CreateClientOperationCompleted == null)) {
                this.CreateClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateClientOperationCompleted);
            }
            this.InvokeAsync("CreateClient", new object[] {
                        client}, this.CreateClientOperationCompleted, userState);
        }
        
        private void OnCreateClientOperationCompleted(object arg) {
            if ((this.CreateClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateClientCompleted(this, new CreateClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/CreateFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CreateFileResponse CreateFile([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] FileDetailsRequest client) {
            object[] results = this.Invoke("CreateFile", new object[] {
                        client});
            return ((CreateFileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreateFileAsync(FileDetailsRequest client) {
            this.CreateFileAsync(client, null);
        }
        
        /// <remarks/>
        public void CreateFileAsync(FileDetailsRequest client, object userState) {
            if ((this.CreateFileOperationCompleted == null)) {
                this.CreateFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateFileOperationCompleted);
            }
            this.InvokeAsync("CreateFile", new object[] {
                        client}, this.CreateFileOperationCompleted, userState);
        }
        
        private void OnCreateFileOperationCompleted(object arg) {
            if ((this.CreateFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateFileCompleted(this, new CreateFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/SetSecurity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SetSecurityResponse SetSecurity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SetSecurityRequest security) {
            object[] results = this.Invoke("SetSecurity", new object[] {
                        security});
            return ((SetSecurityResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SetSecurityAsync(SetSecurityRequest security) {
            this.SetSecurityAsync(security, null);
        }
        
        /// <remarks/>
        public void SetSecurityAsync(SetSecurityRequest security, object userState) {
            if ((this.SetSecurityOperationCompleted == null)) {
                this.SetSecurityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSecurityOperationCompleted);
            }
            this.InvokeAsync("SetSecurity", new object[] {
                        security}, this.SetSecurityOperationCompleted, userState);
        }
        
        private void OnSetSecurityOperationCompleted(object arg) {
            if ((this.SetSecurityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSecurityCompleted(this, new SetSecurityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/ApplyTemplate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ApplyTemplateResponse ApplyTemplate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ApplyTemplateRequest template) {
            object[] results = this.Invoke("ApplyTemplate", new object[] {
                        template});
            return ((ApplyTemplateResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ApplyTemplateAsync(ApplyTemplateRequest template) {
            this.ApplyTemplateAsync(template, null);
        }
        
        /// <remarks/>
        public void ApplyTemplateAsync(ApplyTemplateRequest template, object userState) {
            if ((this.ApplyTemplateOperationCompleted == null)) {
                this.ApplyTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApplyTemplateOperationCompleted);
            }
            this.InvokeAsync("ApplyTemplate", new object[] {
                        template}, this.ApplyTemplateOperationCompleted, userState);
        }
        
        private void OnApplyTemplateOperationCompleted(object arg) {
            if ((this.ApplyTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApplyTemplateCompleted(this, new ApplyTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/ArchiveFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArchiveFileResponse ArchiveFile([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArchiveFileRequest file) {
            object[] results = this.Invoke("ArchiveFile", new object[] {
                        file});
            return ((ArchiveFileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ArchiveFileAsync(ArchiveFileRequest file) {
            this.ArchiveFileAsync(file, null);
        }
        
        /// <remarks/>
        public void ArchiveFileAsync(ArchiveFileRequest file, object userState) {
            if ((this.ArchiveFileOperationCompleted == null)) {
                this.ArchiveFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArchiveFileOperationCompleted);
            }
            this.InvokeAsync("ArchiveFile", new object[] {
                        file}, this.ArchiveFileOperationCompleted, userState);
        }
        
        private void OnArchiveFileOperationCompleted(object arg) {
            if ((this.ArchiveFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArchiveFileCompleted(this, new ArchiveFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/ArchiveDocument", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArchiveDocumentResponse ArchiveDocument([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArchiveDocumentRequest document) {
            object[] results = this.Invoke("ArchiveDocument", new object[] {
                        document});
            return ((ArchiveDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ArchiveDocumentAsync(ArchiveDocumentRequest document) {
            this.ArchiveDocumentAsync(document, null);
        }
        
        /// <remarks/>
        public void ArchiveDocumentAsync(ArchiveDocumentRequest document, object userState) {
            if ((this.ArchiveDocumentOperationCompleted == null)) {
                this.ArchiveDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArchiveDocumentOperationCompleted);
            }
            this.InvokeAsync("ArchiveDocument", new object[] {
                        document}, this.ArchiveDocumentOperationCompleted, userState);
        }
        
        private void OnArchiveDocumentOperationCompleted(object arg) {
            if ((this.ArchiveDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArchiveDocumentCompleted(this, new ArchiveDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/ArchiveFileForceRelease", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArchiveFileResponse ArchiveFileForceRelease([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArchiveFileRequest file) {
            object[] results = this.Invoke("ArchiveFileForceRelease", new object[] {
                        file});
            return ((ArchiveFileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ArchiveFileForceReleaseAsync(ArchiveFileRequest file) {
            this.ArchiveFileForceReleaseAsync(file, null);
        }
        
        /// <remarks/>
        public void ArchiveFileForceReleaseAsync(ArchiveFileRequest file, object userState) {
            if ((this.ArchiveFileForceReleaseOperationCompleted == null)) {
                this.ArchiveFileForceReleaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArchiveFileForceReleaseOperationCompleted);
            }
            this.InvokeAsync("ArchiveFileForceRelease", new object[] {
                        file}, this.ArchiveFileForceReleaseOperationCompleted, userState);
        }
        
        private void OnArchiveFileForceReleaseOperationCompleted(object arg) {
            if ((this.ArchiveFileForceReleaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArchiveFileForceReleaseCompleted(this, new ArchiveFileForceReleaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISystemAggregator/ArchiveDocumentForceRelease", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ArchiveDocumentResponse ArchiveDocumentForceRelease([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] ArchiveDocumentRequest document) {
            object[] results = this.Invoke("ArchiveDocumentForceRelease", new object[] {
                        document});
            return ((ArchiveDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ArchiveDocumentForceReleaseAsync(ArchiveDocumentRequest document) {
            this.ArchiveDocumentForceReleaseAsync(document, null);
        }
        
        /// <remarks/>
        public void ArchiveDocumentForceReleaseAsync(ArchiveDocumentRequest document, object userState) {
            if ((this.ArchiveDocumentForceReleaseOperationCompleted == null)) {
                this.ArchiveDocumentForceReleaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArchiveDocumentForceReleaseOperationCompleted);
            }
            this.InvokeAsync("ArchiveDocumentForceRelease", new object[] {
                        document}, this.ArchiveDocumentForceReleaseOperationCompleted, userState);
        }
        
        private void OnArchiveDocumentForceReleaseOperationCompleted(object arg) {
            if ((this.ArchiveDocumentForceReleaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArchiveDocumentForceReleaseCompleted(this, new ArchiveDocumentForceReleaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class ClientDetailsRequest : Request {
        
        private string clientIdField;
        
        private string clientNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchiveDocumentRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchiveFileRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplyTemplateRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetSecurityRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileDetailsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientDetailsRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class Request {
        
        private string databaseField;
        
        private ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] extendedPropertiesField;
        
        private string serverNameField;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] ExtendedProperties {
            get {
                return this.extendedPropertiesField;
            }
            set {
                this.extendedPropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchiveDocumentResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArchiveFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ApplyTemplateResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetSecurityResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreateClientResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class Response {
        
        private string errorField;
        
        private bool hasErrorField;
        
        private bool hasErrorFieldSpecified;
        
        private string systemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public bool HasError {
            get {
                return this.hasErrorField;
            }
            set {
                this.hasErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasErrorSpecified {
            get {
                return this.hasErrorFieldSpecified;
            }
            set {
                this.hasErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string System {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class ArchiveDocumentResponse : Response {
        
        private int archivedDocumentIdField;
        
        private bool archivedDocumentIdFieldSpecified;
        
        /// <remarks/>
        public int ArchivedDocumentId {
            get {
                return this.archivedDocumentIdField;
            }
            set {
                this.archivedDocumentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArchivedDocumentIdSpecified {
            get {
                return this.archivedDocumentIdFieldSpecified;
            }
            set {
                this.archivedDocumentIdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class ArchiveFileResponse : Response {
        
        private string archivedClientIdField;
        
        private string archivedFileIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArchivedClientId {
            get {
                return this.archivedClientIdField;
            }
            set {
                this.archivedClientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ArchivedFileId {
            get {
                return this.archivedFileIdField;
            }
            set {
                this.archivedFileIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class ApplyTemplateResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class SetSecurityResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class CreateFileResponse : Response {
        
        private string createdFileIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreatedFileId {
            get {
                return this.createdFileIdField;
            }
            set {
                this.createdFileIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.ExternalSystemAggregatorService.Resp" +
        "onses")]
    public partial class CreateClientResponse : Response {
        
        private string createdClientIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CreatedClientId {
            get {
                return this.createdClientIdField;
            }
            set {
                this.createdClientIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class ArchiveDocumentRequest : Request {
        
        private string callingUserField;
        
        private int documentIdField;
        
        private bool documentIdFieldSpecified;
        
        private string securityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallingUser {
            get {
                return this.callingUserField;
            }
            set {
                this.callingUserField = value;
            }
        }
        
        /// <remarks/>
        public int DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentIdSpecified {
            get {
                return this.documentIdFieldSpecified;
            }
            set {
                this.documentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecurityKey {
            get {
                return this.securityKeyField;
            }
            set {
                this.securityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class ArchiveFileRequest : Request {
        
        private string callingUserField;
        
        private string clientIdField;
        
        private string fileIdField;
        
        private string securityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CallingUser {
            get {
                return this.callingUserField;
            }
            set {
                this.callingUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SecurityKey {
            get {
                return this.securityKeyField;
            }
            set {
                this.securityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class ApplyTemplateRequest : Request {
        
        private string clientIdField;
        
        private string descriptionField;
        
        private string displayNameField;
        
        private string fileIdField;
        
        private string templateNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DisplayName {
            get {
                return this.displayNameField;
            }
            set {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TemplateName {
            get {
                return this.templateNameField;
            }
            set {
                this.templateNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class SetSecurityRequest : Request {
        
        private string clientIdField;
        
        private string contactIdField;
        
        private string documentIdField;
        
        private string fileIdField;
        
        private ArrayOfKeyValueOfstringunsignedIntKeyValueOfstringunsignedInt[] groupPermissionsField;
        
        private ArrayOfKeyValueOfstringunsignedIntKeyValueOfstringunsignedInt[] userPermissionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactId {
            get {
                return this.contactIdField;
            }
            set {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringunsignedInt", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringunsignedIntKeyValueOfstringunsignedInt[] GroupPermissions {
            get {
                return this.groupPermissionsField;
            }
            set {
                this.groupPermissionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringunsignedInt", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public ArrayOfKeyValueOfstringunsignedIntKeyValueOfstringunsignedInt[] UserPermissions {
            get {
                return this.userPermissionsField;
            }
            set {
                this.userPermissionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringunsignedIntKeyValueOfstringunsignedInt {
        
        private string keyField;
        
        private uint valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public uint Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/FWBS.Requests")]
    public partial class FileDetailsRequest : Request {
        
        private string clientIdField;
        
        private string fileIdField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ClientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CreateClientCompletedEventHandler(object sender, CreateClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateClientResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateClientResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CreateFileCompletedEventHandler(object sender, CreateFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CreateFileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CreateFileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SetSecurityCompletedEventHandler(object sender, SetSecurityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSecurityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSecurityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SetSecurityResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SetSecurityResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ApplyTemplateCompletedEventHandler(object sender, ApplyTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplyTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApplyTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplyTemplateResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplyTemplateResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ArchiveFileCompletedEventHandler(object sender, ArchiveFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArchiveFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArchiveFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArchiveFileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArchiveFileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ArchiveDocumentCompletedEventHandler(object sender, ArchiveDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArchiveDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArchiveDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArchiveDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArchiveDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ArchiveFileForceReleaseCompletedEventHandler(object sender, ArchiveFileForceReleaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArchiveFileForceReleaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArchiveFileForceReleaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArchiveFileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArchiveFileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ArchiveDocumentForceReleaseCompletedEventHandler(object sender, ArchiveDocumentForceReleaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArchiveDocumentForceReleaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArchiveDocumentForceReleaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ArchiveDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ArchiveDocumentResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591