-- TABS. Create the caption for the tab used on configurable types
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'DLGTABCAPTION' AND CDCODE = 'FDSCRCLIENTINFO' )
INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC )
VALUES ( 'DLGTABCAPTION' , 'FDSCRCLIENTINFO' , 'Enterprise %CLIENT% Information' )

IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'DLGTABCAPTION' AND CDCODE = 'FDSCRFILENTINFO' )
INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC )
VALUES ( 'DLGTABCAPTION' , 'FDSCRFILENTINFO' , 'Enterprise %FILE% Information' )

IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'DLGTABCAPTION' AND CDCODE = 'FDSCRCOMENTINFO' )
INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC )
VALUES ( 'DLGTABCAPTION' , 'FDSCRCOMENTINFO' , 'Enterprise %FEEEARNER% Information' )


-- Command Centre WebView action panel buttons
IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'SLPBUTTON' AND CDCODE = 'FDWEBVIEW' )
INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC )
VALUES ( 'SLPBUTTON' , 'FDWEBVIEW' , 'WebView' )

IF NOT EXISTS ( SELECT * FROM DBCODELOOKUP WHERE CDTYPE = 'SLPBUTTON' AND CDCODE = 'FDMODTIME' )
INSERT INTO DBCODELOOKUP ( CDTYPE , CDCODE , CDDESC )
VALUES ( 'SLPBUTTON' , 'FDMODTIME' , 'Modify Time' )